import type { KinId } from "./extras/kin.ts";
import type { AugmentId, KitId, SysId } from "./types.ts";

/**
 * Hangar rows whose cruiser pages returned text.
 * The Kestrel Cruiser, The Engi Cruiser, The Federation Cruiser: layout blocks.
 * Tile positions are not on those pages (they are pictures). Every hull uses the
 * shared original room grid. INFERRED coordinates. The pictures were not copied.
 *
 * Power splits are INFERRED. The pages list system levels, not which bars start filled.
 * Bars are filled until the reactor is spent, weapons first when the guns need them.
 * Scrap is not on these pages. The caller keeps the existing 10.
 *
 * INVENTED: the pages lock layouts behind achievements. This list does not.
 */

export type HullCrew = {
  kin: KinId;
  room: string;
};

export type HullKit = {
  level: number;
  power: number;
  /** Swarm schematic id, when the kit is drone control. */
  target?: string | null;
  /** Defaults to on when power is above 0. */
  on?: boolean;
};

export type HullSpec = {
  id: string;
  cruiser: string;
  layout: "A" | "B" | "C";
  name: string;
  quote: string;
  unlock: string;
  /** Wiki page the numbers were taken from. */
  source: string;
  reactor: number;
  fuel: number;
  missiles: number;
  parts: number;
  systems: Partial<Record<SysId, [number, number]>>;
  weapons: string[];
  crew: HullCrew[];
  kits: Partial<Record<KitId, HullKit>>;
  augments: AugmentId[];
  /** Named on the page, with no matching id or slot in this build. */
  unfitted: string[];
};

const sub = {
  pilot: [1, 1] as [number, number],
  doors: [1, 1] as [number, number],
};

export const HULLS: HullSpec[] = [
  {
    id: "kestrel-a",
    cruiser: "Kestrel Cruiser",
    layout: "A",
    name: "The Kestrel",
    quote:
      "This class of ship was decommissioned from Federation service years ago. After a number of refits and updating, this classic ship is ready for battle.",
    unlock: "Available from the start. It is the only layout that does not need an unlock.",
    source: "The Kestrel Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 8,
    parts: 2,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [3, 3],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["lineburst", "artemis"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "plain", room: "p-engines" },
      { kin: "plain", room: "p-weapons" },
    ],
    kits: {},
    augments: [],
    unfitted: [],
  },
  {
    id: "kestrel-b",
    cruiser: "Kestrel Cruiser",
    layout: "B",
    name: "Red-Tail",
    quote: "This modified Kestrel class ship was created by a laser weapon aficionado.",
    unlock: "Earn at least two of the three Kestrel Cruiser achievements.",
    source: "The Kestrel Cruiser, Layout B",
    reactor: 8,
    fuel: 16,
    missiles: 5,
    parts: 0,
    // Four lasers need 4 weapon bars. Shields 2 and engines 2 use the rest. Oxygen starts off. INFERRED.
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 0],
      medbay: [1, 0],
      weapons: [4, 4],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["spark", "spark", "spark", "spark"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "plain", room: "p-engines" },
      { kin: "blade", room: "p-weapons" },
      { kin: "spark", room: "p-shields" },
    ],
    kits: {},
    augments: [],
    unfitted: [],
  },
  {
    id: "kestrel-c",
    cruiser: "Kestrel Cruiser",
    layout: "C",
    name: "The Swallow",
    quote:
      "This model was modified by pirates to utilize newly discovered technology. It can clone lost crewmembers and stun enemies.",
    unlock: "Reach the final sector with Kestrel layout B, Advanced Edition on.",
    source: "The Kestrel Cruiser, Layout C",
    reactor: 7,
    fuel: 16,
    missiles: 4,
    parts: 3,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [2, 2],
      sensors: [2, 2],
      ...sub,
    },
    weapons: ["twin", "stunner"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "plain", room: "p-engines" },
      { kin: "voidlung", room: "p-weapons" },
    ],
    // Clone Bay is installed. No reactor left for its bar. INFERRED: it starts unpowered.
    kits: { cradle: { level: 1, power: 0 } },
    augments: [],
    unfitted: [],
  },
  {
    id: "engi-a",
    cruiser: "Engi Cruiser",
    layout: "A",
    name: "The Torus",
    quote:
      "Although it may look like a pile of junk loosely held together, this well designed ship relies on drones and ion weaponry.",
    unlock: "Reach sector 5 with any Kestrel layout.",
    source: "The Engi Cruiser, Layout A",
    reactor: 10,
    fuel: 16,
    missiles: 0,
    parts: 15,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [3, 3],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["ion2"],
    crew: [
      { kin: "shell", room: "p-pilot" },
      { kin: "shell", room: "p-engines" },
      { kin: "plain", room: "p-weapons" },
    ],
    // Drone Control (3). Combat Drone Mark I takes 2 of those bars.
    kits: { swarm: { level: 3, power: 2, target: "striker" } },
    augments: [],
    unfitted: ["Engi Med-bot Dispersal"],
  },
  {
    id: "engi-b",
    cruiser: "Engi Cruiser",
    layout: "B",
    name: "The Vortex",
    quote: "Heavily understaffed, this ship relies on drones to keep the ship running.",
    unlock: "Earn at least two of the three Engi Cruiser achievements.",
    source: "The Engi Cruiser, Layout B",
    reactor: 9,
    fuel: 16,
    missiles: 0,
    parts: 6,
    // The page lists no Sensors.
    systems: {
      shields: [2, 2],
      engines: [1, 1],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [3, 3],
      sensors: [0, 0],
      ...sub,
    },
    weapons: ["heavyion", "heavy"],
    crew: [{ kin: "shell", room: "p-pilot" }],
    // One schematic slot. System Repair is the one this build can store. The other two are unfitted.
    kits: { swarm: { level: 3, power: 1, target: "patch" } },
    augments: [],
    unfitted: ["Drone Reactor Booster", "Anti-Personnel Drone", "System Repair Drone (second)"],
  },
  {
    id: "engi-c",
    cruiser: "Engi Cruiser",
    layout: "C",
    name: "Tetragon",
    quote:
      "The Engi were quick to adapt to the sudden surge of hacking technology — this ship is the result of their research.",
    unlock: "Reach the final sector with Engi layout B, Advanced Edition on.",
    source: "The Engi Cruiser, Layout C",
    reactor: 9,
    fuel: 16,
    missiles: 0,
    parts: 25,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [1, 1],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["twin"],
    crew: [
      { kin: "voidlung", room: "p-pilot" },
      { kin: "shell", room: "p-engines" },
      { kin: "shell", room: "p-weapons" },
    ],
    kits: {
      swarm: { level: 2, power: 2, target: "beam" },
      spike: { level: 1, power: 1 },
      cradle: { level: 1, power: 0 },
    },
    augments: [],
    unfitted: ["Defense Scrambler"],
  },
  {
    id: "fed-a",
    cruiser: "Federation Cruiser",
    layout: "A",
    name: "The Osprey",
    quote:
      "This ship features the latest in federation technology: an advanced beam weapon that pierces through shields!",
    unlock: "Defeat the Flagship, or defeat it with the Engi Cruiser.",
    source: "The Federation Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 5,
    parts: 2,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [2, 2],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["lineburst"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "blade", room: "p-engines" },
      { kin: "stone", room: "p-weapons" },
      { kin: "shell", room: "p-shields" },
    ],
    kits: { lance: { level: 1, power: 1 } },
    augments: [],
    unfitted: [],
  },
  {
    id: "fed-b",
    cruiser: "Federation Cruiser",
    layout: "B",
    name: "Nisos",
    quote: "This ship features additional Artillery power, encouraging heavy reliance on the beam.",
    unlock: "Earn two of the three Federation Cruiser achievements.",
    source: "The Federation Cruiser, Layout B",
    reactor: 9,
    fuel: 16,
    missiles: 9,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [2, 2],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["twin", "leto"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "gel", room: "p-engines" },
      { kin: "spark", room: "p-weapons" },
    ],
    kits: { lance: { level: 2, power: 1 } },
    augments: [],
    unfitted: [],
  },
  {
    id: "fed-c",
    cruiser: "Federation Cruiser",
    layout: "C",
    name: "The Fregatidae",
    quote:
      "With a Flak Artillery weapon and an improved Clone Bay, only the most suicidal of infantry chooses to fly on this ship.",
    unlock: "Reach sector 8 with Federation layout B, Advanced Edition on.",
    source: "The Federation Cruiser, Layout C",
    reactor: 7,
    fuel: 16,
    missiles: 5,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [1, 0],
      sensors: [1, 1],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "spark", room: "p-engines" },
      { kin: "spark", room: "p-shields" },
      { kin: "blade", room: "p-weapons" },
    ],
    kits: {
      cradle: { level: 2, power: 1 },
      sling: { level: 1, power: 1 },
      // Flak Artillery tick keys off `on`, and the module comment says reactor bars are not taken off the hull.
      // Power stays 0 so the 7-bar reactor can cover shields, engines, oxygen, clone bay, and teleporter.
      flak: { level: 1, power: 0, on: true },
    },
    augments: ["lung"],
    unfitted: [],
  },
  {
    id: "zoltan-a",
    cruiser: "Zoltan Cruiser",
    layout: "A",
    name: "The Adjudicator",
    quote: "The Zoltan's advanced shields technology give this ship an edge during each battle.",
    unlock: "See the Unarmed Zoltan Transport, or defeat the Flagship with the Federation Cruiser.",
    source: "The Zoltan Cruiser, Layout A",
    reactor: 5,
    fuel: 16,
    missiles: 12,
    parts: 2,
    systems: {
      shields: [2, 2],
      engines: [1, 1],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [3, 1],
      sensors: [1, 1],
      pilot: [1, 1],
      doors: [2, 2],
    },
    weapons: ["leto"],
    crew: [
      { kin: "spark", room: "p-pilot" },
      { kin: "spark", room: "p-engines" },
      { kin: "spark", room: "p-weapons" },
    ],
    kits: {},
    augments: [],
    unfitted: ["Halberd Beam", "Zoltan Shield"],
  },
  {
    id: "zoltan-b",
    cruiser: "Zoltan Cruiser",
    layout: "B",
    name: "Noether",
    quote: "This ship starts with a weakened Shield system and must rely on its Zoltan shield.",
    unlock: "Earn two of the three Zoltan Cruiser achievements.",
    source: "The Zoltan Cruiser, Layout B",
    reactor: 5,
    fuel: 16,
    missiles: 0,
    parts: 2,
    systems: {
      shields: [1, 1],
      engines: [2, 2],
      oxygen: [1, 0],
      medbay: [1, 0],
      weapons: [4, 2],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["needle", "needle"],
    crew: [
      { kin: "spark", room: "p-pilot" },
      { kin: "spark", room: "p-engines" },
      { kin: "spark", room: "p-shields" },
    ],
    kits: {},
    augments: [],
    unfitted: ["Pike Beam", "Zoltan Shield"],
  },
  {
    id: "zoltan-c",
    cruiser: "Zoltan Cruiser",
    layout: "C",
    name: "Cerenkov",
    quote: "The designer of this ship was not willing to spend the money for a decent reactor. Instead it relies on its Zoltan crew and Backup Battery.",
    unlock: "Reach sector 8 with Zoltan layout B, Advanced Edition on.",
    source: "The Zoltan Cruiser, Layout C",
    reactor: 2,
    fuel: 16,
    missiles: 2,
    parts: 15,
    systems: {
      shields: [2, 2],
      engines: [2, 0],
      oxygen: [1, 0],
      medbay: [0, 0],
      weapons: [2, 0],
      sensors: [1, 1],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "spark", room: "p-pilot" },
      { kin: "spark", room: "p-engines" },
      { kin: "spark", room: "p-shields" },
      { kin: "spark", room: "p-weapons" },
    ],
    kits: {
      cradle: { level: 1, power: 0 },
      swarm: { level: 3, power: 0, target: "beam" },
      cell: { level: 2, power: 0 },
    },
    augments: [],
    unfitted: ["Ion Charger", "Zoltan Shield"],
  },
  {
    id: "slug-a",
    cruiser: "Slug Cruiser",
    layout: "A",
    name: "Man of War",
    quote: "Designed for use inside nebula, this cruiser lacks sensors and relies instead on the guile and cunning of the Slugs.",
    unlock: "See the Slug Home Nebula Surrender event, or defeat the Flagship with the Mantis Cruiser.",
    source: "The Slug Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 15,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 1],
      weapons: [3, 1],
      sensors: [0, 0],
      pilot: [1, 1],
      doors: [2, 2],
    },
    weapons: ["twin"],
    crew: [
      { kin: "gel", room: "p-pilot" },
      { kin: "gel", room: "p-engines" },
    ],
    kits: {},
    augments: [],
    unfitted: ["Anti-Bio Beam", "Breach Bomb I", "Slug Repair Gel"],
  },
  {
    id: "slug-b",
    cruiser: "Slug Cruiser",
    layout: "B",
    name: "The Stormwalker",
    quote: "This boarding ship has no medical facilities and must manage its explosives carefully to keep the crew alive.",
    unlock: "Earn two of the three Slug Cruiser achievements.",
    source: "The Slug Cruiser, Layout B",
    reactor: 7,
    fuel: 16,
    missiles: 25,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 0],
      medbay: [0, 0],
      weapons: [2, 1],
      sensors: [0, 0],
      pilot: [1, 1],
      doors: [2, 2],
    },
    weapons: ["artemis"],
    crew: [
      { kin: "gel", room: "p-pilot" },
      { kin: "gel", room: "p-engines" },
      { kin: "gel", room: "p-weapons" },
    ],
    kits: { sling: { level: 1, power: 1 } },
    augments: [],
    unfitted: ["Healing Burst", "Slug Repair Gel"],
  },
  {
    id: "slug-c",
    cruiser: "Slug Cruiser",
    layout: "C",
    name: "Ariolimax",
    quote: "Slugs are often skilled in the arts of misdirection and manipulation. With Hacking and Mind Control systems, this ship capitalizes on that fact.",
    unlock: "Reach sector 8 with Slug layout B, Advanced Edition on.",
    source: "The Slug Cruiser, Layout C",
    reactor: 9,
    fuel: 16,
    missiles: 1,
    parts: 15,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [2, 0],
      sensors: [1, 1],
      pilot: [1, 1],
      doors: [2, 2],
    },
    weapons: [],
    crew: [
      { kin: "gel", room: "p-pilot" },
      { kin: "gel", room: "p-engines" },
      { kin: "gel", room: "p-weapons" },
    ],
    kits: {
      spike: { level: 1, power: 1 },
      leash: { level: 1, power: 1 },
      cradle: { level: 1, power: 0 },
    },
    augments: [],
    unfitted: ["Chain Burst Laser", "Slug Repair Gel"],
  },
  {
    id: "rock-a",
    cruiser: "Rock Cruiser",
    layout: "A",
    name: "Bulwark",
    quote: "Similar to its designers, this super dense behemoth uses brute force to overwhelm its foes.",
    unlock: "See the Rock war vessel encounter, or defeat the Flagship with the Slug Cruiser.",
    source: "The Rock Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 28,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 1],
      weapons: [3, 1],
      sensors: [1, 1],
      ...sub,
    },
    weapons: ["artemis"],
    crew: [
      { kin: "stone", room: "p-pilot" },
      { kin: "stone", room: "p-engines" },
      { kin: "stone", room: "p-weapons" },
    ],
    kits: {},
    augments: ["keel"],
    unfitted: ["Hull Missile"],
  },
  {
    id: "rock-b",
    cruiser: "Rock Cruiser",
    layout: "B",
    name: "Shivan",
    quote: "With no airlocks, this ship must rely entirely on its rock crew to put out fires.",
    unlock: "Earn two of the three Rock Cruiser achievements.",
    source: "The Rock Cruiser, Layout B",
    reactor: 8,
    fuel: 16,
    missiles: 18,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [2, 1],
      medbay: [1, 0],
      weapons: [3, 2],
      sensors: [1, 1],
      pilot: [1, 1],
      doors: [0, 0],
    },
    weapons: ["cask"],
    crew: [
      { kin: "stone", room: "p-pilot" },
      { kin: "stone", room: "p-engines" },
      { kin: "stone", room: "p-weapons" },
      { kin: "stone", room: "p-shields" },
    ],
    kits: {},
    augments: ["keel"],
    unfitted: ["Heavy Pierce Laser Mk. I"],
  },
  {
    id: "rock-c",
    cruiser: "Rock Cruiser",
    layout: "C",
    name: "Tektite",
    quote: "Contact has been made with the Crystalline race and this cruiser was offered to the Federation as part of diplomatic discussions between the sister species.",
    unlock: "Reach sector 8 with Rock layout B, Advanced Edition on.",
    source: "The Rock Cruiser, Layout C",
    reactor: 8,
    fuel: 16,
    missiles: 15,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [3, 0],
      sensors: [1, 1],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "stone", room: "p-pilot" },
      { kin: "stone", room: "p-engines" },
      { kin: "shard", room: "p-weapons" },
    ],
    kits: { cradle: { level: 1, power: 0 } },
    augments: ["keel"],
    unfitted: ["Swarm Missiles", "Heavy Crystal Mark I"],
  },
  {
    id: "stealth-a",
    cruiser: "Stealth Cruiser",
    layout: "A",
    name: "The Nesasio",
    quote: "Constructed for the Federation by the Engi, this ship is designed to use cloaking technology and speed to get behind enemy lines.",
    unlock: "See the Engi fleet discussion event, or defeat the Flagship with the Rock Cruiser.",
    source: "The Stealth Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 0,
    parts: 0,
    systems: {
      shields: [0, 0],
      engines: [4, 4],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [2, 1],
      sensors: [2, 2],
      ...sub,
    },
    weapons: ["twin"],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "plain", room: "p-engines" },
      { kin: "plain", room: "p-weapons" },
    ],
    kits: { veil: { level: 1, power: 1 } },
    augments: ["casing", "glass"],
    unfitted: ["Mini Beam"],
  },
  {
    id: "stealth-b",
    cruiser: "Stealth Cruiser",
    layout: "B",
    name: "DA-SR 12",
    quote: "Built like a glass cannon, this ship is hard to handle. If its cloaking can keep it safe long enough to charge its weapon, few cruisers can withstand its might.",
    unlock: "Earn two of the three Stealth Cruiser achievements.",
    source: "The Stealth Cruiser, Layout B",
    reactor: 7,
    fuel: 16,
    missiles: 0,
    parts: 0,
    systems: {
      shields: [0, 0],
      engines: [2, 2],
      oxygen: [1, 1],
      medbay: [1, 0],
      weapons: [4, 0],
      sensors: [2, 2],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "plain", room: "p-engines" },
      { kin: "spark", room: "p-weapons" },
    ],
    kits: { veil: { level: 2, power: 2 } },
    augments: ["glass"],
    unfitted: ["Glaive Beam"],
  },
  {
    id: "stealth-c",
    cruiser: "Stealth Cruiser",
    layout: "C",
    name: "Simo-H",
    quote: "This ship was part of an Engi experiment to make a power efficient version of the Zoltan shield. Unfortunately this required the removal of the Cloaking system.",
    unlock: "Reach sector 8 with Stealth layout B, Advanced Edition on.",
    source: "The Stealth Cruiser, Layout C",
    reactor: 7,
    fuel: 16,
    missiles: 0,
    parts: 16,
    systems: {
      shields: [0, 0],
      engines: [3, 3],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [2, 0],
      sensors: [0, 0],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "stone", room: "p-engines" },
      { kin: "gel", room: "p-weapons" },
    ],
    kits: {
      cradle: { level: 1, power: 0 },
      swarm: { level: 2, power: 0, target: null },
    },
    augments: ["glass"],
    unfitted: [],
  },
  {
    id: "lanius-a",
    cruiser: "Lanius Cruiser",
    layout: "A",
    name: "Kruos",
    quote: "The sharp knife-like structures make Lanius ships a sight to behold. This cruiser was adapted to support the other races of the Federation.",
    unlock: "Unlock 4 ships besides The Kestrel.",
    source: "The Lanius Cruiser, Layout A",
    reactor: 8,
    fuel: 16,
    missiles: 3,
    parts: 9,
    systems: {
      shields: [2, 2],
      engines: [1, 1],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [3, 3],
      sensors: [1, 1],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "plain", room: "p-pilot" },
      { kin: "voidlung", room: "p-engines" },
      { kin: "voidlung", room: "p-weapons" },
    ],
    kits: {
      spike: { level: 1, power: 1 },
      cradle: { level: 1, power: 0 },
    },
    augments: ["lung"],
    unfitted: [],
  },
  {
    id: "lanius-b",
    cruiser: "Lanius Cruiser",
    layout: "B",
    name: "The Shrike",
    quote: "The racial ability of the Lanius make them fearsome combatants in small quarters. Combine that with a Mind Control system and this ship is a force to be reckoned with.",
    unlock: "Earn two of the three Lanius Cruiser achievements.",
    source: "The Lanius Cruiser, Layout B",
    reactor: 8,
    fuel: 16,
    missiles: 0,
    parts: 0,
    systems: {
      shields: [2, 2],
      engines: [1, 1],
      oxygen: [1, 1],
      medbay: [0, 0],
      weapons: [1, 0],
      sensors: [0, 0],
      ...sub,
    },
    weapons: [],
    crew: [
      { kin: "shell", room: "p-pilot" },
      { kin: "voidlung", room: "p-engines" },
      { kin: "voidlung", room: "p-weapons" },
    ],
    kits: {
      sling: { level: 1, power: 1 },
      leash: { level: 1, power: 1 },
      cradle: { level: 1, power: 0 },
    },
    augments: ["lung"],
    unfitted: ["Advanced Flak"],
  },
];

export function hullById(id: string): HullSpec | undefined {
  return HULLS.find((h) => h.id === id);
}
