/**
 * Non-player pages from ftl.fandom.com (action=parse, prop=wikitext).
 * One ship per heading that names a hull class. Figures are copied from that
 * heading. Shield numbers are system levels as printed, not bubble layers.
 * A "Weapons" or "Drones" heading is a shared pool ("can have any of"), not a
 * starting loadout, so those names are not attached to a hull.
 * Enemy Ships returned wikitext. Its headings are topics and transclusions,
 * not hull classes, so that page has no ships.
 */

export type FactionPage = {
  title: string;
  status: "fetched" | "blocked";
  ships: { id: string; name: string; notes: string[] }[];
};

export const FACTION_PAGES: FactionPage[] = [
  {
    title: "Engi Ships",
    status: "fetched",
    ships: [
      {
        id: "engi-scout",
        name: "Engi Scout",
        notes: [
          "Hull 8-13 (7-12 on Easy)",
          "Crew 2-4 Engi",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Drone Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Augment Engi Med-bot Dispersal",
          "Sectors 2-7",
          "Blueprint CIRCLE_SCOUT",
        ],
      },
      {
        id: "engi-outrider",
        name: "Engi Outrider",
        notes: [
          "Hull 8-13 (7-12 on Easy)",
          "Crew 2-4 Engi",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-6",
          "Drone Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Hacking 1-2",
          "Augment Engi Med-bot Dispersal (no effect for Clone Bay)",
          "Sectors 2-7",
          "Blueprint CIRCLE_SCOUT_DLC",
        ],
      },
      {
        id: "engi-bomber",
        name: "Engi Bomber",
        notes: [
          "Hull 10-15 (9-14 on Easy)",
          "Crew 3-5 Engi",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-10",
          "Drone Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Augment Engi Med-bot Dispersal",
          "Sectors 2-7",
          "Blueprint CIRCLE_BOMBER",
        ],
      },
      {
        id: "engi-hacker",
        name: "Engi Hacker",
        notes: [
          "Hull 10-15 (9-14 on Easy)",
          "Crew 3-5 Engi",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Hacking 1-3",
          "Weapon Control 2-8",
          "Drone Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Door System 1-3",
          "Augment Engi Med-bot Dispersal (no effect for Clone Bay)",
          "Sectors 2-7",
          "Blueprint CIRCLE_BOMBER_DLC",
        ],
      },
    ],
  },
  {
    title: "Zoltan Ships",
    status: "fetched",
    ships: [
      {
        id: "energy-fighter",
        name: "Energy Fighter / Pirate Fighter",
        notes: [
          "Hull 7-14 (6-13 on Easy)",
          "Crew 2 Zoltan (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Augment Zoltan Shield",
          "Zoltan Shield absorbs 5 points of damage and prevents boarding, hacking, and mind control (page lead; except sector 1 on easy mode)",
          "Ion and beam weapons do double damage against the Zoltan Shield, as does the Beam Drone 2",
          "Sectors 1-8",
          "Blueprints ZOLTAN_FIGHTER, ZOLTAN_FIGHTER_P",
        ],
      },
      {
        id: "energy-instigator",
        name: "Energy Instigator / Pirate Instigator",
        notes: [
          "Hull 7-14 (6-13 on Easy)",
          "Crew 2 Zoltan (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Mind Control 1",
          "Augment Zoltan Shield",
          "Zoltan Shield absorbs 5 points of damage and prevents boarding, hacking, and mind control (page lead; except sector 1 on easy mode)",
          "Ion and beam weapons do double damage against the Zoltan Shield, as does the Beam Drone 2",
          "Sectors 1-8",
          "Blueprints ZOLTAN_FIGHTER_DLC, ZOLTAN_FIGHTER_P_DLC",
        ],
      },
      {
        id: "energy-bomber",
        name: "Energy Bomber / Pirate Bomber",
        notes: [
          "Hull 10-14 (9-13 on Easy)",
          "Crew 4-5 Zoltan (Pirate crew is 4-5 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Drone Control 2-4",
          "Optional Door System 1-3",
          "Augment Zoltan Shield",
          "Zoltan Shield absorbs 5 points of damage and prevents boarding, hacking, and mind control (page lead; except sector 1 on easy mode)",
          "Ion and beam weapons do double damage against the Zoltan Shield, as does the Beam Drone 2",
          "Sectors 4-8",
          "Blueprints ZOLTAN_BOMBER, ZOLTAN_BOMBER_P",
        ],
      },
      {
        id: "energy-hacker",
        name: "Energy Hacker / Pirate Hacker",
        notes: [
          "Hull 10-14 (9-13 on Easy)",
          "Crew 4-5 Zoltan (Pirate crew is 4-5 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Hacking 1-2",
          "Optional Door System 1-3",
          "Augment Zoltan Shield",
          "Zoltan Shield absorbs 5 points of damage and prevents boarding, hacking, and mind control (page lead; except sector 1 on easy mode)",
          "Ion and beam weapons do double damage against the Zoltan Shield, as does the Beam Drone 2",
          "Sectors 4-8",
          "Blueprints ZOLTAN_BOMBER_DLC, ZOLTAN_BOMBER_P_DLC",
        ],
      },
    ],
  },
  {
    title: "Mantis Ships",
    status: "fetched",
    ships: [
      {
        id: "mantis-scout",
        name: "Mantis Scout / Pirate Scout",
        notes: [
          "Hull 7-12 (6-11 on Easy)",
          "Crew 3-4 total, 3-4 Mantis, 0-1 Engi (Pirate crew is 3-4 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-7",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Crew Teleporter 1-3",
          "Optional Door System 1-3 [Mantis Scout only]",
          "Sectors 1-6",
          "Blueprints MANTIS_SCOUT, MANTIS_SCOUT_P",
        ],
      },
      {
        id: "mantis-interceptor",
        name: "Mantis Interceptor / Pirate Interceptor",
        notes: [
          "Hull 7-12 (6-11 on Easy)",
          "Crew 2-3 total, 2-3 Mantis, 0-1 Engi (Pirate crew is 2-3 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-7",
          "Piloting 1-3",
          "Optional Clone Bay 1-2",
          "Optional Crew Teleporter 1-2",
          "Optional Door System 1-2 [Mantis Interceptor only]",
          "Sectors 1-6",
          "Blueprints MANTIS_SCOUT_DLC, MANTIS_SCOUT_P_DLC",
        ],
      },
      {
        id: "mantis-fighter",
        name: "Mantis Fighter / Pirate Fighter",
        notes: [
          "Hull 10-16 (9-15 on Easy)",
          "Crew 3-4 total, 3-4 Mantis, 0-1 Engi (Pirate crew is 3-4 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Medbay 1-3",
          "Oxygen 1-3",
          "Crew Teleporter 1-3",
          "Weapon Control 1-8",
          "Piloting 1-3",
          "Optional Door System 1-3",
          "Sectors 2-8 (in sector 8 the non-pirate version can only be encountered in the Battlefield Wreckage event)",
          "Blueprints MANTIS_FIGHTER, MANTIS_FIGHTER_P",
        ],
      },
      {
        id: "mantis-assault",
        name: "Mantis Assault / Pirate Assault",
        notes: [
          "Hull 10-16 (9-15 on Easy)",
          "Crew 2-4 total, 2-4 Mantis, 0-1 Engi (Pirate crew is 2-4 random)",
          "Shields 2-7",
          "Engines 1-5",
          "Clone Bay 1-3",
          "Oxygen 1-3",
          "Crew Teleporter 1-2",
          "Weapon Control 1-7",
          "Piloting 1-3",
          "Optional Door System 1-3",
          "Sectors 2-8 (in sector 8 the non-pirate version can only be encountered in the Battlefield Wreckage event)",
          "Blueprints MANTIS_FIGHTER_DLC, MANTIS_FIGHTER_P_DLC",
        ],
      },
      {
        id: "mantis-bomber",
        name: "Mantis Bomber / Pirate Bomber",
        notes: [
          "Hull 12-18 (11-17 on Easy) / 15-18 (14-17 on Easy) for pirated",
          "Crew 4-5 total, 4-5 Mantis, 0-1 Engi (Pirate crew is 4-5 random)",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Crew Teleporter 1-3",
          "Weapon Control 2-10",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Sectors 2-8 (normally appears in sectors 5+; in sectors 2-4 can only be encountered in the Mantis Ship-Collectors event; in sector 8 the non-pirate version can only be encountered in the Battlefield Wreckage event) / 5-8 (pirated version)",
          "Blueprints MANTIS_BOMBER, MANTIS_BOMBER_P",
        ],
      },
      {
        id: "mantis-aggressor",
        name: "Mantis Aggressor / Pirate Aggressor",
        notes: [
          "Hull 15-18 (14-17 on Easy)",
          "Crew 4-5 total, 4-5 Mantis, 0-1 Engi (Pirate crew is 4-5 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Crew Teleporter 1-2",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1",
          "Optional Door System 1-3",
          "Sectors 5-8 (in sector 8 the non-pirate version can only be encountered in the Battlefield Wreckage event)",
          "Blueprints MANTIS_BOMBER_DLC, MANTIS_BOMBER_P_DLC",
        ],
      },
    ],
  },
  {
    title: "Slug Ships",
    status: "fetched",
    ships: [
      {
        id: "slug-interceptor",
        name: "Slug Interceptor / Pirate Interceptor",
        notes: [
          "Hull 9-13 (8-12 on Easy)",
          "Crew 2 Slug (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-8",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Door System 1-3 [Pirate Interceptor only]",
          "Augment Slug Repair Gel",
          "Sectors 1-5",
          "Blueprints JELLY_BUTTON, JELLY_BUTTON_P",
        ],
      },
      {
        id: "slug-scout",
        name: "Slug Scout / Pirate Scout",
        notes: [
          "Hull 9-14 (8-13 on Easy)",
          "Crew 2 Slug (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-8",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Mind Control 1-2 [Pirate Scout only]",
          "Augment Slug Repair Gel",
          "Sectors 1-6",
          "Blueprints JELLY_BUTTON_DLC, JELLY_BUTTON_P_DLC",
        ],
      },
      {
        id: "slug-light-cruiser",
        name: "Slug Light-Cruiser / Pirate Light-Cruiser",
        notes: [
          "Hull 11-16 (10-15 on Easy) / 11-17 (10-16 on Easy) for pirated",
          "Crew 3-5 Slug (Pirate crew is 3-6 random)",
          "Shields 2-10",
          "Engines 1-6",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Cloaking 1-2 [Pirate Light-Cruiser only]",
          "Optional Door System 1-3",
          "Augment Slug Repair Gel",
          "Sectors 2-7 / 2-8 (pirated version)",
          "Blueprints JELLY_CROISSANT, JELLY_CROISSANT_P",
        ],
      },
      {
        id: "slug-light-surveyor",
        name: "Slug Light-Surveyor / Pirate Light-Surveyor",
        notes: [
          "Hull 11-16 (10-15 on Easy) / 11-17 (10-16 on Easy) for pirated",
          "Crew 3-6 Slug (Pirate crew is 3-6 random)",
          "Shields 2-10",
          "Engines 1-6",
          "Oxygen 1-3",
          "Weapon Control 2-7",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Mind Control 1-2",
          "Augment Slug Repair Gel",
          "Sectors 2-7 / 2-8 (pirated version)",
          "Blueprints JELLY_CROISSANT_DLC, JELLY_CROISSANT_P_DLC",
        ],
      },
      {
        id: "slug-assault",
        name: "Slug Assault / Pirate Assault",
        notes: [
          "Hull 15-17 (14-16 on Easy) / 15-18 (14-17 on Easy) for pirated",
          "Crew 5-6 Slug (Pirate crew is 5-6 random)",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-10",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Cloaking 1",
          "Optional Door System 1-3",
          "Augment Slug Repair Gel",
          "Sectors 5-7 / 5-8 (pirated version)",
          "Blueprints JELLY_TRUFFLE, JELLY_TRUFFLE_P",
        ],
      },
      {
        id: "slug-instigator",
        name: "Slug Instigator / Pirate Instigator",
        notes: [
          "Hull 15-17 (14-16 on Easy) / 15-18 (14-17 on Easy) for pirated",
          "Crew 6-7 Slug (Pirate crew is 6-7 random)",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-9",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Cloaking 1 [Slug Instigator only]",
          "Optional Mind Control 1-2",
          "Optional Door System 1-2 [Pirate Instigator only]",
          "Augment Slug Repair Gel",
          "Sectors 5-7 / 5-8 (pirated version)",
          "Blueprints JELLY_TRUFFLE_DLC, JELLY_TRUFFLE_P_DLC",
        ],
      },
    ],
  },
  {
    title: "Rock Ships",
    status: "fetched",
    ships: [
      {
        id: "rock-scout",
        name: "Rock Scout / Pirate Scout",
        notes: [
          "Hull 8-13 (7-12 on Easy)",
          "Crew 2-3 Rock (Pirate crew is 2-3 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3 [Rock Scout only]",
          "Optional Crew Teleporter 1-2 [Pirate Scout only]",
          "Optional Door System 1-3 [Rock Scout only]",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 1-6",
          "Blueprints ROCK_SCOUT, ROCK_SCOUT_P",
        ],
      },
      {
        id: "rock-investigator",
        name: "Rock Investigator / Pirate Investigator",
        notes: [
          "Hull 8-13 (7-12 on Easy)",
          "Crew 2-3 Rock (Pirate crew is 2-3 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Crew Teleporter 1-2 [Rock Investigator only]",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 1-6",
          "Blueprints ROCK_SCOUT_DLC, ROCK_SCOUT_P_DLC",
        ],
      },
      {
        id: "rock-fighter",
        name: "Rock Fighter / Pirate Fighter",
        notes: [
          "Hull 12-16 (11-15 on Easy) / 12-17 (11-16 on Easy) for pirated",
          "Crew 3-4 Rock (Pirate crew is 3-4 random)",
          "Shields 2-8",
          "Engines 2-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Cloaking 1-3 [Pirate Fighter only]",
          "Optional Door System 1-3",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 3-7 / 3-8 (pirated version)",
          "Blueprints ROCK_FIGHT, ROCK_FIGHT_P",
        ],
      },
      {
        id: "rock-interceptor",
        name: "Rock Interceptor / Pirate Interceptor",
        notes: [
          "Hull 12-16 (11-15 on Easy) / 12-17 (11-16 on Easy) for pirated",
          "Crew 2-4 Rock (Pirate crew is 2-4 random)",
          "Shields 2-8",
          "Engines 2-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Crew Teleporter 1-2",
          "Optional Cloaking 1",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 3-7 / 3-8 (pirated version)",
          "Blueprints ROCK_FIGHT_DLC, ROCK_FIGHT_P_DLC",
        ],
      },
      {
        id: "rock-assault",
        name: "Rock Assault",
        notes: [
          "Hull 17-18 (16-17 on Easy)",
          "Crew 4-5 Rock",
          "Shields 2-8",
          "Engines 2-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-2",
          "Optional Crew Teleporter 1-2",
          "Optional Cloaking 1",
          "Optional Door System 1-3",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 6-7",
          "Blueprint ROCK_ASSAULT",
        ],
      },
      {
        id: "rock-aggressor",
        name: "Rock Aggressor",
        notes: [
          "Hull 17-18 (16-17 on Easy)",
          "Crew 4-5 Rock",
          "Shields 2-8",
          "Engines 2-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-2",
          "Optional Crew Teleporter 1-2",
          "Optional Cloaking 1-2",
          "Optional Door System 1-3",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 6-7",
          "Blueprint ROCK_ASSAULT_DLC",
        ],
      },
      {
        id: "rock-assault-elite",
        name: "Rock Assault (Elite)",
        notes: [
          "Ship unique to the Rock war vessel encounter event",
          "Hull 16-18 (15-17 on Easy)",
          "Crew 4-5 Rock",
          "Shields 2-8",
          "Engines 2-5",
          "Oxygen 1-3",
          "Cloaking 1-3",
          "Weapon Control 2-10",
          "Piloting 1-3",
          "Optional Medbay 1-2",
          "Optional Crew Teleporter 1-2",
          "Optional Door System 1-3",
          "Augment Rock Plating",
          "25% of their possible weapons are missiles (page lead)",
          "Rock crew have a hidden 67% bonus to fire-fighting (page lead)",
          "Sectors 5-7 (can only be encountered in the Rock Cruiser unlock event sequence)",
          "Blueprint ROCK_ASSAULT_ELITE",
        ],
      },
    ],
  },
  {
    title: "Crystal Ships",
    status: "fetched",
    ships: [
      {
        id: "crystal-scout",
        name: "Crystal Scout",
        notes: [
          "Hull 11-13 (10-12 on Easy)",
          "Crew 2 Crystal",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 4-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only)",
          "Only use crystal weapons and Crystal Lockdown Bomb",
          "Page note: Weapon Control and Shields system levels are incorrect",
          "Blueprint CRYSTAL_SCOUT",
        ],
      },
      {
        id: "crystal-outrider",
        name: "Crystal Outrider",
        notes: [
          "Hull 11-13 (10-12 on Easy)",
          "Crew 2 Crystal",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 4-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only)",
          "Only use crystal weapons and Crystal Lockdown Bomb",
          "Page note: Weapon Control and Shields system levels are incorrect",
          "Blueprint CRYSTAL_SCOUT_DLC",
        ],
      },
      {
        id: "crystal-bomber",
        name: "Crystal Bomber",
        notes: [
          "Hull 13-15 (12-14 on Easy)",
          "Crew 3-4 Crystal",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-10",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only)",
          "Only use crystal weapons and Crystal Lockdown Bomb",
          "Page note: Weapon Control and Shields system levels are incorrect",
          "Blueprint CRYSTAL_BOMBER",
        ],
      },
      {
        id: "crystal-instigator",
        name: "Crystal Instigator",
        notes: [
          "Hull 13-15 (12-14 on Easy)",
          "Crew 3-4 Crystal",
          "Shields 2-10",
          "Engines 1-5",
          "Oxygen 1-3",
          "Crew Teleporter 1-2",
          "Cloaking 1-2",
          "Weapon Control 2-10",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Door System 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only)",
          "Only use crystal weapons and Crystal Lockdown Bomb",
          "Page note: Weapon Control and Shields system levels are incorrect",
          "Blueprint CRYSTAL_BOMBER_DLC",
        ],
      },
    ],
  },
  {
    title: "Lanius Ships",
    status: "fetched",
    ships: [
      {
        id: "lanius-scout",
        name: "Lanius Scout",
        notes: [
          "Hull 8-13 (7-12 on Easy)",
          "Crew 2 Lanius",
          "Shields 2-8",
          "Engines 1-5",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "No Oxygen (page: Lanius ships have no Oxygen)",
          "Optional Clone Bay 1-3",
          "Optional Hacking 1-3",
          "Optional Door System 1-3",
          "Augment Emergency Respirators",
          "Sectors 2-7",
          "Blueprint ANAEROBIC_SCOUT",
        ],
      },
      {
        id: "lanius-bomber",
        name: "Lanius Bomber",
        notes: [
          "Hull 12-15 (11-14 on Easy)",
          "Crew 3-4 Lanius",
          "Shields 2-8",
          "Engines 1-5",
          "Crew Teleporter 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "No Oxygen (page: Lanius ships have no Oxygen)",
          "Optional Clone Bay 1-3",
          "Optional Cloaking 1-3",
          "Optional Mind Control 1-2",
          "Optional Door System 1-3",
          "Augment Emergency Respirators",
          "Sectors 4-7",
          "Blueprint ANAEROBIC_BOMBER",
        ],
      },
    ],
  },
  {
    title: "Federation Ships",
    status: "fetched",
    ships: [
      {
        id: "federation-scout",
        name: "Federation Scout / Pirate Scout",
        notes: [
          "Hull 11-13 (10-12 on Easy) / 7-13 (6-12 on Easy) for pirated",
          "Crew 2 Human (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Door System 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only) / 1-7 (pirated version)",
          "Blueprints FED_SCOUT / FED_SCOUT_P",
        ],
      },
      {
        id: "federation-outrider",
        name: "Federation Outrider / Pirate Outrider",
        notes: [
          "Hull 11-13 (10-12 on Easy) / 7-13 (6-12 on Easy) for pirated",
          "Crew 2 Human (Pirate crew is 2 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Hacking 1",
          "Sectors 5-7 (in Crystal Homeworlds only) / 1-7 (pirated version)",
          "Blueprints FED_SCOUT_DLC / FED_SCOUT_P_DLC",
        ],
      },
      {
        id: "federation-bomber",
        name: "Federation Bomber / Pirate Bomber",
        notes: [
          "Hull 13-15 (12-14 on Easy) / 10-16 (9-15 on Easy) for pirated",
          "Crew 2-5 Human (Pirate crew is 2-5 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Medbay 1-3",
          "Optional Door System 1-3",
          "Sectors 5-7 (in Crystal Homeworlds only) / 2-8 (pirated version)",
          "Blueprints FED_BOMBER / FED_BOMBER_P",
        ],
      },
      {
        id: "federation-hacker",
        name: "Federation Hacker / Pirate Hacker",
        notes: [
          "Hull 13-15 (12-14 on Easy) / 10-16 (9-15 on Easy) for pirated",
          "Crew 2-5 Human (Pirate crew is 2-5 random)",
          "Shields 2-8",
          "Engines 1-5",
          "Oxygen 1-3",
          "Weapon Control 2-8",
          "Piloting 1-3",
          "Optional Clone Bay 1-3",
          "Optional Hacking 1",
          "Sectors 5-7 (in Crystal Homeworlds only) / 2-8 (pirated version)",
          "Blueprints FED_BOMBER_DLC / FED_BOMBER_P_DLC",
        ],
      },
    ],
  },
  {
    title: "Enemy Ships",
    status: "fetched",
    ships: [],
  },
];
