/**
 * Traced interiors for the 45 enemy classes whose faction pages show a room screenshot.
 * Engi Hacker and Crystal Outrider have no interior picture and are not in this table.
 * The bitmaps are not copied. A pirate screenshot is the same hull, not a second shape.
 * Rebel Fighter, Rebel Invader, and Elite Fighter share one hull; the icons differ.
 * system is the icon visible in that screenshot. Null is an empty hall.
 * Seating an unlabeled system into a hall is INFERRED in enemy-gen.ts.
 * Door marks are orange bars on a cell edge. A shared edge with no bar stays a wall.
 */
import type { DoorMark } from "../types.ts";
import type { EnemySystem } from "./enemy-ships.ts";

export type EnemyTraceRoom = {
  x: number;
  y: number;
  w: number;
  h: number;
  system: EnemySystem | null;
  omit?: { x: number; y: number }[];
};

export type EnemyLayout = {
  cols: number;
  rows: number;
  rooms: EnemyTraceRoom[];
  marks: DoorMark[];
};

export const ENEMY_LAYOUTS: Record<string, EnemyLayout> = {
  "rebel-fighter": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "shields" },
      { x: 2, y: 2, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 5, w: 2, h: 2, system: "doors" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "pilot" },
    ],
    marks: [
      { x: 0, y: 6, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 2, y: 0, side: "n" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 6, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "n" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 4, side: "s" },
      { x: 3, y: 4, side: "w" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 5, side: "n" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 6, side: "s" },
    ],
  },
  "rebel-invader": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "shields" },
      { x: 2, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 5, w: 2, h: 2, system: "pilot" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "doors" },
    ],
    marks: [
      { x: 0, y: 6, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 2, y: 0, side: "n" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 6, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "n" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 4, side: "s" },
      { x: 3, y: 4, side: "w" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 5, side: "n" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 6, side: "s" },
    ],
  },
  "rebel-rigger": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 1, system: null },
      { x: 0, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 2, h: 2, system: null },
      { x: 4, y: 2, w: 2, h: 1, system: null },
      { x: 4, y: 3, w: 1, h: 1, system: null },
      { x: 2, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 2, side: "e" },
      { x: 0, y: 2, side: "n" },
      { x: 0, y: 2, side: "w" },
      { x: 0, y: 3, side: "s" },
      { x: 0, y: 3, side: "w" },
      { x: 1, y: 0, side: "e" },
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 1, side: "w" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 4, side: "w" },
      { x: 3, y: 1, side: "n" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 1, side: "w" },
      { x: 3, y: 3, side: "e" },
      { x: 4, y: 1, side: "e" },
      { x: 4, y: 1, side: "n" },
      { x: 4, y: 1, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 2, side: "n" },
    ],
  },
  "rebel-disruptor": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 1, system: null },
      { x: 0, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 2, h: 2, system: null },
      { x: 4, y: 2, w: 2, h: 1, system: null },
      { x: 4, y: 3, w: 1, h: 1, system: null },
      { x: 3, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 2, side: "e" },
      { x: 0, y: 2, side: "n" },
      { x: 0, y: 2, side: "w" },
      { x: 0, y: 3, side: "s" },
      { x: 0, y: 3, side: "w" },
      { x: 1, y: 0, side: "e" },
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 1, side: "w" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 3, y: 1, side: "n" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 1, side: "w" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 4, side: "e" },
      { x: 4, y: 1, side: "e" },
      { x: 4, y: 1, side: "n" },
      { x: 4, y: 1, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 2, side: "n" },
    ],
  },
  "elite-fighter": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "shields" },
      { x: 2, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 5, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 1, h: 2, system: null },
      { x: 3, y: 5, w: 2, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 6, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 2, y: 0, side: "n" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 6, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "n" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 4, side: "s" },
      { x: 3, y: 4, side: "w" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 5, side: "n" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 6, side: "s" },
    ],
  },
  "elite-assault": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 5, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 1, h: 2, system: null },
      { x: 3, y: 5, w: 2, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 6, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 6, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "n" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 4, side: "s" },
      { x: 3, y: 4, side: "w" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 5, side: "n" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 6, side: "s" },
    ],
  },
  "auto-scout": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: null },
      { x: 5, y: 0, w: 2, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 1, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 5, y: 0, side: "s" },
    ],
  },
  "auto-surveyor": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: null },
      { x: 5, y: 0, w: 2, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 1, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 5, y: 0, side: "s" },
    ],
  },
  "auto-assault": {
    cols: 5,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 0, w: 1, h: 2, system: null },
      { x: 3, y: 0, w: 1, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
    ],
  },
  "auto-hacker": {
    cols: 5,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 0, w: 1, h: 2, system: null },
      { x: 3, y: 0, w: 1, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
    ],
  },
  "engi-scout": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 3, y: 0, w: 2, h: 1, system: null },
      { x: 4, y: 1, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 1, h: 1, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 4, y: 3, w: 2, h: 2, system: null },
      { x: 3, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 3, y: 4, side: "e" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  "engi-outrider": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 0, w: 2, h: 2, omit: [{ x: 1, y: 0 }], system: null },
      { x: 3, y: 0, w: 2, h: 1, system: null },
      { x: 0, y: 2, w: 2, h: 1, system: null },
      { x: 4, y: 2, w: 1, h: 1, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 4, y: 3, w: 2, h: 2, omit: [{ x: 5, y: 3 }], system: null },
      { x: 3, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 3, y: 4, side: "e" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  "engi-bomber": {
    cols: 6,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 3, y: 0, w: 1, h: 1, system: null },
      { x: 2, y: 1, w: 2, h: 1, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: null },
      { x: 0, y: 2, w: 2, h: 2, omit: [{ x: 1, y: 2 }], system: null },
      { x: 4, y: 2, w: 1, h: 2, system: null },
      { x: 5, y: 2, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 1, system: null },
      { x: 4, y: 4, w: 2, h: 1, system: null },
      { x: 0, y: 5, w: 2, h: 2, omit: [{ x: 0, y: 5 }], system: null },
      { x: 4, y: 5, w: 2, h: 2, system: null },
      { x: 2, y: 6, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 3, side: "s" },
      { x: 1, y: 0, side: "e" },
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 6, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 6, side: "e" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 4, side: "s" },
      { x: 5, y: 1, side: "s" },
      { x: 5, y: 3, side: "s" },
    ],
  },
  "mantis-scout": {
    cols: 8,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 1, w: 1, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 5, y: 1, w: 2, h: 1, system: null },
      { x: 7, y: 1, w: 1, h: 1, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 5, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 5, y: 1, side: "s" },
      { x: 6, y: 1, side: "e" },
    ],
  },
  "mantis-interceptor": {
    cols: 8,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 7, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 1, w: 2, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 6, y: 1, w: 1, h: 1, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 5, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 5, y: 2, side: "n" },
      { x: 6, y: 1, side: "e" },
    ],
  },
  "mantis-fighter": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 1, system: null },
      { x: 7, y: 1, w: 1, h: 1, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 5, y: 2, w: 2, h: 1, system: null },
      { x: 1, y: 3, w: 1, h: 1, system: null },
      { x: 2, y: 3, w: 1, h: 1, system: null },
      { x: 5, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 6, y: 2, side: "e" },
    ],
  },
  "mantis-assault": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 1, system: null },
      { x: 7, y: 1, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 5, y: 2, w: 1, h: 1, system: null },
      { x: 6, y: 2, w: 1, h: 1, system: null },
      { x: 1, y: 3, w: 2, h: 1, system: null },
      { x: 5, y: 3, w: 2, h: 1, system: null },
      { x: 4, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 6, y: 2, side: "e" },
    ],
  },
  "mantis-bomber": {
    cols: 8,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 2, h: 2, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 4, y: 4, w: 1, h: 1, system: null },
      { x: 3, y: 5, w: 2, h: 1, system: null },
      { x: 0, y: 6, w: 1, h: 2, system: null },
      { x: 3, y: 6, w: 2, h: 2, system: null },
      { x: 7, y: 6, w: 1, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 5, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 7, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 0, side: "n" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 5, side: "s" },
      { x: 3, y: 7, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 4, side: "e" },
      { x: 4, y: 4, side: "s" },
      { x: 4, y: 5, side: "e" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 7, side: "e" },
      { x: 4, y: 7, side: "s" },
      { x: 5, y: 4, side: "s" },
      { x: 6, y: 7, side: "e" },
      { x: 6, y: 7, side: "n" },
    ],
  },
  "mantis-aggressor": {
    cols: 8,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 2, h: 2, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 4, y: 4, w: 1, h: 1, system: null },
      { x: 3, y: 5, w: 2, h: 1, system: null },
      { x: 0, y: 6, w: 1, h: 2, system: null },
      { x: 3, y: 6, w: 2, h: 2, system: null },
      { x: 7, y: 6, w: 1, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 5, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 7, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 0, side: "n" },
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 5, side: "s" },
      { x: 3, y: 7, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 4, side: "e" },
      { x: 4, y: 4, side: "s" },
      { x: 4, y: 5, side: "e" },
      { x: 4, y: 6, side: "e" },
      { x: 4, y: 7, side: "e" },
      { x: 4, y: 7, side: "s" },
      { x: 5, y: 4, side: "s" },
      { x: 6, y: 7, side: "e" },
      { x: 6, y: 7, side: "n" },
    ],
  },
  "slug-interceptor": {
    cols: 4,
    rows: 4,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "shields" },
      { x: 1, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 2, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 2, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 0, side: "s" },
    ],
  },
  "slug-scout": {
    cols: 4,
    rows: 4,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: null },
      { x: 1, y: 1, w: 1, h: 2, system: null },
      { x: 2, y: 1, w: 1, h: 2, system: null },
      { x: 0, y: 2, w: 1, h: 2, system: null },
      { x: 3, y: 2, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 0, side: "s" },
    ],
  },
  "slug-light-cruiser": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 5, y: 1, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 1, h: 1, system: null },
      { x: 4, y: 3, w: 1, h: 1, system: null },
      { x: 6, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 1, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
    ],
  },
  "slug-light-surveyor": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 5, y: 1, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 6, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 1, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
    ],
  },
  "slug-assault": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 5, y: 2, w: 2, h: 1, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 6, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 0, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
    ],
  },
  "slug-instigator": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 5, y: 2, w: 2, h: 1, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 6, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 0, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
    ],
  },
  "rock-scout": {
    cols: 3,
    rows: 7,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 0, w: 2, h: 2, omit: [{ x: 2, y: 0 }], system: null },
      { x: 0, y: 2, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 1, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 6, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 0, y: 4, side: "e" },
      { x: 0, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 4, side: "s" },
    ],
  },
  "rock-investigator": {
    cols: 3,
    rows: 7,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 0, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 1, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 0, y: 4, side: "e" },
      { x: 0, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 4, side: "s" },
    ],
  },
  "rock-fighter": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 2, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, omit: [{ x: 1, y: 4 }], system: null },
      { x: 2, y: 5, w: 2, h: 2, system: null },
      { x: 0, y: 6, w: 1, h: 1, system: null },
      { x: 1, y: 6, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "n" },
      { x: 1, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 4, side: "w" },
      { x: 3, y: 2, side: "s" },
    ],
  },
  "rock-interceptor": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 0, y: 3, w: 2, h: 1, system: null },
      { x: 2, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 2, h: 2, omit: [{ x: 3, y: 5 }], system: null },
      { x: 0, y: 6, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "n" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
    ],
  },
  "rock-assault": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 1, system: null },
      { x: 0, y: 1, w: 2, h: 1, system: null },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 1, system: null },
      { x: 5, y: 1, w: 1, h: 1, system: null },
      { x: 2, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, omit: [{ x: 0, y: 4 }], system: null },
      { x: 4, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 2, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 3, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 1, side: "n" },
      { x: 2, y: 4, side: "s" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 7, side: "n" },
    ],
  },
  "rock-aggressor": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 1, system: null },
      { x: 0, y: 1, w: 2, h: 1, system: null },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 1, system: null },
      { x: 5, y: 1, w: 1, h: 1, system: null },
      { x: 2, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, omit: [{ x: 1, y: 4 }], system: null },
      { x: 4, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 2, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 3, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 1, side: "n" },
      { x: 2, y: 4, side: "s" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 7, side: "n" },
    ],
  },
  "rock-assault-elite": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: null },
      { x: 0, y: 1, w: 2, h: 1, system: null },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: null },
      { x: 2, y: 3, w: 2, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, system: null },
      { x: 4, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 2, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 3, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 0, side: "s" },
      { x: 2, y: 4, side: "s" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 3, y: 6, side: "s" },
      { x: 4, y: 7, side: "n" },
    ],
  },
  "energy-fighter": {
    cols: 5,
    rows: 6,
    rooms: [
      { x: 2, y: 0, w: 1, h: 1, system: null },
      { x: 2, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 2, h: 2, system: null },
      { x: 4, y: 4, w: 1, h: 1, system: null },
      { x: 0, y: 5, w: 2, h: 1, system: null },
      { x: 2, y: 5, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 0, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 4, side: "e" },
      { x: 2, y: 4, side: "s" },
      { x: 4, y: 3, side: "s" },
    ],
  },
  "energy-instigator": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 2, system: null },
      { x: 4, y: 3, w: 1, h: 2, system: null },
      { x: 1, y: 4, w: 2, h: 2, system: null },
      { x: 3, y: 5, w: 1, h: 1, system: null },
      { x: 0, y: 6, w: 2, h: 1, system: null },
      { x: 2, y: 6, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 5, side: "s" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 2, y: 5, side: "s" },
      { x: 4, y: 4, side: "s" },
    ],
  },
  "energy-bomber": {
    cols: 4,
    rows: 9,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 3, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 2, h: 2, system: null },
      { x: 1, y: 5, w: 1, h: 2, system: null },
      { x: 3, y: 5, w: 1, h: 1, system: null },
      { x: 3, y: 6, w: 1, h: 2, system: null },
      { x: 0, y: 7, w: 2, h: 2, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 3, side: "n" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 6, side: "s" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 5, side: "s" },
    ],
  },
  "energy-hacker": {
    cols: 4,
    rows: 9,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 3, y: 2, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 2, h: 2, system: null },
      { x: 3, y: 4, w: 1, h: 1, system: null },
      { x: 1, y: 5, w: 1, h: 2, system: null },
      { x: 3, y: 6, w: 1, h: 2, system: null },
      { x: 0, y: 7, w: 2, h: 2, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 3, side: "n" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 6, side: "s" },
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 6, side: "n" },
    ],
  },
  "crystal-scout": {
    cols: 3,
    rows: 6,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 2, system: null },
      { x: 1, y: 4, w: 1, h: 1, system: null },
      { x: 2, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 3, side: "s" },
    ],
  },
  "crystal-bomber": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 2, y: 2, w: 1, h: 1, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 1, h: 1, system: null },
      { x: 4, y: 3, w: 1, h: 1, system: null },
      { x: 3, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 2, h: 2, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 1, y: 3, side: "n" },
      { x: 1, y: 4, side: "s" },
      { x: 1, y: 6, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  "crystal-instigator": {
    cols: 5,
    rows: 8,
    rooms: [
      { x: 0, y: 0, w: 1, h: 1, system: null },
      { x: 1, y: 0, w: 2, h: 2, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 2, h: 2, system: null },
      { x: 3, y: 7, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  "lanius-scout": {
    cols: 8,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 1, h: 1, system: null },
      { x: 2, y: 0, w: 1, h: 1, system: null },
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 5, y: 0, w: 2, h: 1, system: null },
      { x: 0, y: 1, w: 2, h: 1, system: null },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 2, system: null },
      { x: 7, y: 1, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 2, y: 0, side: "s" },
      { x: 3, y: 1, side: "n" },
      { x: 3, y: 2, side: "e" },
      { x: 4, y: 0, side: "s" },
      { x: 5, y: 0, side: "s" },
      { x: 5, y: 1, side: "e" },
    ],
  },
  "lanius-bomber": {
    cols: 7,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 1, system: null },
      { x: 5, y: 0, w: 1, h: 1, system: null },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 6, y: 1, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 2, system: null },
      { x: 3, y: 2, w: 1, h: 1, system: null },
      { x: 4, y: 2, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 1, h: 2, system: null },
      { x: 6, y: 3, w: 1, h: 1, system: null },
      { x: 5, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 2, side: "e" },
      { x: 0, y: 3, side: "e" },
      { x: 1, y: 2, side: "n" },
      { x: 1, y: 3, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
      { x: 5, y: 2, side: "n" },
      { x: 5, y: 3, side: "e" },
      { x: 5, y: 3, side: "s" },
    ],
  },
  "federation-scout": {
    cols: 4,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 1, h: 2, system: null },
      { x: 1, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 4, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 0, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 3, y: 4, side: "w" },
    ],
  },
  "federation-outrider": {
    cols: 4,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 1, system: null },
      { x: 1, y: 1, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 1, h: 2, system: null },
      { x: 1, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 3, w: 1, h: 2, system: null },
      { x: 2, y: 4, w: 1, h: 1, system: null },
    ],
    marks: [
      { x: 0, y: 4, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 0, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 2, y: 4, side: "e" },
    ],
  },
  "federation-bomber": {
    cols: 8,
    rows: 7,
    rooms: [
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 6, y: 2, w: 1, h: 1, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 1, h: 1, system: null },
      { x: 4, y: 3, w: 1, h: 1, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, omit: [{ x: 0, y: 4 }], system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
      { x: 6, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 1, h: 2, system: null },
      { x: 5, y: 5, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 4, side: "e" },
      { x: 5, y: 5, side: "e" },
    ],
  },
  "federation-hacker": {
    cols: 8,
    rows: 7,
    rooms: [
      { x: 4, y: 0, w: 1, h: 1, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 6, y: 2, w: 1, h: 1, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: null },
      { x: 6, y: 4, w: 2, h: 2, system: null },
      { x: 2, y: 5, w: 1, h: 2, system: null },
      { x: 5, y: 5, w: 1, h: 2, system: null },
    ],
    marks: [
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 4, side: "e" },
      { x: 5, y: 5, side: "e" },
    ],
  },
};
