/**
 * Interiors for all 47 enemy classes, from ftl-layouts.mikehopley.org (linked from Enemy Ships): each room's grid
 * position, size, and system icon come from that site's room data, and the door bars (orange, or grey on Slug and
 * Zoltan hulls) are read off its room picture, cell edge by cell edge. The bitmaps are not copied.
 * A pirate version with a different interior is keyed "<class id>:pirate"; one with the same interior uses the regular key.
 * system is the room the blueprint keeps for that system, installed or not. Null is an empty room.
 * Door marks are bars on a cell edge. A shared edge with no bar stays a wall.
 */
import type { DoorMark } from "../types.ts";
import type { EnemySystem } from "./enemy-ships.ts";

export type EnemyTraceRoom = {
  x: number;
  y: number;
  w: number;
  h: number;
  system: EnemySystem | null;
  omit?: { x: number; y: number }[];
};

export type EnemyLayout = {
  cols: number;
  rows: number;
  rooms: EnemyTraceRoom[];
  marks: DoorMark[];
};

export const ENEMY_LAYOUTS: Record<string, EnemyLayout> = {
  // Rebel Fighter: ftl-layouts.mikehopley.org/img/rebel/fighter_2.png
  "rebel-fighter": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 2, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 5, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "shields" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 3, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "e" },
    ],
  },
  // Pirate Rebel Fighter: ftl-layouts.mikehopley.org/img/rebel/pirate/fighter_2.png
  "rebel-fighter:pirate": {
    cols: 7,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 2, w: 1, h: 2, system: null },
      { x: 3, y: 4, w: 1, h: 2, system: null },
      { x: 1, y: 5, w: 2, h: 1, system: "weapons" },
      { x: 4, y: 5, w: 2, h: 1, system: "shields" },
      { x: 0, y: 6, w: 2, h: 1, system: "doors" },
      { x: 3, y: 6, w: 1, h: 2, system: "engines" },
      { x: 5, y: 6, w: 2, h: 1, system: "teleporter" },
      { x: 1, y: 7, w: 2, h: 1, system: "medbay" },
      { x: 4, y: 7, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 5, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 5, side: "e" },
      { x: 3, y: 5, side: "s" },
      { x: 5, y: 5, side: "s" },
      { x: 1, y: 6, side: "s" },
      { x: 5, y: 6, side: "s" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 7, side: "e" },
    ],
  },
  // Rebel Invader: ftl-layouts.mikehopley.org/img/rebel/invader_2.png
  "rebel-invader": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 2, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 5, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "weapons" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 3, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "e" },
    ],
  },
  // Pirate Rebel Invader: ftl-layouts.mikehopley.org/img/rebel/pirate/invader_2.png
  "rebel-invader:pirate": {
    cols: 7,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 2, w: 1, h: 2, system: "weapons" },
      { x: 3, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 5, w: 2, h: 1, system: "clonebay" },
      { x: 4, y: 5, w: 2, h: 1, system: "teleporter" },
      { x: 0, y: 6, w: 2, h: 1, system: "shields" },
      { x: 3, y: 6, w: 1, h: 2, system: "doors" },
      { x: 5, y: 6, w: 2, h: 1, system: "engines" },
      { x: 1, y: 7, w: 2, h: 1, system: null },
      { x: 4, y: 7, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 3, y: 1, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 5, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 5, side: "e" },
      { x: 3, y: 5, side: "s" },
      { x: 5, y: 5, side: "s" },
      { x: 1, y: 6, side: "s" },
      { x: 5, y: 6, side: "s" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 7, side: "e" },
    ],
  },
  // Rebel Rigger: ftl-layouts.mikehopley.org/img/rebel/rigger_2.png
  "rebel-rigger": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 1, system: "drones" },
      { x: 0, y: 2, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 2, w: 1, h: 2, system: "medbay" },
      { x: 2, y: 2, w: 2, h: 2, system: "shields" },
      { x: 4, y: 2, w: 2, h: 1, system: "doors" },
      { x: 4, y: 3, w: 2, h: 1, system: "weapons" },
      { x: 2, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 4, y: 1, side: "s" },
      { x: 0, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Pirate Rebel Rigger: ftl-layouts.mikehopley.org/img/rebel/pirate/rigger_2.png
  "rebel-rigger:pirate": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 1, system: "doors" },
      { x: 2, y: 2, w: 1, h: 2, system: "weapons" },
      { x: 4, y: 2, w: 2, h: 2, system: "drones" },
      { x: 0, y: 3, w: 2, h: 1, system: "medbay" },
      { x: 3, y: 3, w: 1, h: 2, system: "engines" },
      { x: 0, y: 4, w: 2, h: 1, system: "shields" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 0, y: 3, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Rebel Disruptor: ftl-layouts.mikehopley.org/img/rebel/disruptor_2.png
  "rebel-disruptor": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 0, y: 2, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 2, w: 1, h: 2, system: "clonebay" },
      { x: 2, y: 2, w: 2, h: 2, system: "drones" },
      { x: 4, y: 2, w: 2, h: 1, system: "hacking" },
      { x: 4, y: 3, w: 2, h: 1, system: "engines" },
      { x: 2, y: 4, w: 2, h: 1, system: "shields" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 4, y: 1, side: "s" },
      { x: 0, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "s" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Pirate Rebel Disruptor: ftl-layouts.mikehopley.org/img/rebel/pirate/disruptor_2.png
  "rebel-disruptor:pirate": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 1, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 2, y: 2, w: 1, h: 2, system: "drones" },
      { x: 4, y: 2, w: 2, h: 2, system: "hacking" },
      { x: 0, y: 3, w: 2, h: 1, system: "engines" },
      { x: 3, y: 3, w: 1, h: 2, system: "shields" },
      { x: 0, y: 4, w: 2, h: 1, system: "weapons" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 0, y: 3, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Rebel Elite Fighter: ftl-layouts.mikehopley.org/img/rebel/elite_fighter_2.png
  "elite-fighter": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 2, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 5, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "shields" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 3, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "e" },
    ],
  },
  // Rebel Elite Assault: ftl-layouts.mikehopley.org/img/rebel/elite_assault_2.png
  "elite-assault": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 2, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 5, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 1, h: 2, system: "engines" },
      { x: 3, y: 5, w: 2, h: 2, system: "weapons" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 3, y: 4, side: "s" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "e" },
    ],
  },
  // Auto-Scout: ftl-layouts.mikehopley.org/img/auto/scout_2.png
  "auto-scout": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: "cloaking" },
      { x: 5, y: 0, w: 2, h: 1, system: "weapons" },
      { x: 1, y: 1, w: 2, h: 1, system: "engines" },
      { x: 3, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 4, y: 1, w: 2, h: 1, system: "shields" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 5, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
    ],
  },
  // Auto-Surveyor: ftl-layouts.mikehopley.org/img/auto/surveyor_2.png
  "auto-surveyor": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: "engines" },
      { x: 5, y: 0, w: 2, h: 1, system: "mindcontrol" },
      { x: 1, y: 1, w: 2, h: 1, system: "shields" },
      { x: 3, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 4, y: 1, w: 2, h: 1, system: "weapons" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 5, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
    ],
  },
  // Auto-Assault: ftl-layouts.mikehopley.org/img/auto/assault_2.png
  "auto-assault": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "weapons" },
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 5, y: 0, w: 1, h: 2, system: "shields" },
      { x: 0, y: 1, w: 1, h: 2, system: "drones" },
      { x: 6, y: 1, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 5, y: 1, side: "e" },
    ],
  },
  // Auto-Hacker: ftl-layouts.mikehopley.org/img/auto/hacker_2.png
  "auto-hacker": {
    cols: 7,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "shields" },
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 5, y: 0, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 1, w: 1, h: 2, system: "engines" },
      { x: 6, y: 1, w: 1, h: 2, system: "hacking" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 5, y: 1, side: "e" },
    ],
  },
  // Engi Scout: ftl-layouts.mikehopley.org/img/engi/scout_2.png
  "engi-scout": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "drones" },
      { x: 1, y: 0, w: 2, h: 2, system: "shields" },
      { x: 3, y: 0, w: 2, h: 1, system: "doors" },
      { x: 4, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 1, system: "engines" },
      { x: 1, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 4, y: 3, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 4, w: 2, h: 1, system: "pilot" },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 4, y: 0, side: "s" },
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 3, y: 4, side: "e" },
    ],
  },
  // Engi Outrider: ftl-layouts.mikehopley.org/img/engi/outrider_2.png
  "engi-outrider": {
    cols: 6,
    rows: 5,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "drones" },
      { x: 1, y: 0, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 0, w: 2, h: 1, system: "hacking" },
      { x: 4, y: 1, w: 1, h: 2, system: "shields" },
      { x: 0, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 1, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 4, y: 3, w: 2, h: 2, system: "engines" },
      { x: 2, y: 4, w: 2, h: 1, system: "pilot" },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 2, y: 0, side: "e" },
      { x: 4, y: 0, side: "s" },
      { x: 0, y: 1, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 3, y: 4, side: "e" },
    ],
  },
  // Engi Bomber: ftl-layouts.mikehopley.org/img/engi/bomber_2.png
  "engi-bomber": {
    cols: 6,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 2, y: 1, w: 2, h: 1, system: "doors" },
      { x: 4, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 2, w: 1, h: 2, system: "medbay" },
      { x: 5, y: 2, w: 1, h: 2, system: "drones" },
      { x: 0, y: 4, w: 2, h: 1, system: null },
      { x: 4, y: 4, w: 2, h: 1, system: null },
      { x: 0, y: 5, w: 2, h: 2, system: "engines" },
      { x: 4, y: 5, w: 2, h: 2, system: "shields" },
      { x: 2, y: 6, w: 2, h: 1, system: null },
    ],
    marks: [
      { x: 1, y: 0, side: "e" },
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "e" },
      { x: 5, y: 1, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 0, y: 3, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 5, y: 3, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 4, y: 4, side: "s" },
      { x: 1, y: 6, side: "e" },
      { x: 3, y: 6, side: "e" },
    ],
  },
  // Engi Hacker: ftl-layouts.mikehopley.org/img/engi/hacker_2.png
  "engi-hacker": {
    cols: 6,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: null },
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 2, y: 1, w: 2, h: 1, system: "doors" },
      { x: 4, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 2, system: "shields" },
      { x: 4, y: 2, w: 1, h: 2, system: "clonebay" },
      { x: 5, y: 2, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 1, system: null },
      { x: 4, y: 4, w: 2, h: 1, system: "drones" },
      { x: 0, y: 5, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 5, w: 2, h: 2, system: "engines" },
      { x: 2, y: 6, w: 2, h: 1, system: "hacking" },
    ],
    marks: [
      { x: 1, y: 0, side: "e" },
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "e" },
      { x: 5, y: 1, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 0, y: 3, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 5, y: 3, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 4, y: 4, side: "s" },
      { x: 1, y: 6, side: "e" },
      { x: 3, y: 6, side: "e" },
    ],
  },
  // Mantis Scout: ftl-layouts.mikehopley.org/img/mantis/scout_2.png
  "mantis-scout": {
    cols: 8,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "shields" },
      { x: 7, y: 0, w: 1, h: 2, system: "engines" },
      { x: 1, y: 1, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 5, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 1, y: 2, w: 2, h: 1, system: "doors" },
      { x: 5, y: 2, w: 2, h: 1, system: "medbay" },
      { x: 3, y: 3, w: 2, h: 1, system: "teleporter" },
    ],
    marks: [
      { x: 7, y: 0, side: "e" },
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 5, y: 1, side: "s" },
      { x: 6, y: 1, side: "e" },
      { x: 7, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  // Pirate Mantis Scout: ftl-layouts.mikehopley.org/img/mantis/pirate/scout_2.png
  "mantis-scout:pirate": {
    cols: 7,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: "shields" },
      { x: 5, y: 0, w: 2, h: 1, system: "weapons" },
      { x: 0, y: 1, w: 1, h: 2, system: "engines" },
      { x: 6, y: 1, w: 1, h: 2, system: "medbay" },
      { x: 1, y: 2, w: 2, h: 1, system: "teleporter" },
      { x: 3, y: 2, w: 1, h: 2, system: "pilot" },
      { x: 4, y: 2, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 0, y: 0, side: "s" },
      { x: 6, y: 0, side: "s" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
    ],
  },
  // Mantis Interceptor: ftl-layouts.mikehopley.org/img/mantis/interceptor_2.png
  "mantis-interceptor": {
    cols: 8,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "clonebay" },
      { x: 7, y: 0, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 3, y: 1, w: 2, h: 2, system: "shields" },
      { x: 5, y: 1, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 2, w: 2, h: 1, system: "doors" },
      { x: 5, y: 2, w: 2, h: 1, system: "weapons" },
      { x: 3, y: 3, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 7, y: 0, side: "e" },
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "s" },
      { x: 5, y: 1, side: "s" },
      { x: 6, y: 1, side: "e" },
      { x: 7, y: 1, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
    ],
  },
  // Pirate Mantis Interceptor: ftl-layouts.mikehopley.org/img/mantis/pirate/interceptor_2.png
  "mantis-interceptor:pirate": {
    cols: 7,
    rows: 4,
    rooms: [
      { x: 0, y: 0, w: 2, h: 1, system: "engines" },
      { x: 5, y: 0, w: 2, h: 1, system: "clonebay" },
      { x: 0, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 6, y: 1, w: 1, h: 2, system: "shields" },
      { x: 1, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 3, y: 2, w: 1, h: 2, system: "pilot" },
      { x: 4, y: 2, w: 2, h: 1, system: "teleporter" },
    ],
    marks: [
      { x: 0, y: 0, side: "s" },
      { x: 6, y: 0, side: "s" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
    ],
  },
  // Mantis Fighter: ftl-layouts.mikehopley.org/img/mantis/fighter_2.png
  "mantis-fighter": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 1, w: 1, h: 2, system: "shields" },
      { x: 3, y: 1, w: 2, h: 1, system: "medbay" },
      { x: 7, y: 1, w: 1, h: 2, system: "engines" },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 5, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 1, y: 3, w: 2, h: 1, system: "doors" },
      { x: 5, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: "teleporter" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 4, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 6, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
    ],
  },
  // Pirate Mantis Fighter: ftl-layouts.mikehopley.org/img/mantis/pirate/fighter_2.png
  "mantis-fighter:pirate": {
    cols: 7,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 4, y: 0, w: 1, h: 2, system: "doors" },
      { x: 0, y: 1, w: 1, h: 2, system: "medbay" },
      { x: 3, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 6, y: 1, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 2, w: 2, h: 2, system: "shields" },
      { x: 3, y: 3, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Mantis Assault: ftl-layouts.mikehopley.org/img/mantis/assault_2.png
  "mantis-assault": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 1, w: 1, h: 2, system: "clonebay" },
      { x: 3, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 7, y: 1, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 2, w: 2, h: 1, system: null },
      { x: 3, y: 2, w: 2, h: 2, system: "shields" },
      { x: 5, y: 2, w: 2, h: 1, system: "doors" },
      { x: 1, y: 3, w: 2, h: 1, system: "weapons" },
      { x: 5, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 4, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 6, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
    ],
  },
  // Pirate Mantis Assault: ftl-layouts.mikehopley.org/img/mantis/pirate/assault_2.png
  "mantis-assault:pirate": {
    cols: 7,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "teleporter" },
      { x: 4, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 1, w: 1, h: 2, system: "shields" },
      { x: 3, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 6, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 2, w: 2, h: 2, system: "clonebay" },
      { x: 4, y: 2, w: 2, h: 2, system: "doors" },
      { x: 3, y: 3, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
    ],
  },
  // Mantis Bomber: ftl-layouts.mikehopley.org/img/mantis/bomber_2.png
  "mantis-bomber": {
    cols: 8,
    rows: 9,
    rooms: [
      { x: 3, y: 0, w: 2, h: 2, system: "shields" },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 5, w: 2, h: 1, system: "teleporter" },
      { x: 0, y: 6, w: 1, h: 2, system: "doors" },
      { x: 3, y: 6, w: 2, h: 2, system: null },
      { x: 7, y: 6, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 7, w: 2, h: 2, system: "medbay" },
      { x: 5, y: 7, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 8, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 3, y: 1, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 4, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 4, y: 4, side: "e" },
      { x: 4, y: 4, side: "s" },
      { x: 3, y: 5, side: "s" },
      { x: 0, y: 7, side: "e" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 7, side: "s" },
      { x: 4, y: 7, side: "e" },
      { x: 4, y: 7, side: "s" },
      { x: 6, y: 7, side: "e" },
    ],
  },
  // Pirate Mantis Bomber: ftl-layouts.mikehopley.org/img/mantis/pirate/bomber_2.png
  "mantis-bomber:pirate": {
    cols: 7,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 2, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 4, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 4, w: 1, h: 2, system: "pilot" },
      { x: 1, y: 5, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 5, w: 2, h: 2, system: "shields" },
      { x: 0, y: 6, w: 1, h: 2, system: "doors" },
      { x: 6, y: 6, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 7, w: 2, h: 1, system: "engines" },
      { x: 4, y: 7, w: 2, h: 1, system: "medbay" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 4, side: "e" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 5, side: "e" },
      { x: 0, y: 6, side: "e" },
      { x: 2, y: 6, side: "s" },
      { x: 4, y: 6, side: "s" },
      { x: 5, y: 6, side: "e" },
    ],
  },
  // Mantis Aggressor: ftl-layouts.mikehopley.org/img/mantis/aggressor_2.png
  "mantis-aggressor": {
    cols: 8,
    rows: 9,
    rooms: [
      { x: 3, y: 0, w: 2, h: 2, system: "clonebay" },
      { x: 3, y: 2, w: 2, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 4, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 5, w: 2, h: 1, system: "teleporter" },
      { x: 0, y: 6, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 6, w: 2, h: 2, system: null },
      { x: 7, y: 6, w: 1, h: 2, system: "doors" },
      { x: 1, y: 7, w: 2, h: 2, system: "weapons" },
      { x: 5, y: 7, w: 2, h: 2, system: "shields" },
      { x: 3, y: 8, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 3, y: 1, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 4, y: 3, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 4, y: 4, side: "e" },
      { x: 4, y: 4, side: "s" },
      { x: 3, y: 5, side: "s" },
      { x: 0, y: 7, side: "e" },
      { x: 2, y: 7, side: "e" },
      { x: 3, y: 7, side: "s" },
      { x: 4, y: 7, side: "e" },
      { x: 4, y: 7, side: "s" },
      { x: 6, y: 7, side: "e" },
    ],
  },
  // Pirate Mantis Aggressor: ftl-layouts.mikehopley.org/img/mantis/pirate/aggressor_2.png
  "mantis-aggressor:pirate": {
    cols: 7,
    rows: 8,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 1, w: 1, h: 2, system: null },
      { x: 4, y: 1, w: 1, h: 2, system: null },
      { x: 2, y: 3, w: 1, h: 2, system: "teleporter" },
      { x: 4, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 3, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 5, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 5, w: 2, h: 2, system: "shields" },
      { x: 0, y: 6, w: 1, h: 2, system: null },
      { x: 6, y: 6, w: 1, h: 2, system: null },
      { x: 1, y: 7, w: 2, h: 1, system: "doors" },
      { x: 4, y: 7, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 4, side: "e" },
      { x: 2, y: 5, side: "e" },
      { x: 3, y: 5, side: "e" },
      { x: 0, y: 6, side: "e" },
      { x: 2, y: 6, side: "s" },
      { x: 4, y: 6, side: "s" },
      { x: 5, y: 6, side: "e" },
    ],
  },
  // Slug Interceptor: ftl-layouts.mikehopley.org/img/slug/interceptor_2.png
  "slug-interceptor": {
    cols: 4,
    rows: 4,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 1, h: 2, system: "shields" },
      { x: 2, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 2, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 2, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
    ],
  },
  // Pirate Slug Interceptor: ftl-layouts.mikehopley.org/img/slug/pirate/interceptor_2.png
  "slug-interceptor:pirate": {
    cols: 5,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 1, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 1, w: 1, h: 2, system: "doors" },
      { x: 0, y: 3, w: 2, h: 1, system: "shields" },
      { x: 2, y: 3, w: 1, h: 2, system: "engines" },
      { x: 3, y: 3, w: 2, h: 1, system: "weapons" },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
    ],
  },
  // Slug Scout: ftl-layouts.mikehopley.org/img/slug/scout_2.png
  "slug-scout": {
    cols: 4,
    rows: 4,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 1, h: 2, system: "shields" },
      { x: 2, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 2, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 2, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
    ],
  },
  // Pirate Slug Scout: ftl-layouts.mikehopley.org/img/slug/pirate/scout_2.png
  "slug-scout:pirate": {
    cols: 5,
    rows: 5,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 1, w: 1, h: 2, system: "mindcontrol" },
      { x: 0, y: 3, w: 2, h: 1, system: "engines" },
      { x: 2, y: 3, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 3, w: 2, h: 1, system: "shields" },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
    ],
  },
  // Slug Light-Cruiser: ftl-layouts.mikehopley.org/img/slug/light-cruiser_2.png
  "slug-light-cruiser": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 1, w: 2, h: 2, system: null },
      { x: 5, y: 1, w: 2, h: 2, system: "shields" },
      { x: 0, y: 3, w: 2, h: 1, system: "oxygen" },
      { x: 3, y: 3, w: 2, h: 1, system: "doors" },
      { x: 6, y: 3, w: 2, h: 1, system: "medbay" },
      { x: 3, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 4, y: 1, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
    ],
  },
  // Pirate Slug Light-Cruiser: ftl-layouts.mikehopley.org/img/slug/pirate/light-cruiser_2.png
  "slug-light-cruiser:pirate": {
    cols: 8,
    rows: 6,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: null },
      { x: 4, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 2, y: 1, w: 1, h: 2, system: "shields" },
      { x: 5, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 2, w: 2, h: 2, system: "medbay" },
      { x: 6, y: 2, w: 2, h: 2, system: "doors" },
      { x: 2, y: 3, w: 2, h: 1, system: "oxygen" },
      { x: 4, y: 3, w: 2, h: 1, system: "cloaking" },
      { x: 3, y: 4, w: 2, h: 2, system: "engines" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 3, y: 0, side: "e" },
      { x: 5, y: 0, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 3, side: "e" },
    ],
  },
  // Slug Light-Surveyor: ftl-layouts.mikehopley.org/img/slug/light-surveyor_2.png
  "slug-light-surveyor": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 1, w: 2, h: 2, system: "engines" },
      { x: 5, y: 1, w: 2, h: 2, system: "shields" },
      { x: 0, y: 3, w: 2, h: 1, system: "oxygen" },
      { x: 3, y: 3, w: 2, h: 1, system: null },
      { x: 6, y: 3, w: 2, h: 1, system: "mindcontrol" },
      { x: 3, y: 4, w: 2, h: 1, system: "clonebay" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 2, y: 1, side: "e" },
      { x: 4, y: 1, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
    ],
  },
  // Pirate Slug Light-Surveyor: ftl-layouts.mikehopley.org/img/slug/pirate/light-surveyor_2.png
  "slug-light-surveyor:pirate": {
    cols: 8,
    rows: 6,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 4, y: 0, w: 2, h: 1, system: "clonebay" },
      { x: 2, y: 1, w: 1, h: 2, system: "mindcontrol" },
      { x: 5, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 2, system: "shields" },
      { x: 6, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 3, w: 2, h: 1, system: null },
      { x: 4, y: 3, w: 2, h: 1, system: null },
      { x: 3, y: 4, w: 2, h: 2, system: "engines" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 3, y: 0, side: "e" },
      { x: 5, y: 0, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 5, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 4, y: 3, side: "s" },
      { x: 5, y: 3, side: "e" },
    ],
  },
  // Slug Assault: ftl-layouts.mikehopley.org/img/slug/assault_2.png
  "slug-assault": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 2, system: "doors" },
      { x: 1, y: 2, w: 2, h: 1, system: "weapons" },
      { x: 5, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 0, y: 3, w: 2, h: 1, system: "shields" },
      { x: 3, y: 3, w: 2, h: 1, system: "engines" },
      { x: 6, y: 3, w: 2, h: 1, system: "cloaking" },
      { x: 3, y: 4, w: 2, h: 1, system: "medbay" },
    ],
    marks: [
      { x: 3, y: 0, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
    ],
  },
  // Pirate Slug Assault: ftl-layouts.mikehopley.org/img/slug/pirate/assault_2.png
  "slug-assault:pirate": {
    cols: 7,
    rows: 6,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 1, system: "weapons" },
      { x: 4, y: 1, w: 2, h: 1, system: "cloaking" },
      { x: 3, y: 2, w: 1, h: 2, system: null },
      { x: 0, y: 3, w: 1, h: 2, system: "doors" },
      { x: 1, y: 3, w: 2, h: 1, system: "engines" },
      { x: 4, y: 3, w: 2, h: 1, system: "shields" },
      { x: 6, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 4, w: 1, h: 2, system: "medbay" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 1, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 5, y: 3, side: "e" },
    ],
  },
  // Slug Instigator: ftl-layouts.mikehopley.org/img/slug/instigator_2.png
  "slug-instigator": {
    cols: 8,
    rows: 5,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 1, y: 2, w: 2, h: 1, system: "shields" },
      { x: 5, y: 2, w: 2, h: 1, system: "mindcontrol" },
      { x: 0, y: 3, w: 2, h: 1, system: "oxygen" },
      { x: 3, y: 3, w: 2, h: 1, system: "cloaking" },
      { x: 6, y: 3, w: 2, h: 1, system: "clonebay" },
      { x: 3, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 3, y: 0, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 4, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 6, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
    ],
  },
  // Pirate Slug Instigator: ftl-layouts.mikehopley.org/img/slug/pirate/instigator_2.png
  "slug-instigator:pirate": {
    cols: 7,
    rows: 6,
    rooms: [
      { x: 3, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 4, y: 1, w: 2, h: 1, system: "doors" },
      { x: 3, y: 2, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 3, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 3, w: 2, h: 1, system: "mindcontrol" },
      { x: 4, y: 3, w: 2, h: 1, system: null },
      { x: 6, y: 3, w: 1, h: 2, system: "shields" },
      { x: 3, y: 4, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 2, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 1, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 2, y: 3, side: "e" },
      { x: 3, y: 3, side: "e" },
      { x: 3, y: 3, side: "s" },
      { x: 5, y: 3, side: "e" },
    ],
  },
  // Rock Scout: ftl-layouts.mikehopley.org/img/rock/scout_2.png
  "rock-scout": {
    cols: 3,
    rows: 7,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 0, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 2, w: 1, h: 2, system: "medbay" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 3, w: 2, h: 2, system: "shields" },
      { x: 0, y: 4, w: 1, h: 2, system: "doors" },
      { x: 1, y: 5, w: 1, h: 2, system: "engines" },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 0, y: 4, side: "e" },
      { x: 0, y: 5, side: "e" },
    ],
  },
  // Pirate Rock Scout: ftl-layouts.mikehopley.org/img/rock/pirate/scout_2.png
  "rock-scout:pirate": {
    cols: 4,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 1, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 1, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 3, w: 2, h: 2, system: "shields" },
      { x: 1, y: 5, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 1, y: 4, side: "s" },
    ],
  },
  // Rock Investigator: ftl-layouts.mikehopley.org/img/rock/investigator_2.png
  "rock-investigator": {
    cols: 3,
    rows: 7,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 0, w: 2, h: 2, system: "engines" },
      { x: 0, y: 2, w: 1, h: 2, system: "shields" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 3, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 5, w: 1, h: 2, system: "clonebay" },
    ],
    marks: [
      { x: 0, y: 0, side: "e" },
      { x: 0, y: 1, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 0, y: 3, side: "e" },
      { x: 0, y: 4, side: "e" },
      { x: 0, y: 5, side: "e" },
    ],
  },
  // Pirate Rock Investigator: ftl-layouts.mikehopley.org/img/rock/pirate/investigator_2.png
  "rock-investigator:pirate": {
    cols: 4,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "pilot" },
      { x: 0, y: 1, w: 1, h: 2, system: "weapons" },
      { x: 3, y: 1, w: 1, h: 2, system: "shields" },
      { x: 1, y: 2, w: 2, h: 1, system: "oxygen" },
      { x: 1, y: 3, w: 2, h: 2, system: "clonebay" },
      { x: 1, y: 5, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 2, y: 2, side: "s" },
      { x: 1, y: 4, side: "s" },
    ],
  },
  // Rock Fighter: ftl-layouts.mikehopley.org/img/rock/fighter_2.png
  "rock-fighter": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: null },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 3, w: 2, h: 1, system: "medbay" },
      { x: 2, y: 3, w: 2, h: 2, system: "oxygen" },
      { x: 0, y: 4, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 2, h: 2, system: "engines" },
      { x: 0, y: 6, w: 2, h: 1, system: "doors" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
    ],
  },
  // Pirate Rock Fighter: ftl-layouts.mikehopley.org/img/rock/pirate/fighter_2.png
  "rock-fighter:pirate": {
    cols: 5,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 0, w: 1, h: 2, system: "doors" },
      { x: 2, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 0, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 2, w: 2, h: 2, system: "shields" },
      { x: 1, y: 4, w: 1, h: 2, system: "cloaking" },
      { x: 2, y: 4, w: 1, h: 2, system: "engines" },
      { x: 3, y: 4, w: 1, h: 2, system: "medbay" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
    ],
  },
  // Rock Interceptor: ftl-layouts.mikehopley.org/img/rock/interceptor_2.png
  "rock-interceptor": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "clonebay" },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 1, h: 2, system: "cloaking" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 3, w: 2, h: 1, system: "oxygen" },
      { x: 2, y: 3, w: 2, h: 2, system: "engines" },
      { x: 0, y: 4, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 5, w: 2, h: 2, system: "shields" },
      { x: 0, y: 6, w: 2, h: 1, system: "teleporter" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 1, y: 3, side: "e" },
      { x: 1, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 1, y: 6, side: "e" },
    ],
  },
  // Pirate Rock Interceptor: ftl-layouts.mikehopley.org/img/rock/pirate/interceptor_2.png
  "rock-interceptor:pirate": {
    cols: 5,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "shields" },
      { x: 3, y: 0, w: 1, h: 2, system: "weapons" },
      { x: 2, y: 1, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 2, w: 2, h: 2, system: "cloaking" },
      { x: 3, y: 2, w: 2, h: 2, system: "engines" },
      { x: 1, y: 4, w: 1, h: 2, system: "teleporter" },
      { x: 2, y: 4, w: 1, h: 2, system: "pilot" },
      { x: 3, y: 4, w: 1, h: 2, system: "oxygen" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
    ],
  },
  // Rock Assault: ftl-layouts.mikehopley.org/img/rock/assault_2.png
  "rock-assault": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 1, w: 2, h: 1, system: "medbay" },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: "doors" },
      { x: 2, y: 3, w: 2, h: 2, system: "cloaking" },
      { x: 0, y: 4, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 4, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 2, h: 2, system: "engines" },
      { x: 1, y: 7, w: 2, h: 1, system: "teleporter" },
      { x: 3, y: 7, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 2, y: 4, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 6, side: "s" },
    ],
  },
  // Rock Aggressor: ftl-layouts.mikehopley.org/img/rock/aggressor_2.png
  "rock-aggressor": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 1, w: 2, h: 1, system: "clonebay" },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: "doors" },
      { x: 2, y: 3, w: 2, h: 2, system: "cloaking" },
      { x: 0, y: 4, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 4, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 2, h: 2, system: "engines" },
      { x: 1, y: 7, w: 2, h: 1, system: "teleporter" },
      { x: 3, y: 7, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 2, y: 4, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 6, side: "s" },
    ],
  },
  // Rock Assault (Elite): ftl-layouts.mikehopley.org/img/rock/assault_elite_2.png
  "rock-assault-elite": {
    cols: 6,
    rows: 8,
    rooms: [
      { x: 2, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 1, w: 2, h: 1, system: "medbay" },
      { x: 2, y: 1, w: 2, h: 2, system: null },
      { x: 4, y: 1, w: 2, h: 1, system: "doors" },
      { x: 2, y: 3, w: 2, h: 2, system: "cloaking" },
      { x: 0, y: 4, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 4, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 2, h: 2, system: "engines" },
      { x: 1, y: 7, w: 2, h: 1, system: "teleporter" },
      { x: 3, y: 7, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 1, side: "e" },
      { x: 3, y: 1, side: "e" },
      { x: 3, y: 2, side: "s" },
      { x: 2, y: 4, side: "s" },
      { x: 3, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 2, y: 6, side: "s" },
      { x: 3, y: 6, side: "s" },
    ],
  },
  // Zoltan Fighter: ftl-layouts.mikehopley.org/img/zoltan/fighter_2.png
  "energy-fighter": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "engines" },
      { x: 2, y: 2, w: 1, h: 2, system: "shields" },
      { x: 4, y: 3, w: 1, h: 2, system: "medbay" },
      { x: 1, y: 4, w: 2, h: 2, system: "doors" },
      { x: 3, y: 5, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 6, w: 2, h: 1, system: "oxygen" },
      { x: 2, y: 6, w: 2, h: 1, system: "weapons" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 4, y: 4, side: "s" },
      { x: 1, y: 5, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 2, y: 5, side: "s" },
    ],
  },
  // Pirate Zoltan Fighter: ftl-layouts.mikehopley.org/img/zoltan/pirate/fighter_2.png
  "energy-fighter:pirate": {
    cols: 4,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "medbay" },
      { x: 2, y: 1, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 2, w: 2, h: 2, system: "shields" },
      { x: 3, y: 2, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 4, w: 2, h: 1, system: "doors" },
      { x: 2, y: 4, w: 2, h: 1, system: "weapons" },
      { x: 0, y: 5, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 0, y: 3, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
    ],
  },
  // Zoltan Instigator: ftl-layouts.mikehopley.org/img/zoltan/instigator_2.png
  "energy-instigator": {
    cols: 5,
    rows: 7,
    rooms: [
      { x: 2, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 2, w: 1, h: 2, system: "mindcontrol" },
      { x: 4, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 1, y: 4, w: 2, h: 2, system: "shields" },
      { x: 3, y: 5, w: 2, h: 1, system: "engines" },
      { x: 0, y: 6, w: 2, h: 1, system: "weapons" },
      { x: 2, y: 6, w: 2, h: 1, system: "oxygen" },
    ],
    marks: [
      { x: 2, y: 1, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 4, y: 4, side: "s" },
      { x: 1, y: 5, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 2, y: 5, side: "s" },
    ],
  },
  // Pirate Zoltan Instigator: ftl-layouts.mikehopley.org/img/zoltan/pirate/instigator_2.png
  "energy-instigator:pirate": {
    cols: 4,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "pilot" },
      { x: 2, y: 1, w: 2, h: 1, system: "oxygen" },
      { x: 0, y: 2, w: 2, h: 2, system: "shields" },
      { x: 3, y: 2, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 4, w: 2, h: 1, system: "mindcontrol" },
      { x: 2, y: 4, w: 2, h: 1, system: "engines" },
      { x: 0, y: 5, w: 2, h: 1, system: "weapons" },
    ],
    marks: [
      { x: 1, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 3, y: 1, side: "s" },
      { x: 0, y: 3, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
    ],
  },
  // Zoltan Bomber: ftl-layouts.mikehopley.org/img/zoltan/bomber_2.png
  "energy-bomber": {
    cols: 4,
    rows: 9,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "drones" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 2, w: 1, h: 2, system: "doors" },
      { x: 1, y: 3, w: 2, h: 2, system: "shields" },
      { x: 3, y: 4, w: 1, h: 2, system: "weapons" },
      { x: 1, y: 5, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 6, w: 1, h: 2, system: "medbay" },
      { x: 0, y: 7, w: 2, h: 2, system: "engines" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 5, side: "s" },
      { x: 1, y: 6, side: "s" },
    ],
  },
  // Pirate Zoltan Bomber: ftl-layouts.mikehopley.org/img/zoltan/pirate/bomber_2.png
  "energy-bomber:pirate": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 1, h: 2, system: "drones" },
      { x: 2, y: 2, w: 2, h: 1, system: "medbay" },
      { x: 0, y: 3, w: 2, h: 2, system: "shields" },
      { x: 3, y: 3, w: 1, h: 2, system: "weapons" },
      { x: 2, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 0, y: 5, w: 1, h: 2, system: "doors" },
      { x: 1, y: 6, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 2, y: 5, side: "s" },
      { x: 0, y: 6, side: "e" },
    ],
  },
  // Zoltan Hacker: ftl-layouts.mikehopley.org/img/zoltan/hacker_2.png
  "energy-hacker": {
    cols: 4,
    rows: 9,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "hacking" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 2, w: 1, h: 2, system: "doors" },
      { x: 1, y: 3, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 4, w: 1, h: 2, system: "shields" },
      { x: 1, y: 5, w: 1, h: 2, system: "oxygen" },
      { x: 3, y: 6, w: 1, h: 2, system: "engines" },
      { x: 0, y: 7, w: 2, h: 2, system: "clonebay" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 2, y: 1, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 4, side: "e" },
      { x: 3, y: 5, side: "s" },
      { x: 1, y: 6, side: "s" },
    ],
  },
  // Pirate Zoltan Hacker: ftl-layouts.mikehopley.org/img/zoltan/pirate/hacker_2.png
  "energy-hacker:pirate": {
    cols: 4,
    rows: 7,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "hacking" },
      { x: 1, y: 1, w: 1, h: 2, system: "doors" },
      { x: 2, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 0, y: 3, w: 2, h: 2, system: "shields" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 2, y: 4, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 5, w: 1, h: 2, system: "engines" },
      { x: 1, y: 6, w: 2, h: 1, system: "clonebay" },
    ],
    marks: [
      { x: 1, y: 0, side: "s" },
      { x: 1, y: 2, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
      { x: 2, y: 5, side: "s" },
      { x: 0, y: 6, side: "e" },
    ],
  },
  // Crystal Scout: ftl-layouts.mikehopley.org/img/crystal/scout_2.png
  "crystal-scout": {
    cols: 3,
    rows: 6,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 0, w: 1, h: 2, system: "shields" },
      { x: 1, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 4, w: 2, h: 1, system: "pilot" },
      { x: 2, y: 4, w: 1, h: 2, system: "medbay" },
      { x: 0, y: 5, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
    ],
  },
  // Crystal Outrider: ftl-layouts.mikehopley.org/img/crystal/outrider_2.png
  "crystal-outrider": {
    cols: 3,
    rows: 6,
    rooms: [
      { x: 0, y: 0, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 0, w: 1, h: 2, system: "shields" },
      { x: 1, y: 2, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 4, w: 2, h: 1, system: "pilot" },
      { x: 2, y: 4, w: 1, h: 2, system: "clonebay" },
      { x: 0, y: 5, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 1, y: 1, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 0, y: 4, side: "s" },
      { x: 1, y: 4, side: "e" },
    ],
  },
  // Crystal Bomber: ftl-layouts.mikehopley.org/img/crystal/bomber_2.png
  "crystal-bomber": {
    cols: 5,
    rows: 8,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "medbay" },
      { x: 0, y: 1, w: 1, h: 2, system: null },
      { x: 3, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: "doors" },
      { x: 3, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 5, w: 2, h: 2, system: "shields" },
      { x: 1, y: 7, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 1, y: 6, side: "s" },
    ],
  },
  // Crystal Instigator: ftl-layouts.mikehopley.org/img/crystal/instigator_2.png
  "crystal-instigator": {
    cols: 5,
    rows: 8,
    rooms: [
      { x: 1, y: 0, w: 2, h: 2, system: "clonebay" },
      { x: 0, y: 1, w: 1, h: 2, system: "cloaking" },
      { x: 3, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 1, y: 2, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 3, w: 1, h: 2, system: "teleporter" },
      { x: 3, y: 3, w: 2, h: 1, system: "doors" },
      { x: 3, y: 4, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 5, w: 2, h: 2, system: "shields" },
      { x: 1, y: 7, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 0, y: 1, side: "e" },
      { x: 2, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 2, side: "e" },
      { x: 4, y: 2, side: "s" },
      { x: 3, y: 3, side: "s" },
      { x: 1, y: 4, side: "s" },
      { x: 2, y: 5, side: "e" },
      { x: 1, y: 6, side: "s" },
    ],
  },
  // Lanius Scout: ftl-layouts.mikehopley.org/img/lanius/scout_2.png
  "lanius-scout": {
    cols: 8,
    rows: 3,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "doors" },
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 5, y: 0, w: 2, h: 1, system: "hacking" },
      { x: 0, y: 1, w: 2, h: 1, system: "clonebay" },
      { x: 2, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 4, y: 1, w: 2, h: 2, system: "shields" },
      { x: 6, y: 1, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 3, y: 0, side: "s" },
      { x: 4, y: 0, side: "s" },
      { x: 5, y: 0, side: "s" },
      { x: 1, y: 1, side: "e" },
      { x: 5, y: 1, side: "e" },
      { x: 3, y: 2, side: "e" },
    ],
  },
  // Lanius Bomber: ftl-layouts.mikehopley.org/img/lanius/bomber_2.png
  "lanius-bomber": {
    cols: 7,
    rows: 6,
    rooms: [
      { x: 1, y: 0, w: 1, h: 2, system: "shields" },
      { x: 5, y: 0, w: 1, h: 2, system: "weapons" },
      { x: 0, y: 1, w: 1, h: 2, system: "cloaking" },
      { x: 3, y: 1, w: 1, h: 2, system: "pilot" },
      { x: 6, y: 1, w: 1, h: 2, system: "mindcontrol" },
      { x: 1, y: 2, w: 2, h: 2, system: null },
      { x: 4, y: 2, w: 2, h: 2, system: null },
      { x: 0, y: 3, w: 1, h: 2, system: "clonebay" },
      { x: 6, y: 3, w: 1, h: 2, system: "teleporter" },
      { x: 1, y: 4, w: 1, h: 2, system: "engines" },
      { x: 5, y: 4, w: 1, h: 2, system: "doors" },
    ],
    marks: [
      { x: 1, y: 1, side: "s" },
      { x: 5, y: 1, side: "s" },
      { x: 6, y: 1, side: "e" },
      { x: 0, y: 2, side: "e" },
      { x: 2, y: 2, side: "e" },
      { x: 3, y: 2, side: "e" },
      { x: 5, y: 2, side: "e" },
      { x: 0, y: 3, side: "e" },
      { x: 1, y: 3, side: "s" },
      { x: 5, y: 3, side: "e" },
      { x: 5, y: 3, side: "s" },
      { x: 6, y: 4, side: "e" },
    ],
  },
  // Federation Scout: ftl-layouts.mikehopley.org/img/federation/scout_2.png
  "federation-scout": {
    cols: 4,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 2, system: "shields" },
      { x: 0, y: 3, w: 1, h: 2, system: "doors" },
      { x: 1, y: 3, w: 2, h: 1, system: "weapons" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 0, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
    ],
  },
  // Federation Outrider: ftl-layouts.mikehopley.org/img/federation/outrider_2.png
  "federation-outrider": {
    cols: 4,
    rows: 5,
    rooms: [
      { x: 1, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 1, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 0, y: 3, w: 1, h: 2, system: "hacking" },
      { x: 1, y: 3, w: 2, h: 1, system: "shields" },
      { x: 3, y: 3, w: 1, h: 2, system: "oxygen" },
      { x: 1, y: 4, w: 2, h: 1, system: "engines" },
    ],
    marks: [
      { x: 2, y: 0, side: "s" },
      { x: 1, y: 2, side: "s" },
      { x: 2, y: 3, side: "s" },
      { x: 0, y: 4, side: "e" },
      { x: 2, y: 4, side: "e" },
    ],
  },
  // Federation Bomber: ftl-layouts.mikehopley.org/img/federation/bomber_2.png
  "federation-bomber": {
    cols: 8,
    rows: 7,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 2, system: "shields" },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: "doors" },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, system: "weapons" },
      { x: 3, y: 4, w: 2, h: 1, system: null },
      { x: 6, y: 4, w: 2, h: 2, system: "engines" },
      { x: 2, y: 5, w: 1, h: 2, system: "oxygen" },
      { x: 5, y: 5, w: 1, h: 2, system: "medbay" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 5, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 5, y: 5, side: "e" },
      { x: 5, y: 6, side: "e" },
    ],
  },
  // Federation Hacker: ftl-layouts.mikehopley.org/img/federation/hacker_2.png
  "federation-hacker": {
    cols: 8,
    rows: 7,
    rooms: [
      { x: 3, y: 0, w: 2, h: 1, system: "pilot" },
      { x: 3, y: 1, w: 2, h: 2, system: "weapons" },
      { x: 2, y: 3, w: 1, h: 2, system: null },
      { x: 3, y: 3, w: 2, h: 1, system: "hacking" },
      { x: 5, y: 3, w: 1, h: 2, system: null },
      { x: 0, y: 4, w: 2, h: 2, system: "engines" },
      { x: 3, y: 4, w: 2, h: 1, system: null },
      { x: 6, y: 4, w: 2, h: 2, system: "shields" },
      { x: 2, y: 5, w: 1, h: 2, system: "oxygen" },
      { x: 5, y: 5, w: 1, h: 2, system: "clonebay" },
    ],
    marks: [
      { x: 4, y: 0, side: "s" },
      { x: 3, y: 2, side: "s" },
      { x: 2, y: 3, side: "e" },
      { x: 4, y: 3, side: "e" },
      { x: 4, y: 3, side: "s" },
      { x: 1, y: 4, side: "e" },
      { x: 5, y: 4, side: "e" },
      { x: 1, y: 5, side: "e" },
      { x: 5, y: 5, side: "e" },
      { x: 5, y: 6, side: "e" },
    ],
  },
};

/** The traced interior for a class, the pirate one when it differs. */
export function enemyLayout(classId: string, pirate = false): EnemyLayout | undefined {
  return (pirate ? ENEMY_LAYOUTS[`${classId}:pirate`] : undefined) ?? ENEMY_LAYOUTS[classId];
}
