export type EventRow = {
  title: string;
  status: "mechanic" | "no-mechanic" | "blocked";
  facts: string[];
};

// Revision wikitext. A row is mechanic only when that text states a scrap amount, hull damage, crew gain or loss, a named weapon or augment reward, or a fleet delay.
export const EVENTS_3: EventRow[] = [
  { title: "Abandoned station", status: "mechanic", facts: ["Cloning a stored body can add a crewmember."] },
  { title: "Advanced Mastery", status: "no-mechanic", facts: [] },
  { title: "Artillery Mastery", status: "no-mechanic", facts: [] },
  { title: "Asteroid Fields", status: "no-mechanic", facts: [] },
  { title: "Auto-Ship Warning in Nebula", status: "no-mechanic", facts: [] },
  { title: "Auto-ship attacking small outpost", status: "no-mechanic", facts: [] },
  { title: "Auto-ship fight (Crystal)", status: "no-mechanic", facts: [] },
  { title: "Auto-ship fight near sun", status: "no-mechanic", facts: [] },
  { title: "Auto-ship near radar station", status: "mechanic", facts: ["Hacking the radar station delays the Rebel Fleet for 1 turn."] },
  { title: "Auto-ship near storage station in nebula", status: "no-mechanic", facts: [] },
  { title: "Auto-ship sits dormant", status: "no-mechanic", facts: [] },
  { title: "Automated Rebel Ship Close to Star", status: "no-mechanic", facts: [] },
  { title: "Battle Royale", status: "mechanic", facts: ["Your only crew member must deal the killing blow on the last enemy crew."] },
  { title: "Black Market Weapons Trader", status: "no-mechanic", facts: [] },
  { title: "Boarders: Humans (Abandoned)", status: "no-mechanic", facts: [] },
  { title: "Boarders: Humans jammed sensors", status: "no-mechanic", facts: [] },
  { title: "Boarders: rebels in nebula", status: "no-mechanic", facts: [] },
  { title: "Brutal Exchange Between Several Ships", status: "no-mechanic", facts: [] },
  { title: "Civilian FTL Haywire Escort", status: "no-mechanic", facts: [] },
  { title: "Civilian Ship Out Of FTL Fuel", status: "no-mechanic", facts: [] },
  { title: "Civilians fleeing from Lanius", status: "no-mechanic", facts: [] },
  { title: "Closed Mining Fields", status: "no-mechanic", facts: [] },
  { title: "Crew hiring station", status: "mechanic", facts: ["Hiring a crewmember costs 25-45 scrap, or 25-55 scrap.", "The hired crewmember joins your crew."] },
  { title: "Crystal (Weapon)", status: "no-mechanic", facts: [] },
  { title: "Crystal Burst Mark II", status: "no-mechanic", facts: [] },
  { title: "Crystal Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Crystal Ships", status: "no-mechanic", facts: [] },
  { title: "Crystal chat", status: "no-mechanic", facts: [] },
  { title: "Crystal scrap collector", status: "mechanic", facts: ["Paying 35 scrap can yield a Crystal crewmember, a Crystal Lockdown Bomb, or a Crystal Burst Mark II."] },
  { title: "Crystalline Border Guard", status: "no-mechanic", facts: [] },
  { title: "Crystalline Research Facility", status: "no-mechanic", facts: [] },
  { title: "Damaged Lanius Absorbing Jump Beacon", status: "no-mechanic", facts: [] },
  { title: "Damaged and Dilapidated Space Station", status: "no-mechanic", facts: [] },
  { title: "De-Activated Rebel Automated Scout", status: "no-mechanic", facts: [] },
  { title: "Default rewards (generic)", status: "no-mechanic", facts: [] },
  { title: "Destroyed Cargo Ship", status: "no-mechanic", facts: [] },
  { title: "Disintegration Ray", status: "mechanic", facts: ["One Anti-Bio Beam shot must kill 3 enemy crew."] },
  { title: "Distress Signal from Slug Ship Under Attack by the Lanius", status: "no-mechanic", facts: [] },
  { title: "Drifting Debris", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship Distress (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Easter Eggs and Trivia", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Rebel)", status: "no-mechanic", facts: [] },
  { title: "Empty nebula beacon", status: "no-mechanic", facts: [] },
  { title: "Enemy ships weaponry (tables)", status: "no-mechanic", facts: [] },
  { title: "Engi Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Engi Mantis Fight", status: "no-mechanic", facts: [] },
  { title: "Engi Ships", status: "no-mechanic", facts: [] },
  { title: "Engi attacked by Rebel", status: "no-mechanic", facts: [] },
  { title: "Engi fight", status: "no-mechanic", facts: [] },
  { title: "Engi ship under attack by Rebel", status: "no-mechanic", facts: [] },
  { title: "Escape Pod Floating Nearby", status: "no-mechanic", facts: [] },
  { title: "Escort civilian ship", status: "no-mechanic", facts: [] },
  { title: "Events commented out", status: "no-mechanic", facts: [] },
  { title: "FTL: Faster Than Light", status: "no-mechanic", facts: [] },
  { title: "Federation Fleet and Rebel Fleet Fight", status: "no-mechanic", facts: [] },
  { title: "Federation Terraforming Team C12", status: "no-mechanic", facts: [] },
  { title: "Fire chance", status: "no-mechanic", facts: [] },
  { title: "Flak (Weapon)", status: "no-mechanic", facts: [] },
  { title: "Free Weapon", status: "no-mechanic", facts: [] },
  { title: "Free scrap with resources (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Fuel Auto-ship", status: "no-mechanic", facts: [] },
  { title: "Fuel Mantis Attack", status: "no-mechanic", facts: [] },
  { title: "Fuel Wait Fail (Distress)", status: "no-mechanic", facts: [] },
  { title: "Galactic Federation", status: "no-mechanic", facts: [] },
  { title: "Givin' her all she's got, Captain!", status: "no-mechanic", facts: [] },
  { title: "Heavily Damaged Federation Ship Random Event", status: "no-mechanic", facts: [] },
  { title: "Home Sweet Home", status: "no-mechanic", facts: [] },
  { title: "Huge Rebel Shipyard", status: "no-mechanic", facts: [] },
  { title: "Human boarders in nebula", status: "no-mechanic", facts: [] },
  { title: "Human boarders near sun", status: "no-mechanic", facts: [] },
  { title: "Intelligent Lifeform on Planet", status: "no-mechanic", facts: [] },
  { title: "Intercept Comm Chatter from Mantis Ship", status: "no-mechanic", facts: [] },
  { title: "Ions (Weapon)", status: "no-mechanic", facts: [] },
  { title: "Lanius Absorbing Rebel Base", status: "no-mechanic", facts: [] },
  { title: "Lanius Distress Signal Blinks Out", status: "no-mechanic", facts: [] },
  { title: "Lanius Pirate fight", status: "no-mechanic", facts: [] },
  { title: "Lanius Scavenger Trader", status: "no-mechanic", facts: [] },
  { title: "Lanius Vessel in Rich Debris Field", status: "no-mechanic", facts: [] },
  { title: "Lanius attacking Mantis", status: "no-mechanic", facts: [] },
  { title: "Lanius attacking Slug", status: "no-mechanic", facts: [] },
  { title: "Lanius empty beacon distress", status: "no-mechanic", facts: [] },
  { title: "Lanius fight", status: "no-mechanic", facts: [] },
  { title: "Lanius fight near pulsar", status: "no-mechanic", facts: [] },
  { title: "Lanius powered-down ship", status: "no-mechanic", facts: [] },
  { title: "Lanius ship absorbing rebel base", status: "mechanic", facts: ["Persuading the Lanius delays the Rebel Fleet for 1 turn."] },
  { title: "Lanius ship attacking civilian", status: "no-mechanic", facts: [] },
  { title: "Lanius ship salvager", status: "no-mechanic", facts: [] },
  { title: "Lanius with docked science craft", status: "no-mechanic", facts: [] },
  { title: "Laser Charger (S)", status: "no-mechanic", facts: [] },
  { title: "Legendary thief KazaaakplethKilik", status: "mechanic", facts: ["KazaaakplethKilik can join as a max-skilled Mantis crewmember named Kazaaak.", "That outcome also grants the Mantis Pheromones augment."] },
  { title: "Lumbering Zoltan Freighter", status: "no-mechanic", facts: [] },
  { title: "Manpower", status: "no-mechanic", facts: [] },
  { title: "Mantis Attacking Smaller Crystal Ship", status: "no-mechanic", facts: [] },
  { title: "Mantis Fight", status: "no-mechanic", facts: [] },
  { title: "Mantis Homeworlds", status: "no-mechanic", facts: [] },
  { title: "Mantis Ship Doesn't See You", status: "no-mechanic", facts: [] },
  { title: "Mantis Store", status: "no-mechanic", facts: [] },
  { title: "Mantis attacking Crystal ship", status: "no-mechanic", facts: [] },
  { title: "Mantis fight (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Mantis fight in nebula (Slug)", status: "no-mechanic", facts: [] },
  { title: "Mantis in Nebula", status: "no-mechanic", facts: [] },
  { title: "Mantis ship attacking civilian", status: "no-mechanic", facts: [] },
  { title: "Master of Patience", status: "mechanic", facts: ["Destroy an enemy ship with only the Artillery Beam and take no hull damage."] },
  { title: "Merchant Fuel Ship", status: "no-mechanic", facts: [] },
  { title: "Merchant with Conspicuous Markings", status: "no-mechanic", facts: [] },
  { title: "Music", status: "no-mechanic", facts: [] },
  { title: "Nebula Store", status: "no-mechanic", facts: [] },
  { title: "Nebula wreckage", status: "mechanic", facts: ["Searching the wreck can deal 5 hull damage and 1 damage with fire to a random room.", "A rescued survivor can join as a crewmember."] },
  { title: "No fuel: Engi ship repair", status: "mechanic", facts: ["One exchange loses 10-20 scrap and adds 4-6 fuel."] },
  { title: "No fuel: Rebel fleet delay", status: "mechanic", facts: ["Rebel Fleet pursuit is delayed for 1 jump."] },
  { title: "No fuel: drifting debris", status: "mechanic", facts: ["Paying the ransom costs 25-40 scrap.", "Refusing the ransom loses a crewmember."] },
  { title: "No fuel: fuel trader (distress)", status: "no-mechanic", facts: [] },
  { title: "No fuel: prepare to dock", status: "no-mechanic", facts: [] },
  { title: "No fuel: wait fail (distress off)", status: "no-mechanic", facts: [] },
  { title: "Orbiting refueling platform", status: "no-mechanic", facts: [] },
  { title: "Pirate Bribing You for Unknown Ship", status: "no-mechanic", facts: [] },
  { title: "Pirate Engine Hack", status: "no-mechanic", facts: [] },
  { title: "Pirate Salesman", status: "no-mechanic", facts: [] },
  { title: "Pirate Store", status: "no-mechanic", facts: [] },
  { title: "Pirate attacking Crystal", status: "no-mechanic", facts: [] },
  { title: "Pirate attacking civilian distress", status: "no-mechanic", facts: [] },
  { title: "Pirate fight (Engi)", status: "no-mechanic", facts: [] },
  { title: "Pirate fight choice in nebula", status: "no-mechanic", facts: [] },
  { title: "Pirate fight in nebula choice", status: "no-mechanic", facts: [] },
  { title: "Pirate ship attacking civilian", status: "no-mechanic", facts: [] },
  { title: "Pirate ship selling drones", status: "mechanic", facts: ["Five drone parts cost 25 scrap; a drone schematic costs 25-35 scrap.", "Drone Control upgrades cost 15-20, 25-33, or 50-65 scrap.", "Leaving without a purchase deals 3 hull damage."] },
  { title: "Pirate smuggler ship", status: "no-mechanic", facts: [] },
  { title: "Plasma Storm Automated Scout", status: "no-mechanic", facts: [] },
  { title: "Plasma storm Auto-ship", status: "no-mechanic", facts: [] },
  { title: "Powered-Down Lanius Vessel", status: "no-mechanic", facts: [] },
  { title: "Races", status: "no-mechanic", facts: [] },
  { title: "Races/Engi", status: "no-mechanic", facts: [] },
  { title: "Races/Rockman", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Crew", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Lanius", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Zoltan", status: "no-mechanic", facts: [] },
  { title: "Rebel AI Scout Carrying Shield Virus", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-Ship Fight", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-ship carrying shield virus", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-ship near storage vessel", status: "no-mechanic", facts: [] },
  { title: "Rebel Automated Ship Near Storage Vessel", status: "no-mechanic", facts: [] },
  { title: "Rebel Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Rebel Fleet Fight", status: "no-mechanic", facts: [] },
  { title: "Rebel Ship Nearby", status: "no-mechanic", facts: [] },
  { title: "Rebel Stronghold", status: "no-mechanic", facts: [] },
  { title: "Rebel attacking Crystal ship", status: "no-mechanic", facts: [] },
  { title: "Rebel checkpoint", status: "mechanic", facts: ["Bribing the checkpoint costs 10-15 scrap."] },
  { title: "Rebel fight (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Rebel fight chance", status: "no-mechanic", facts: [] },
  { title: "Rebel fight in nebula choice", status: "no-mechanic", facts: [] },
  { title: "Rebel in Nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel ship attacking civilians in Last Stand", status: "no-mechanic", facts: [] },
  { title: "Rebel shipyard", status: "mechanic", facts: ["Salvaging the unfinished flagship delays the Rebel Fleet for 2 turns."] },
  { title: "Red Giant", status: "no-mechanic", facts: [] },
  { title: "Refueling Platform Garbled Broadcast", status: "no-mechanic", facts: [] },
  { title: "Refugee (Pirate)", status: "no-mechanic", facts: [] },
  { title: "Refugee Ship with Communications Down", status: "no-mechanic", facts: [] },
  { title: "Refugee distress (Slug)", status: "no-mechanic", facts: [] },
  { title: "Repair Station", status: "no-mechanic", facts: [] },
  { title: "Resources", status: "no-mechanic", facts: [] },
  { title: "Rock Bride Transport", status: "no-mechanic", facts: [] },
  { title: "Rock Fight", status: "no-mechanic", facts: [] },
  { title: "Rock Homeworlds", status: "no-mechanic", facts: [] },
  { title: "Rock Pirate in Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Rock War Vessel Encounter", status: "no-mechanic", facts: [] },
  { title: "Rock fight choice", status: "no-mechanic", facts: [] },
  { title: "Rock pirates fight", status: "no-mechanic", facts: [] },
  { title: "Rock ship in uncharted nebula plasma storm", status: "no-mechanic", facts: [] },
  { title: "Scrap Hoarder", status: "mechanic", facts: ["Have at least 600 scrap in storage at one time."] },
  { title: "Selling Drone Parts Station", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Advanced Mastery", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Battle Royale", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Disintegration Ray", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Home Sweet Home", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Manpower", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Robotic Warfare", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Tactical Approach", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Tough Little Ship", status: "no-mechanic", facts: [] },
  { title: "Ship Damaged Near Sun", status: "no-mechanic", facts: [] },
  { title: "Single Life Form on Moon", status: "no-mechanic", facts: [] },
  { title: "Slug Boarding Rock Freighter", status: "no-mechanic", facts: [] },
  { title: "Slug Disable Door System", status: "no-mechanic", facts: [] },
  { title: "Slug Fight in Nebula", status: "no-mechanic", facts: [] },
  { title: "Slug Oxygen Malfunction", status: "no-mechanic", facts: [] },
  { title: "Slug Rebel fight", status: "no-mechanic", facts: [] },
  { title: "Slug Store", status: "no-mechanic", facts: [] },
  { title: "Slug and Rock Standoff in Nebula", status: "no-mechanic", facts: [] },
  { title: "Slug empty nebula beacon", status: "no-mechanic", facts: [] },
  { title: "Slug hacker (choice)", status: "mechanic", facts: ["Paying 35 scrap makes the Slug ship leave."] },
  { title: "Slug medical hacker", status: "no-mechanic", facts: [] },
  { title: "Slug sabotage medical unit", status: "no-mechanic", facts: [] },
  { title: "Slugs Detected Radiation From Your Medical Unit", status: "no-mechanic", facts: [] },
  { title: "Smouldering Engi Research Station", status: "no-mechanic", facts: [] },
  { title: "Specialty Work on Your Ship", status: "no-mechanic", facts: [] },
  { title: "Store (Crystal)", status: "no-mechanic", facts: [] },
  { title: "Store (Pirate)", status: "no-mechanic", facts: [] },
  { title: "Store (event)", status: "no-mechanic", facts: [] },
  { title: "Store in uncharted nebula", status: "no-mechanic", facts: [] },
  { title: "Take no prisoners!", status: "mechanic", facts: ["Kill the crew of 20 ships by the end of sector 6 without destroying those ships."] },
  { title: "The Basilisk", status: "no-mechanic", facts: [] },
  { title: "The Gila Monster", status: "no-mechanic", facts: [] },
  { title: "The Theseus", status: "no-mechanic", facts: [] },
  { title: "Trade: fuel for drone parts", status: "no-mechanic", facts: [] },
  { title: "Trade: selling drone parts station", status: "no-mechanic", facts: [] },
  { title: "Trade resources in nebula", status: "no-mechanic", facts: [] },
  { title: "Trap Distress Beacon", status: "no-mechanic", facts: [] },
  { title: "Two smashed Engi ships", status: "no-mechanic", facts: [] },
  { title: "We're in position!", status: "no-mechanic", facts: [] },
  { title: "Weapons (tables)", status: "no-mechanic", facts: [] },
  { title: "Zoltan \"Wise Man\"", status: "no-mechanic", facts: [] },
  { title: "Zoltan Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Zoltan Follows Mantis", status: "no-mechanic", facts: [] },
  { title: "Zoltan Mantis fight", status: "no-mechanic", facts: [] },
  { title: "Zoltan Rock fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Zoltan Ships", status: "no-mechanic", facts: [] },
  { title: "Zoltan free augment", status: "no-mechanic", facts: [] },
  { title: "Zoltan quest primitives", status: "no-mechanic", facts: [] },
  { title: "Zoltan ship follows Mantis ship", status: "no-mechanic", facts: [] },
];
