export type EventRow = {
  title: string;
  status: "mechanic" | "no-mechanic" | "blocked";
  facts: string[];
};

// Quoted from ftl.fandom.com revision wikitext. No reward is inferred from another page.
export const EVENTS_0: EventRow[] = [
  { title: "ASB", status: "no-mechanic", facts: [] },
  { title: "Achievement", status: "no-mechanic", facts: [] },
  { title: "Ancestry", status: "mechanic", facts: ["Acquire the Damaged Stasis Pod augment.", "Once the pod is fixed, Crystal crewmember Ruwen joins the ship."] },
  { title: "Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Asteroid Mining Colony", status: "no-mechanic", facts: [] },
  { title: "Auto-ship attacking civilian", status: "mechanic", facts: ["Destroying the auto-ship gives low scrap with resources."] },
  { title: "Auto-ship carrying shield virus", status: "mechanic", facts: ["Shields are halved, or Hacking goes offline if used to counter the virus.", "Destroying the ship gives medium scrap with resources."] },
  { title: "Auto-ship fight in asteroid field", status: "mechanic", facts: ["Destroying the ship gives medium scrap with resources."] },
  { title: "Auto-ship in asteroid belt", status: "no-mechanic", facts: [] },
  { title: "Auto-ship near sensor station", status: "mechanic", facts: ["Low scrap, and the current sector map is revealed."] },
  { title: "Auto-ship near storage vessel", status: "no-mechanic", facts: [] },
  { title: "Auto-ship warning", status: "mechanic", facts: ["If the scout escapes, Rebel Fleet pursuit is doubled.", "Destroying it gives low scrap with resources."] },
  { title: "Automated refueling ship", status: "no-mechanic", facts: [] },
  { title: "Battlefield wreckage", status: "mechanic", facts: ["Medium resources with some scrap: fuel 2-4, missiles 2-4, 1 drone part.", "High resources with some scrap: fuel 3-6, missiles 4-8, drone parts 1-2.", "A prototype weapon comes with low scrap."] },
  { title: "Black Raven", status: "no-mechanic", facts: [] },
  { title: "Boarders: Humans (Pirate)", status: "mechanic", facts: ["3-5 human boarders beam aboard."] },
  { title: "Boarders: Humans near sun", status: "mechanic", facts: ["2-4 human boarders beam aboard."] },
  { title: "Boarders in Nebula", status: "no-mechanic", facts: [] },
  { title: "Bump Hulls with Mantis Ship", status: "no-mechanic", facts: [] },
  { title: "Civilian Sector", status: "no-mechanic", facts: [] },
  { title: "Civilian Vessel Under Fire from a Lanius Ship", status: "no-mechanic", facts: [] },
  { title: "Civilized Trader", status: "no-mechanic", facts: [] },
  { title: "Confused Mantis", status: "mechanic", facts: ["Approaching him can lose a crewmember; Clone Bay revives them.", "Mantis crew yields low scrap; calming him yields medium scrap.", "Returning Robert Smith home adds that Mantis crewmember."] },
  { title: "Crew races", status: "no-mechanic", facts: [] },
  { title: "Crystal Auto-ship fight", status: "no-mechanic", facts: [] },
  { title: "Crystal Civilian Question", status: "no-mechanic", facts: [] },
  { title: "Crystal Fight", status: "no-mechanic", facts: [] },
  { title: "Crystal Store", status: "no-mechanic", facts: [] },
  { title: "Crystal fight choice", status: "no-mechanic", facts: [] },
  { title: "Crystal sector", status: "no-mechanic", facts: [] },
  { title: "Crystalline Cache", status: "no-mechanic", facts: [] },
  { title: "Crystalline Ship Carrying Humans", status: "no-mechanic", facts: [] },
  { title: "Damaged Space Station", status: "no-mechanic", facts: [] },
  { title: "Dangerous-looking ship", status: "no-mechanic", facts: [] },
  { title: "Deactivated Auto-ship", status: "mechanic", facts: ["Low scrap, sometimes with the sector map revealed.", "If it reactivates and is destroyed, medium scrap with resources."] },
  { title: "Defense Drones Don't Do D'anything!", status: "no-mechanic", facts: [] },
  { title: "Diplomatic Immunity", status: "no-mechanic", facts: [] },
  { title: "Distress: Civilian Ship Chased by Pirate", status: "no-mechanic", facts: [] },
  { title: "Distress Signals", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship Distress", status: "no-mechanic", facts: [] },
  { title: "Drone Schematic", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Civilian)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Last Stand)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Rock)", status: "no-mechanic", facts: [] },
  { title: "Empty nebula beacon (Slug)", status: "no-mechanic", facts: [] },
  { title: "Engi Colony Hiding", status: "no-mechanic", facts: [] },
  { title: "Engi Fleet Discussion", status: "no-mechanic", facts: [] },
  { title: "Engi Pirate Fight", status: "no-mechanic", facts: [] },
  { title: "Engi Store", status: "no-mechanic", facts: [] },
  { title: "Engi cache", status: "mechanic", facts: ["Spend 2 missiles to delay the Rebel Fleet for 2 turns.", "Or take a drone schematic with medium scrap."] },
  { title: "Engi fight (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Engi smashed ships", status: "mechanic", facts: ["A random amount of resources with some scrap."] },
  { title: "Escape pod", status: "mechanic", facts: ["1 Mantis boarder beams aboard and you lose a crewmember; Clone Bay revives them.", "Or gain a Mantis crewmember.", "Or gain a Human crewmember."] },
  { title: "Escort civilians", status: "no-mechanic", facts: [] },
  { title: "Exit Beacons", status: "no-mechanic", facts: [] },
  { title: "FTL haywire civilian ship escort", status: "no-mechanic", facts: [] },
  { title: "Federation Science-Craft Docked with Lanius", status: "no-mechanic", facts: [] },
  { title: "Federation base assist", status: "no-mechanic", facts: [] },
  { title: "Fire on Small Research Station", status: "no-mechanic", facts: [] },
  { title: "Forward Scout of Rebel Fleet", status: "no-mechanic", facts: [] },
  { title: "Free scrap with resources", status: "mechanic", facts: ["Medium scrap with resources."] },
  { title: "Friendly Refugee", status: "no-mechanic", facts: [] },
  { title: "Fuel Automated Rebel Scout", status: "no-mechanic", facts: [] },
  { title: "Fuel Trader", status: "no-mechanic", facts: [] },
  { title: "Fuel for Drone", status: "no-mechanic", facts: [] },
  { title: "Game Bugs", status: "no-mechanic", facts: [] },
  { title: "Guides and Tips", status: "no-mechanic", facts: [] },
  { title: "Hidden Crystal Worlds", status: "no-mechanic", facts: [] },
  { title: "Hostile Lanius Ship", status: "no-mechanic", facts: [] },
  { title: "Human Boarders", status: "no-mechanic", facts: [] },
  { title: "Human boarders in pirate sector", status: "no-mechanic", facts: [] },
  { title: "I hardly lifted a finger", status: "no-mechanic", facts: [] },
  { title: "Intelligent life form on planet", status: "no-mechanic", facts: [] },
  { title: "Ion Storm", status: "no-mechanic", facts: [] },
  { title: "Is it warm in here?", status: "no-mechanic", facts: [] },
  { title: "Lanius Absorbing Rebel Scout", status: "no-mechanic", facts: [] },
  { title: "Lanius Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Lanius Rebel fight", status: "no-mechanic", facts: [] },
  { title: "Lanius Ship Mining Mantis Ship's Hull", status: "no-mechanic", facts: [] },
  { title: "Lanius absorbing Auto-ship", status: "no-mechanic", facts: [] },
  { title: "Lanius attacking Mantis ship", status: "no-mechanic", facts: [] },
  { title: "Lanius attacking Slug ship", status: "no-mechanic", facts: [] },
  { title: "Lanius empty distress beacon", status: "no-mechanic", facts: [] },
  { title: "Lanius fight distress", status: "no-mechanic", facts: [] },
  { title: "Lanius fight with friendly ASB support", status: "mechanic", facts: ["Destroying the ship gives medium scrap with resources.", "Killing the crew gives high scrap with resources.", "The defense team may give 8 hull repairs."] },
  { title: "Lanius salvaging", status: "no-mechanic", facts: [] },
  { title: "Lanius ship attacking Mantis", status: "mechanic", facts: ["Medium scrap with resources.", "Grateful Mantis may give medium missiles (2-4) and scrap."] },
  { title: "Lanius ship attacking civilian distress", status: "mechanic", facts: ["Destroying the Lanius ship gives medium scrap with resources.", "Killing its crew gives high scrap with resources."] },
  { title: "Lanius trader", status: "mechanic", facts: ["Trade 3-7 fuel for 15-30 scrap, 3-7 missiles for 20-40, or 3-7 drone parts for 20-40.", "Lanius crew: 3-7 fuel for 20-35 scrap, or 3-7 missiles or drone parts for 25-50 scrap."] },
  { title: "Large Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Lasers (Weapon)", status: "no-mechanic", facts: [] },
  { title: "Lone Lanius ship", status: "no-mechanic", facts: [] },
  { title: "Main Page", status: "no-mechanic", facts: [] },
  { title: "Mantis Attacking Civilian", status: "no-mechanic", facts: [] },
  { title: "Mantis Boarders", status: "no-mechanic", facts: [] },
  { title: "Mantis Fight with Boarders", status: "no-mechanic", facts: [] },
  { title: "Mantis Hunting Slugs", status: "no-mechanic", facts: [] },
  { title: "Mantis Ship Rock Body Parts", status: "no-mechanic", facts: [] },
  { title: "Mantis Venture Close to Sun", status: "no-mechanic", facts: [] },
  { title: "Mantis attacking Slug ship", status: "no-mechanic", facts: [] },
  { title: "Mantis fight choice", status: "no-mechanic", facts: [] },
  { title: "Mantis fight in nebula choice", status: "no-mechanic", facts: [] },
  { title: "Mantis outcasts", status: "mechanic", facts: ["2-3 Mantis boarders beam aboard."] },
  { title: "Mantis ship comm chatter", status: "no-mechanic", facts: [] },
  { title: "Mercenary", status: "no-mechanic", facts: [] },
  { title: "Merchant Ship Docked with Lanius Transport", status: "no-mechanic", facts: [] },
  { title: "Meta:Event Conventions", status: "no-mechanic", facts: [] },
  { title: "Nebula Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Nebula Trader", status: "no-mechanic", facts: [] },
  { title: "No Escape", status: "no-mechanic", facts: [] },
  { title: "No fuel: Mantis fight", status: "mechanic", facts: ["Destroying the ship gives medium fuel (2-4) and scrap.", "Killing the crew gives high fuel (3-6) and scrap."] },
  { title: "No fuel: Slug fuel depot", status: "mechanic", facts: ["Buy 5 fuel for 50 scrap, or 10 fuel for 95 scrap.", "Destroying the ship gives medium fuel (2-4) and scrap.", "Killing the crew gives high fuel (3-6) and scrap."] },
  { title: "No fuel: explore the system", status: "mechanic", facts: ["Pay 20 scrap for 5 fuel, 10 scrap for 2 fuel, or 5 scrap for 1 fuel.", "Salvage: 3-6 fuel, 2-4 missiles and scrap, 1 drone part and scrap, or 2-4 fuel and scrap.", "One outcome deals 5 hull damage, 1 system damage, and fire in a random room."] },
  { title: "No fuel: fuel trader (distress off)", status: "no-mechanic", facts: [] },
  { title: "No fuel: refugee trading", status: "mechanic", facts: ["Low fuel (1-3), or trade 10 scrap for 3 fuel.", "A better trade gives 6 fuel for 10 scrap.", "Trade 1 missile for 5-7 fuel; a surrender gives medium fuel (2-4) and scrap."] },
  { title: "No fuel: wait fail (distress on)", status: "no-mechanic", facts: [] },
  { title: "Patches", status: "no-mechanic", facts: [] },
  { title: "Pirate Charges Crystalline Transport", status: "no-mechanic", facts: [] },
  { title: "Pirate Fight", status: "no-mechanic", facts: [] },
  { title: "Pirate Ship firing on Docked Ships", status: "no-mechanic", facts: [] },
  { title: "Pirate Toll", status: "no-mechanic", facts: [] },
  { title: "Pirate attacking Crystal ship", status: "no-mechanic", facts: [] },
  { title: "Pirate blockade", status: "no-mechanic", facts: [] },
  { title: "Pirate fight (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Pirate fight distress", status: "no-mechanic", facts: [] },
  { title: "Pirate fight near pulsar", status: "no-mechanic", facts: [] },
  { title: "Pirate ship attacking civilian (Lanius)", status: "mechanic", facts: ["Destroying the pirate ship gives medium scrap with resources.", "Killing the crew gives high scrap with resources."] },
  { title: "Pirate ship selling unknown weapon", status: "no-mechanic", facts: [] },
  { title: "Pirate trap", status: "no-mechanic", facts: [] },
  { title: "Plasma Storm Events", status: "no-mechanic", facts: [] },
  { title: "Plasma storm pirate ships", status: "no-mechanic", facts: [] },
  { title: "Prepare to Dock", status: "no-mechanic", facts: [] },
  { title: "Races/Crew", status: "no-mechanic", facts: [] },
  { title: "Races/Human", status: "no-mechanic", facts: [] },
  { title: "Races/Slug", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Crystal", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Mantis", status: "no-mechanic", facts: [] },
  { title: "Random Event", status: "no-mechanic", facts: [] },
  { title: "Rebel Assistant Hails", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-Ship Sits Dormant", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-ship in asteroid belt", status: "no-mechanic", facts: [] },
  { title: "Rebel Automated-Scout in Asteroid Belt", status: "no-mechanic", facts: [] },
  { title: "Rebel Boarders in Nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel Fight", status: "no-mechanic", facts: [] },
  { title: "Rebel Scout Attacking Refueling Outpost", status: "no-mechanic", facts: [] },
  { title: "Rebel Ship With Boarders", status: "no-mechanic", facts: [] },
  { title: "Rebel Transport", status: "no-mechanic", facts: [] },
  { title: "Rebel attacking Federation loyalists", status: "no-mechanic", facts: [] },
  { title: "Rebel defector", status: "mechanic", facts: ["A Human crewmember may join.", "3 hull damage; fleet pursuit can double, with 1 engine or piloting damage.", "You can lose a crewmember or face 1-2 human boarders; Clone Bay revives a loss."] },
  { title: "Rebel fight (Slug)", status: "no-mechanic", facts: [] },
  { title: "Rebel fight chance in nebula", status: "mechanic", facts: ["Getting lost doubles Rebel Fleet pursuit."] },
  { title: "Rebel fight in plasma storm", status: "mechanic", facts: ["Outside a nebula in a Slug sector, fleet pursuit is the full amount instead of 80%."] },
  { title: "Rebel in Plasma Storm", status: "no-mechanic", facts: [] },
  { title: "Rebel ship attacking refueling outpost", status: "mechanic", facts: ["Destroyed ship: medium scrap with resources. Dead crew: high scrap with resources.", "The outpost can also give medium fuel (2-4) and scrap."] },
  { title: "Rebel supplying civilians", status: "no-mechanic", facts: [] },
  { title: "Red Giant Events", status: "no-mechanic", facts: [] },
  { title: "Refueling platform", status: "mechanic", facts: ["Pay 5-10 scrap for 5 fuel, or take 3-5 or 5 fuel without paying.", "An explosion deals 3 hull damage, 3 fire damage to engines, and loses 3 fuel.", "An ambush deals 3 hull and 3 engine damage, plus 2-4 boarders."] },
  { title: "Refugee (Slug)", status: "no-mechanic", facts: [] },
  { title: "Refugee comms down", status: "mechanic", facts: ["Lose a crewmember (Clone Bay revives them) or gain a crewmember.", "Abandoned cargo gives medium missiles (2-4) and scrap.", "2-4 human boarders can beam aboard."] },
  { title: "Refugee distress (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Repair Station in Last Stand", status: "no-mechanic", facts: [] },
  { title: "Robotic Warfare", status: "no-mechanic", facts: [] },
  { title: "Rock Controlled Sector", status: "no-mechanic", facts: [] },
  { title: "Rock Fight With Boarders", status: "no-mechanic", facts: [] },
  { title: "Rock Live Mine", status: "no-mechanic", facts: [] },
  { title: "Rock Ship Being Mined by Lanius", status: "no-mechanic", facts: [] },
  { title: "Rock and Slug standoff", status: "mechanic", facts: ["Pay 10-15 scrap; destroying the Rock ship gives low scrap, dead crew medium scrap.", "A reactor explosion deals 5 hull damage and 1 damage to each of 2 systems.", "The Slugs may upgrade your reactor for free or for 10-15 scrap."] },
  { title: "Rock fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Rock pirates fight in asteroid field", status: "no-mechanic", facts: [] },
  { title: "Rockman", status: "no-mechanic", facts: [] },
  { title: "Sell drone parts for scrap", status: "mechanic", facts: ["Sell 3 drone parts for 12 scrap.", "Sell 6 drone parts for 24 scrap.", "Sell 12 drone parts for 48 scrap."] },
  { title: "Selling Missiles Station", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Ancestry", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Bird of Prey", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Disintigration Ray", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/I hardly lifted a finger", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Master of Patience", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Scrap Hoarder", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Take no prisoners!", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/We're in position!", status: "no-mechanic", facts: [] },
  { title: "Ship Scrap Comparison", status: "no-mechanic", facts: [] },
  { title: "Slaver (friendly)", status: "mechanic", facts: ["Buy one crewmember for 25-45 scrap.", "A teleporter raid can also free a crewmember."] },
  { title: "Slug Captain Invites You to a Drink", status: "no-mechanic", facts: [] },
  { title: "Slug Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Slug Mantis fight", status: "no-mechanic", facts: [] },
  { title: "Slug Pirate", status: "no-mechanic", facts: [] },
  { title: "Slug Repair Station", status: "no-mechanic", facts: [] },
  { title: "Slug Transport with Military Escort", status: "no-mechanic", facts: [] },
  { title: "Slug boarding Rock ship", status: "no-mechanic", facts: [] },
  { title: "Slug fake store", status: "no-mechanic", facts: [] },
  { title: "Slug hacker (doors)", status: "mechanic", facts: ["Destroying the ship gives medium scrap with resources.", "Killing the crew gives high scrap with resources."] },
  { title: "Slug moons question", status: "mechanic", facts: ["A wrong answer loses 35 scrap, 2-4 fuel, and 1-2 drone parts.", "A correct answer gains a Slug crewmember."] },
  { title: "Slug ship boarding Rock ship", status: "mechanic", facts: ["Medium scrap with resources from the Slug ship, and sometimes again from the Rock ship."] },
  { title: "Small Asteroid Belt Distress Beacon", status: "no-mechanic", facts: [] },
  { title: "Smuggler", status: "no-mechanic", facts: [] },
  { title: "Stasis chamber", status: "no-mechanic", facts: [] },
  { title: "Store (Engi)", status: "no-mechanic", facts: [] },
  { title: "Store (Rebel)", status: "no-mechanic", facts: [] },
  { title: "Store beacon", status: "no-mechanic", facts: [] },
  { title: "Stores", status: "no-mechanic", facts: [] },
  { title: "Terraforming federation team C12", status: "no-mechanic", facts: [] },
  { title: "The Black Raven", status: "mechanic", facts: ["1-2 Slug boarders can beam aboard.", "A mind duel or surrender gives a weapon with high scrap.", "Destroying the ship gives medium scrap; killing the crew gives high scrap."] },
  { title: "The Last Stand", status: "no-mechanic", facts: [] },
  { title: "The United Federation", status: "no-mechanic", facts: [] },
  { title: "Trade: sell drone parts for scrap", status: "no-mechanic", facts: [] },
  { title: "Trade: selling missiles station", status: "no-mechanic", facts: [] },
  { title: "Trade scrap for upgrades", status: "mechanic", facts: ["Oxygen level 2 costs 15-20 scrap; level 3 costs 25-40 scrap.", "Piloting or doors level 2 costs 8-15 scrap; level 3 costs 25-40 scrap.", "Sensors level 2 costs 10-20 scrap; level 3 costs 35-45. Reactor upgrade costs 15-25 scrap."] },
  { title: "Two Pirate Ships in Nebula", status: "no-mechanic", facts: [] },
  { title: "Uncharted Nebula", status: "no-mechanic", facts: [] },
  { title: "Weak and Hungry Human Intruders", status: "no-mechanic", facts: [] },
  { title: "Weapons trader", status: "no-mechanic", facts: [] },
  { title: "Zoltan Academy Free Augment", status: "no-mechanic", facts: [] },
  { title: "Zoltan Engi fight", status: "no-mechanic", facts: [] },
  { title: "Zoltan Great Eye", status: "mechanic", facts: ["One outcome loses a crewmember; Clone Bay does not revive them.", "One outcome gives high scrap.", "One outcome gives the Healing Burst weapon."] },
  { title: "Zoltan Mantis fight with boarders", status: "no-mechanic", facts: [] },
  { title: "Zoltan Security Checkpoint", status: "no-mechanic", facts: [] },
  { title: "Zoltan Store", status: "no-mechanic", facts: [] },
  { title: "Zoltan free map", status: "no-mechanic", facts: [] },
  { title: "Zoltan retake the ship", status: "mechanic", facts: ["Destroying the ship gives medium scrap with resources.", "Hire the Zoltan for 40 scrap.", "Killing the pirate crew gives an augmentation with high scrap."] },
  { title: "Zoltan wise man", status: "mechanic", facts: ["Destroying the summoned ship gives low scrap with resources.", "Killing its crew gives medium scrap with resources.", "If the Zoltan then implodes, high scrap with resources."] },
];
