export type EventRow = {
  title: string;
  status: "mechanic" | "no-mechanic" | "blocked";
  facts: string[];
};

export const EVENTS_1: EventRow[] = [
  { title: "Abandoned Sector", status: "mechanic", facts: ["Crew of the listed races can be purchased or received as a crew-kill reward."] },
  { title: "Adv. FTL Navigation", status: "mechanic", facts: ["Purchase price is 50 scrap."] },
  { title: "Ancient Device", status: "mechanic", facts: ["Scrapping the device yields high scrap.", "Reactivating it grants the Crystal Vengeance augment, medium fuel and scrap, and 10 repairs."] },
  { title: "Asteroid Field Events", status: "no-mechanic", facts: [] },
  { title: "Asteroid belt distress", status: "mechanic", facts: ["Shielding them can deal 1 hull damage and a fire, for high fuel and scrap.", "A failed escort can deal 4 hull damage for low scrap.", "You can receive a crewmember, or a weapon with medium scrap."] },
  { title: "Auto-ship attacking outpost", status: "mechanic", facts: ["Destroying the auto-ship yields low scrap with resources.", "The outpost then gives medium scrap with resources."] },
  { title: "Auto-ship close to star", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Auto-ship fight in nebula", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Auto-ship in nebula", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Auto-ship near small space-station", status: "mechanic", facts: ["You receive medium scrap."] },
  { title: "Auto-ship near sun", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Automated Re-Fueling Ship", status: "mechanic", facts: ["Fuel costs 20 scrap for 5, or 8 scrap for 2.", "You can receive medium fuel and scrap."] },
  { title: "Avast, ye scurvy dogs!", status: "mechanic", facts: ["Kill 5 enemy crew with the Mantis Cruiser without hull damage or losing a crewmember."] },
  { title: "Bird of Prey", status: "mechanic", facts: ["The cloak must start before any hull damage and last until the fight ends."] },
  { title: "Blue Options", status: "no-mechanic", facts: [] },
  { title: "Boarders: Humans in nebula", status: "no-mechanic", facts: [] },
  { title: "Boarders: Mantis", status: "no-mechanic", facts: [] },
  { title: "Boarders in Plasma Storm", status: "mechanic", facts: ["You receive medium scrap with resources as 3-4 human boarders beam aboard."] },
  { title: "Capture the ship", status: "mechanic", facts: ["One path deals 15 hull damage, a system hit, a fire, and a breach.", "You can receive a weapon with high scrap."] },
  { title: "Civilian Ship Chased by Pirate", status: "mechanic", facts: ["Rewards include medium or high scrap with resources."] },
  { title: "Civilian ship chased by Pirate (distress)", status: "mechanic", facts: ["Rewards include medium or high scrap with resources."] },
  { title: "Clash of the Titans", status: "no-mechanic", facts: [] },
  { title: "Crew Member", status: "mechanic", facts: ["Receiving a 9th crewmember forces you to dismiss one crewmember."] },
  { title: "Crewmembers", status: "mechanic", facts: ["Receiving a 9th crewmember forces you to dismiss one crewmember."] },
  { title: "Crystal Auto Fight", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Crystal Collector of Alien Artifacts", status: "mechanic", facts: ["You can offer 35 scrap.", "You can receive a Crystal crewmember.", "You can receive a Crystal Lockdown Bomb."] },
  { title: "Crystal Lockdown ability", status: "no-mechanic", facts: [] },
  { title: "Crystal Vengeance", status: "mechanic", facts: ["Sell price is 40 scrap."] },
  { title: "Crystal fight with surrender offer (Human crew)", status: "mechanic", facts: ["You can receive a Human crewmember while the fight continues.", "You can receive medium scrap with resources."] },
  { title: "Crystal ship attacking Federation loyalists", status: "mechanic", facts: ["Outcomes include medium or high scrap with resources.", "You can receive a crewmember and low scrap with resources."] },
  { title: "Crystalline Man Buried", status: "mechanic", facts: ["Leaving a crewmember behind loses that crew for medium fuel and scrap.", "Waiting longer loses a crewmember for high fuel and scrap."] },
  { title: "Crystalline Ship Engaged with Rebel", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Damaged Stasis Pod", status: "mechanic", facts: ["Sell price is 15 scrap."] },
  { title: "Dangerous Looking Ship", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can pay 35 scrap for them to leave."] },
  { title: "Deactivated Rebel Automated Scout", status: "mechanic", facts: ["You can receive low scrap with resources and a revealed sector map.", "You can receive medium scrap with resources, or low scrap."] },
  { title: "Dense Asteroid Field Distress Call", status: "mechanic", facts: ["The ship can take 5 hull damage and 1 engine damage.", "You can receive a random amount of scrap with resources.", "You can receive the Damaged Stasis Pod augment with low scrap."] },
  { title: "Disabled Rock Transport", status: "mechanic", facts: ["You receive a random amount of scrap with resources."] },
  { title: "Distress Beacon Events", status: "no-mechanic", facts: [] },
  { title: "Distress beacon", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship (Pirate)", status: "mechanic", facts: ["Destroying the pirate bait yields medium scrap with resources.", "Killing that crew yields high scrap with resources.", "The refugees then give low scrap with resources."] },
  { title: "Drifting Refugee Ship Distress (Pirate)", status: "mechanic", facts: ["Destroying the pirate bait yields medium scrap with resources.", "Killing that crew yields high scrap with resources.", "The refugees then give low scrap with resources."] },
  { title: "Drone Schematics", status: "mechanic", facts: ["Drones deal 1 hull or system damage per shot, or per room a beam crosses.", "Purchase prices include 50, 60, 65, 70, and 75 scrap."] },
  { title: "Empty beacon (Crystal)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Mantis)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Slug)", status: "no-mechanic", facts: [] },
  { title: "Encrypted Federation Signal", status: "mechanic", facts: ["You can receive medium resources with some scrap.", "You can receive high scrap with resources."] },
  { title: "Engi Controlled Sector", status: "mechanic", facts: ["Crew of the listed races can be purchased or received as a crew-kill reward."] },
  { title: "Engi Free Stuff", status: "mechanic", facts: ["You receive a random amount of scrap with resources."] },
  { title: "Engi Rebel Fight", status: "no-mechanic", facts: [] },
  { title: "Engi Surrender", status: "mechanic", facts: ["You receive a random amount of scrap with resources."] },
  { title: "Engi distress", status: "mechanic", facts: ["You can receive low or medium scrap with resources.", "One choice pays them 25 scrap.", "Another choice pays 40 scrap, 2 missiles, and 2 fuel."] },
  { title: "Engi ship attacked by Mantis ship", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can receive an Engi crewmember and low scrap with resources.", "You can receive a weapon with low scrap."] },
  { title: "Engi virus", status: "mechanic", facts: ["You can lose an Engi crewmember.", "You can receive an Engi crewmember named Virus.", "You can receive the Drone Reactor Booster augment with scrap."] },
  { title: "Escort FTL haywire civilian ship", status: "mechanic", facts: ["You receive low scrap up front.", "Finishing the escort yields high scrap with resources."] },
  { title: "Escort civilians FTL haywire", status: "mechanic", facts: ["You receive low scrap up front.", "Finishing the escort yields high scrap with resources."] },
  { title: "Explore the System", status: "mechanic", facts: ["Fuel trades cost 20, 10, or 5 scrap.", "One result deals 5 hull damage, a system hit, and a fire.", "You can receive medium missiles and scrap, or medium fuel and scrap."] },
  { title: "Federation Deserters", status: "mechanic", facts: ["Offering supplies costs 15-25 scrap and 1-3 fuel."] },
  { title: "Federation Ship in Need of Aid", status: "mechanic", facts: ["You can receive medium scrap with resources.", "You can receive a crewmember and low scrap with resources.", "A skilled crewmember can join with medium scrap or high fuel and scrap."] },
  { title: "Federation signal broadcast", status: "mechanic", facts: ["You can receive medium resources with some scrap.", "You can receive high scrap with resources."] },
  { title: "Fire on research station", status: "mechanic", facts: ["You can lose a crewmember and receive low scrap.", "The ship can take 4 hull damage and a system hit for low scrap.", "Dr. Jones can join for low scrap."] },
  { title: "Free Drone Schematic", status: "mechanic", facts: ["You receive a drone schematic with low scrap."] },
  { title: "Free scrap with resources (Engi)", status: "mechanic", facts: ["You receive a random amount of scrap with resources."] },
  { title: "Friendly Ship Out of Fuel", status: "mechanic", facts: ["You receive high scrap."] },
  { title: "Fuel Engi Ship Repair", status: "mechanic", facts: ["A repair trade loses 10-20 scrap for 4-6 fuel.", "You can receive medium or high fuel and scrap."] },
  { title: "Fuel Trader (Distress)", status: "mechanic", facts: ["One trade loses 15-25 scrap for 2-5 fuel.", "Another trade loses 5-12 scrap for 3-7 fuel."] },
  { title: "Fuel for drone parts", status: "no-mechanic", facts: [] },
  { title: "General Store", status: "no-mechanic", facts: [] },
  { title: "Hazards", status: "mechanic", facts: ["Solar flares can damage hull and systems in rooms that catch fire.", "An affected room can take 1 hull damage: 33% for one fire, 66% for two.", "With shields down, the maximum hull damage is 6."] },
  { title: "Hidden federation base", status: "mechanic", facts: ["A crewmember can join with low scrap and resources.", "The base can give 35 repairs and medium scrap with resources.", "A survivor can join with high scrap and resources and 7 repairs."] },
  { title: "Hostile Pirate in Lanius Sector", status: "no-mechanic", facts: [] },
  { title: "Human Boarders Sensors Jammed", status: "no-mechanic", facts: [] },
  { title: "Human boarders in plasma storm", status: "mechanic", facts: ["You receive medium scrap with resources as 3-4 human boarders beam aboard."] },
  { title: "I hardly lifted a finger (Achievement)", status: "mechanic", facts: ["Destroying a system deals 1 hull damage."] },
  { title: "Intelligent life forms planet", status: "mechanic", facts: ["You can receive an Engi crewmember and low scrap with resources.", "You can lose a crewmember.", "You can receive an Engi crewmember."] },
  { title: "Ion Storm Events", status: "no-mechanic", facts: [] },
  { title: "KazaaakplethKilik", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "The Mantis Cruiser unlock grants high scrap, Mantis Pheromones, and crewmember Kazaaak.", "You can receive a weapon with high scrap."] },
  { title: "Lanius Attacking Civilian", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Lanius Merchant", status: "mechanic", facts: ["Trading 3-7 fuel yields 15-30 scrap.", "Trading 3-7 missiles or drone parts yields 20-40 scrap.", "A translator costs 40 scrap and can add a Lanius crewmember named Translator."] },
  { title: "Lanius Salvaging Small Asteroid Belt", status: "mechanic", facts: ["You receive medium scrap."] },
  { title: "Lanius Ships", status: "no-mechanic", facts: [] },
  { title: "Lanius absorbing automated scout", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can receive a random amount of scrap and delay the Rebel Fleet for 1 turn."] },
  { title: "Lanius attacking Rock", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Lanius attacking civilian distress", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Lanius empty distress beacon 1", status: "no-mechanic", facts: [] },
  { title: "Lanius fight distress trap", status: "no-mechanic", facts: [] },
  { title: "Lanius free stuff", status: "mechanic", facts: ["You receive high scrap with resources."] },
  { title: "Lanius ship absorbing automated scout", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can receive a random amount of scrap and delay the Rebel Fleet for 1 turn."] },
  { title: "Lanius ship attacking Rock", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Lanius ship in rich debris field", status: "mechanic", facts: ["You can receive low, medium, or high scrap with resources."] },
  { title: "Lanius trader with translator", status: "mechanic", facts: ["Trading 3-7 fuel yields 15-30 scrap.", "Trading 3-7 missiles or drone parts yields 20-40 scrap.", "A translator costs 40 scrap and can add a Lanius crewmember named Translator."] },
  { title: "Large Convoy", status: "mechanic", facts: ["You can receive low fuel and scrap and 8 repairs.", "You can receive medium scrap with resources."] },
  { title: "Last Stand empty beacon", status: "no-mechanic", facts: [] },
  { title: "Long-Range Scanners", status: "mechanic", facts: ["Purchase price is 30 scrap."] },
  { title: "Malfunction Defense System", status: "mechanic", facts: ["The ship can take 5 hull damage, a system hit, and a breach.", "You can receive low, medium, or high scrap with resources."] },
  { title: "Mantis Attacking Engi Station", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can receive an Engi crewmember and low scrap with resources.", "You can receive a weapon with low scrap."] },
  { title: "Mantis Controlled Sector", status: "mechanic", facts: ["Crew of the listed races can be purchased or received as a crew-kill reward."] },
  { title: "Mantis Fuel Attack", status: "mechanic", facts: ["You can receive medium or high fuel and scrap."] },
  { title: "Mantis Pheromones", status: "mechanic", facts: ["Sell price is 25 scrap."] },
  { title: "Mantis Ships", status: "no-mechanic", facts: [] },
  { title: "Mantis War Camp", status: "mechanic", facts: ["You can receive medium scrap and a quest marker.", "You can receive medium or high scrap with resources.", "You can receive an Engi crewmember and high resources with some scrap."] },
  { title: "Mantis fight (Engi)", status: "no-mechanic", facts: [] },
  { title: "Mantis fight choice in nebula", status: "no-mechanic", facts: [] },
  { title: "Mantis fight near sun", status: "no-mechanic", facts: [] },
  { title: "Mantis ship attacking Crystal", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Mantis ship comm chatter intercept", status: "no-mechanic", facts: [] },
  { title: "Mercenary work", status: "mechanic", facts: ["You can receive a weapon with medium scrap.", "You can receive low scrap with resources.", "You can receive medium scrap and 5 repairs."] },
  { title: "Merchant docked with Lanius", status: "mechanic", facts: ["Crafting costs 45 scrap for an augment, 50 for a weapon, or 40 for a drone schematic."] },
  { title: "Missiles (Weapon)", status: "mechanic", facts: ["Listed purchase prices include 45, 60, and 65 scrap.", "Missile text cites hull damage; bombs are said not to damage hull."] },
  { title: "Nebula Events", status: "no-mechanic", facts: [] },
  { title: "Nebula battlefield", status: "mechanic", facts: ["Drifting wreckage can deal 5 hull damage and start a fire.", "You can receive a crewmember.", "You can receive medium scrap with resources."] },
  { title: "No fuel: Auto-ship fight", status: "mechanic", facts: ["You receive low scrap with resources."] },
  { title: "No fuel: Rebel assistant hails", status: "mechanic", facts: ["You can receive medium or high fuel and scrap."] },
  { title: "No fuel: Slug fuel trader", status: "mechanic", facts: ["5 fuel costs 15 scrap.", "Another trade loses 20-35 scrap and 2-4 missiles."] },
  { title: "No fuel: friendly refugee", status: "no-mechanic", facts: [] },
  { title: "No fuel: fuel trader (distress on)", status: "mechanic", facts: ["One trade loses 15-25 scrap for 2-5 fuel.", "Another trade loses 5-12 scrap for 3-7 fuel."] },
  { title: "No fuel: wait fail", status: "no-mechanic", facts: [] },
  { title: "Odd Moon", status: "mechanic", facts: ["You can receive a weapon with low scrap or a random amount of scrap.", "You can receive medium scrap.", "You can receive a Zoltan crewmember."] },
  { title: "Phase Shift", status: "no-mechanic", facts: [] },
  { title: "Pirate Controlled Sector", status: "mechanic", facts: ["Crew of the listed races can be purchased or received as a crew-kill reward."] },
  { title: "Pirate Fight Near Sun", status: "no-mechanic", facts: [] },
  { title: "Pirate Slaver", status: "mechanic", facts: ["You lose a crewmember."] },
  { title: "Pirate arms dealer", status: "mechanic", facts: ["The offered weapon costs 45 scrap."] },
  { title: "Pirate attacking civilian", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Pirate briber", status: "mechanic", facts: ["The Rebel Fleet can be delayed for 1 turn.", "You can receive low or medium scrap with resources.", "One result is a random amount of scrap."] },
  { title: "Pirate fight (Slug)", status: "no-mechanic", facts: [] },
  { title: "Pirate fight distress trap", status: "no-mechanic", facts: [] },
  { title: "Pirate in Nebula", status: "no-mechanic", facts: [] },
  { title: "Pirate ship attacking civilian distress", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Pirate ship selling weapon", status: "mechanic", facts: ["The offered weapon costs 45 scrap."] },
  { title: "Plagued station", status: "mechanic", facts: ["You can receive low scrap, or a random amount of scrap.", "You can receive a Human crewmember with low scrap.", "You can lose a crewmember."] },
  { title: "Plasma Storm Incapacitated Ships", status: "mechanic", facts: ["One path deals 4 hull damage and a breach for high resources with some scrap.", "You can receive a crewmember and low scrap with resources.", "You can lose a crewmember and receive low scrap with resources."] },
  { title: "Plasma storm wreckage", status: "mechanic", facts: ["One path deals 4 hull damage and a breach for high resources with some scrap.", "You can receive a crewmember and low scrap with resources.", "You can lose a crewmember and receive low scrap with resources."] },
  { title: "Pulsar", status: "no-mechanic", facts: [] },
  { title: "Races/Crew Members", status: "mechanic", facts: ["Receiving a 9th crewmember forces you to dismiss one crewmember."] },
  { title: "Races/Lanius", status: "no-mechanic", facts: [] },
  { title: "Races/Zoltan", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Engi", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Rockman", status: "no-mechanic", facts: [] },
  { title: "Random Events", status: "no-mechanic", facts: [] },
  { title: "Rebel Attacking Civilians in Last Stand", status: "mechanic", facts: ["You can receive medium or high scrap with resources.", "You can receive medium resources with some scrap."] },
  { title: "Rebel Auto-Ship Warning", status: "mechanic", facts: ["You receive low scrap with resources."] },
  { title: "Rebel Auto-ship near sensor station", status: "mechanic", facts: ["You receive low scrap and the sector map is revealed."] },
  { title: "Rebel Automated Ship Near Sensor Station", status: "mechanic", facts: ["You receive low scrap and the sector map is revealed."] },
  { title: "Rebel Civilian Checkpoint", status: "mechanic", facts: ["You can receive low scrap, or low scrap with resources."] },
  { title: "Rebel Fight in Last Stand", status: "no-mechanic", facts: [] },
  { title: "Rebel Scout Pursuing Civilian Ship", status: "mechanic", facts: ["You receive low scrap with resources."] },
  { title: "Rebel Ship in Nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel Unarmed Defector", status: "mechanic", facts: ["You can receive a Human crewmember.", "One path deals 3 hull damage.", "One path loses a crewmember."] },
  { title: "Rebel attacking poorly equipped Engi", status: "mechanic", facts: ["You can receive low or medium scrap with resources.", "One choice pays them 25 scrap.", "Another choice pays 40 scrap, 2 missiles, and 2 fuel."] },
  { title: "Rebel fight (Crystal)", status: "no-mechanic", facts: [] },
  { title: "Rebel fight among Federation and Rebel fleets", status: "mechanic", facts: ["You can receive low scrap, or medium scrap with resources."] },
  { title: "Rebel fight choice in nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel fight near pulsar", status: "no-mechanic", facts: [] },
  { title: "Rebel ship attacking Crystal ship", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Rebel ship supplying civilians", status: "mechanic", facts: ["You can receive low or medium scrap with resources.", "One path deals 2 hull damage plus a fire or breach."] },
  { title: "Rebel transport ship", status: "mechanic", facts: ["You can receive a weapon with medium scrap.", "You can receive a crewmember and low scrap with resources.", "You can receive high scrap with resources."] },
  { title: "Red Giants", status: "mechanic", facts: ["Solar flares can damage hull and systems in rooms that catch fire.", "An affected room can take 1 hull damage: 33% for one fire, 66% for two.", "With shields down, the maximum hull damage is 6."] },
  { title: "Refueling station", status: "mechanic", facts: ["Fuel prices are 12 scrap for 6, 6 scrap for 3, or 2 scrap for 1."] },
  { title: "Refugee (Zoltan)", status: "mechanic", facts: ["Destroying the Zoltan ship yields medium scrap with resources.", "Killing its crew yields high scrap with resources.", "The refugees then give low scrap with resources."] },
  { title: "Refugee distress", status: "mechanic", facts: ["Destroying the bait ship yields medium scrap with resources.", "Killing its crew yields high scrap with resources.", "The refugees then give low scrap with resources."] },
  { title: "Refugee with communications down", status: "mechanic", facts: ["You can lose a crewmember.", "You can receive a crewmember.", "You can receive medium missiles and scrap."] },
  { title: "Research Station Near Pulsar", status: "no-mechanic", facts: [] },
  { title: "Rock Armoured Transport", status: "mechanic", facts: ["You receive high scrap with resources."] },
  { title: "Rock Deserters", status: "mechanic", facts: ["You receive a Rockman crewmember."] },
  { title: "Rock Fight With Boarders in Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Rock Pirate Fight", status: "no-mechanic", facts: [] },
  { title: "Rock Ships", status: "no-mechanic", facts: [] },
  { title: "Rock atheists", status: "mechanic", facts: ["You receive a Rockman crewmember."] },
  { title: "Rock pirate fight in asteroid field", status: "no-mechanic", facts: [] },
  { title: "Rock pirates fight near sun", status: "no-mechanic", facts: [] },
  { title: "Rupturing Zoltan Freighter", status: "no-mechanic", facts: [] },
  { title: "Sell fuel for drone parts", status: "no-mechanic", facts: [] },
  { title: "Settlement Mercenary Work", status: "mechanic", facts: ["You can receive a weapon with medium scrap.", "You can receive low scrap with resources.", "You can receive medium scrap and 5 repairs."] },
  { title: "Ship Achievements/Artillery Mastery", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Clash of the Titans", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Full Arsenal", status: "mechanic", facts: ["Listed scrap costs: Teleporter 90, Cloaking 150, Hacking 80, Mind Control 75.", "Drone Control costs 75 or 85 scrap depending on its drone."] },
  { title: "Ship Achievements/Is it warm in here?", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/No Escape", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Shields Holding", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/The United Federation", status: "no-mechanic", facts: [] },
  { title: "Ship Being Mined by Lanius", status: "mechanic", facts: ["You can receive medium scrap with resources.", "You can receive medium missiles and scrap."] },
  { title: "Ship Strategies", status: "no-mechanic", facts: [] },
  { title: "Slaver (hostile)", status: "mechanic", facts: ["You lose a crewmember."] },
  { title: "Slug Comm Tapping", status: "mechanic", facts: ["You can receive high scrap, or low, medium, or high scrap with resources."] },
  { title: "Slug Exposed in Open Space", status: "no-mechanic", facts: [] },
  { title: "Slug Mantis fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Slug Pirate fight", status: "no-mechanic", facts: [] },
  { title: "Slug Sabotage Oxygen System", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Slug Trapped on a Moon", status: "mechanic", facts: ["You lose 35 scrap, 2-4 fuel, and 1-2 drone parts.", "You receive a Slug crewmember."] },
  { title: "Slug doors hacker", status: "mechanic", facts: ["You can receive medium or high scrap with resources."] },
  { title: "Slug fight", status: "no-mechanic", facts: [] },
  { title: "Slug hacker (medical)", status: "mechanic", facts: ["You receive high scrap with resources."] },
  { title: "Slug oxygen hacker", status: "mechanic", facts: ["You receive medium scrap with resources."] },
  { title: "Slug store ship", status: "no-mechanic", facts: [] },
  { title: "Small Rebel Research Station", status: "no-mechanic", facts: [] },
  { title: "Space Station Under Construction", status: "mechanic", facts: ["Losing a Lanius crewmember can yield an augment with high scrap.", "Other results include medium scrap or high scrap with resources."] },
  { title: "Stasis pod", status: "mechanic", facts: ["Sell price is 15 scrap."] },
  { title: "Store (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Store (Rock)", status: "no-mechanic", facts: [] },
  { title: "Store in nebula (Slug)", status: "no-mechanic", facts: [] },
  { title: "Sweet Revenge", status: "mechanic", facts: ["The shard is created only when the hull is damaged."] },
  { title: "Terraforming scan", status: "mechanic", facts: ["You receive 15-25 scrap."] },
  { title: "The Engi Virus", status: "mechanic", facts: ["You can lose an Engi crewmember.", "You can receive an Engi crewmember named Virus.", "You can receive the Drone Reactor Booster augment with scrap."] },
  { title: "The Mercenary", status: "mechanic", facts: ["The Rebel Fleet is delayed for 2 turns."] },
  { title: "The guns... They've stopped", status: "no-mechanic", facts: [] },
  { title: "Trade: sell fuel for drone parts", status: "no-mechanic", facts: [] },
  { title: "Trade fuel for drone parts", status: "no-mechanic", facts: [] },
  { title: "Trader", status: "no-mechanic", facts: [] },
  { title: "Two Smashed Ships", status: "mechanic", facts: ["You receive a random amount of resources with some scrap."] },
  { title: "Unencrypted Communication Channel", status: "mechanic", facts: ["One path deals 15 hull damage, a system hit, a fire, and a breach.", "You can receive a weapon with high scrap."] },
  { title: "Weak and hungry human boarders", status: "no-mechanic", facts: [] },
  { title: "Zoltan \"Great Eye\"", status: "mechanic", facts: ["You lose a crewmember.", "You receive high scrap."] },
  { title: "Zoltan Border Police", status: "no-mechanic", facts: [] },
  { title: "Zoltan Fight", status: "no-mechanic", facts: [] },
  { title: "Zoltan Homeworlds", status: "mechanic", facts: ["Crew of the listed races can be purchased or received as a crew-kill reward."] },
  { title: "Zoltan Pirate Fight", status: "no-mechanic", facts: [] },
  { title: "Zoltan Shield Bypass", status: "mechanic", facts: ["Purchase price is 55 scrap."] },
  { title: "Zoltan Trade Hub", status: "mechanic", facts: ["You lose 10 scrap."] },
  { title: "Zoltan free stuff", status: "mechanic", facts: ["You receive a random amount of scrap with resources."] },
  { title: "Zoltan science ship", status: "mechanic", facts: ["You can receive a Zoltan crewmember and low scrap with resources.", "Other results are low or medium scrap with resources."] },
];
