export type EventRow = {
  title: string;
  status: "mechanic" | "no-mechanic" | "blocked";
  facts: string[];
};

export const EVENTS_2: EventRow[] = [
  { title: "Abandoned Space Station", status: "mechanic", facts: ["Can gain a crewmember."] },
  { title: "Advanced FTL Navigation", status: "mechanic", facts: ["Scrap: 50 scrap."] },
  { title: "Anti-Ship Battery Firing on Lanius Ships", status: "mechanic", facts: ["Hull: 8 hull repairs."] },
  { title: "Asteroid Field Lanius Scavengers", status: "no-mechanic", facts: [] },
  { title: "Augments", status: "mechanic", facts: ["Scrap: 25 scrap, 40 scrap, 80 scrap, 60 scrap, 50 scrap, 120 scrap, 55 scrap, 65 scrap and others.", "Hull: 3-5 hull repaired by a drone."] },
  { title: "Auto-ship attacking refueling outpost", status: "no-mechanic", facts: [] },
  { title: "Auto-ship fight", status: "no-mechanic", facts: [] },
  { title: "Auto-ship fight in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Auto-ship in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Auto-ship near storage station", status: "no-mechanic", facts: [] },
  { title: "Auto-ship pursuing civilian ship", status: "no-mechanic", facts: [] },
  { title: "Automated Rebel Scout Attacking Refueling Outpost", status: "no-mechanic", facts: [] },
  { title: "Badly Damaged Lanius Craft", status: "no-mechanic", facts: [] },
  { title: "Black Market Weapon Trader", status: "mechanic", facts: ["Scrap: 45 scrap."] },
  { title: "Boarders: Crystal", status: "no-mechanic", facts: [] },
  { title: "Boarders: Humans in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Boarders: Rockmen near sun", status: "no-mechanic", facts: [] },
  { title: "Bomb (Weapon)", status: "mechanic", facts: ["Scrap: 45 scrap, 60 scrap, 50 scrap, 55 scrap, 40 scrap."] },
  { title: "Civilian Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Civilian Ship Fleeing from Lanius", status: "no-mechanic", facts: [] },
  { title: "Civilians Under Fire from Lanius", status: "no-mechanic", facts: [] },
  { title: "Clonebay", status: "mechanic", facts: ["Dead crewmembers are revived, or lost if the Clone Bay stays offline."] },
  { title: "Crew Members", status: "mechanic", facts: ["Losing all crewmembers causes a game over."] },
  { title: "Crushed Pirate", status: "mechanic", facts: ["Hull: 2 hull damage."] },
  { title: "Crystal Boarders", status: "no-mechanic", facts: [] },
  { title: "Crystal Cruiser", status: "no-mechanic", facts: [] },
  { title: "Crystal Rebel Fight", status: "no-mechanic", facts: [] },
  { title: "Crystal attacking Federation loyalists", status: "mechanic", facts: ["Can gain a crewmember."] },
  { title: "Crystal fight with surrender offer (hull repairs)", status: "mechanic", facts: ["Hull: 8 hull repairs."] },
  { title: "Crystal ship convoy fight", status: "mechanic", facts: ["Hull: 8 hull repairs."] },
  { title: "Crystalline Men Buried", status: "mechanic", facts: ["Named reward: Heavy Crystal Mark II.", "A crewmember can be lost."] },
  { title: "Crystalline Ship Messaging About Rebels", status: "mechanic", facts: ["Rebel fleet pursuit is delayed for 1 jump."] },
  { title: "Damaged Vessel docked with Beacon", status: "mechanic", facts: ["Scrap: 30 scrap.", "Can gain a Lanius crewmember."] },
  { title: "Dangerous looking slug ship", status: "mechanic", facts: ["Scrap: 35 scrap."] },
  { title: "Debris Field Zoltan Cruiser", status: "no-mechanic", facts: [] },
  { title: "Dense asteroid field distress", status: "mechanic", facts: ["Named reward: Damaged Stasis Pod.", "Hull: 5 hull damage."] },
  { title: "Disabled Rock ship", status: "no-mechanic", facts: [] },
  { title: "Distress Signal Emitter Consumed", status: "no-mechanic", facts: [] },
  { title: "Distress signal from Slug ship under attack by Lanius", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship (Slug)", status: "no-mechanic", facts: [] },
  { title: "Drifting Refugee Ship Distress (Slug)", status: "no-mechanic", facts: [] },
  { title: "Drones salesman", status: "mechanic", facts: ["Scrap: 25 scrap, 25-35 scrap, 15-20 scrap, 25-33 scrap, 50-65 scrap.", "Hull: 3 hull damage."] },
  { title: "Empty beacon (Engi)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Pirate)", status: "no-mechanic", facts: [] },
  { title: "Empty beacon (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Enemy ships' weapons (tables)", status: "no-mechanic", facts: [] },
  { title: "Engi Distress Call", status: "mechanic", facts: ["Hull: 10 hull repairs.", "Can gain an Engi crewmember."] },
  { title: "Engi Homeworlds", status: "no-mechanic", facts: [] },
  { title: "Engi Research Station", status: "mechanic", facts: ["A crewmember can be lost. A lost crewmember can be revived."] },
  { title: "Engi attacked by Mantis", status: "mechanic", facts: ["Hull: 10 hull repairs.", "Can gain an Engi crewmember."] },
  { title: "Engi distress Rebel fight", status: "mechanic", facts: ["Named reward: Healing Burst, Engi Med-bot Dispersal.", "Scrap: 25 scrap, 40 scrap."] },
  { title: "Engi ship distress call", status: "mechanic", facts: ["Hull: 10 hull repairs.", "Can gain an Engi crewmember."] },
  { title: "Environmental Hazard", status: "mechanic", facts: ["Hull: 1 hull damage; up to 6 hull damage; ASB shot deals 3 damage and a hull breach.", "Nebula slows Rebel fleet pursuit by 50% (20% in nebula sectors)."] },
  { title: "Escort Nearby Ship", status: "no-mechanic", facts: [] },
  { title: "Events", status: "no-mechanic", facts: [] },
  { title: "FTL: Advanced Edition", status: "mechanic", facts: ["Scrap: 50 scrap.", "Clone Bay clones crewmembers who die."] },
  { title: "Federation Fleet", status: "no-mechanic", facts: [] },
  { title: "Federation Ships", status: "no-mechanic", facts: [] },
  { title: "Fight in Last Stand", status: "no-mechanic", facts: [] },
  { title: "Fires and venting", status: "mechanic", facts: ["Hull: 1 hull damage."] },
  { title: "Free Stuff", status: "no-mechanic", facts: [] },
  { title: "Free scrap with resources (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Friendly Slaver", status: "mechanic", facts: ["Scrap: 25-45 scrap.", "Can gain a crewmember."] },
  { title: "Fuel Fleet Delay", status: "mechanic", facts: ["Rebel fleet pursuit is delayed for 1 jump."] },
  { title: "Fuel Wait Fail", status: "no-mechanic", facts: [] },
  { title: "Full Arsenal", status: "mechanic", facts: ["Scrap costs: Teleporter 90, Drone Control 75/85, Cloaking 150, Hacking 80, Mind Control 75, Backup Battery 35."] },
  { title: "Giant Alien Spiders", status: "mechanic", facts: ["A crewmember can be lost. A lost crewmember can be revived."] },
  { title: "Heavily Damaged Federation Ship", status: "mechanic", facts: ["Can gain a crewmember."] },
  { title: "Hiring Crewmembers Station", status: "mechanic", facts: ["Scrap: 25-45 scrap, 25-55 scrap."] },
  { title: "Hostile Rebel in Lanius Sector", status: "no-mechanic", facts: [] },
  { title: "Human boarders in abandoned sector", status: "no-mechanic", facts: [] },
  { title: "Human boarders jammed sensors", status: "no-mechanic", facts: [] },
  { title: "Improve Reactor for Supplies", status: "no-mechanic", facts: [] },
  { title: "Intelligent ponies", status: "mechanic", facts: ["Can gain an Engi crewmember. A crewmember can be lost."] },
  { title: "Ion Storms", status: "no-mechanic", facts: [] },
  { title: "LRS", status: "mechanic", facts: ["Scrap: 30 scrap."] },
  { title: "Lanius Distress Beacon Empty", status: "no-mechanic", facts: [] },
  { title: "Lanius Merchant with Improved Translator", status: "mechanic", facts: ["Scrap: 15-30 scrap, 20-40 scrap.", "Can gain a Lanius crewmember named Translator."] },
  { title: "Lanius Salvaging Small Civilian Craft", status: "no-mechanic", facts: [] },
  { title: "Lanius Store", status: "no-mechanic", facts: [] },
  { title: "Lanius absorbing jump beacon", status: "mechanic", facts: ["Scrap: 30 scrap.", "Can gain a Lanius crewmember."] },
  { title: "Lanius attacking Rock ship", status: "no-mechanic", facts: [] },
  { title: "Lanius craftsmen", status: "mechanic", facts: ["Scrap: 45 scrap, 50 scrap, 40 scrap."] },
  { title: "Lanius empty distress beacon 2", status: "no-mechanic", facts: [] },
  { title: "Lanius fight in asteroid field", status: "no-mechanic", facts: [] },
  { title: "Lanius lone ship", status: "no-mechanic", facts: [] },
  { title: "Lanius ship absorbing jump beacon", status: "mechanic", facts: ["Scrap: 30 scrap.", "Can gain a Lanius crewmember."] },
  { title: "Lanius ship attacking Slug", status: "no-mechanic", facts: [] },
  { title: "Lanius ship mining Mantis ship hull", status: "no-mechanic", facts: [] },
  { title: "Lanius with Federation science craft", status: "no-mechanic", facts: [] },
  { title: "Large Trade Station", status: "no-mechanic", facts: [] },
  { title: "Legendary Thief KazaaakplethKilik Random Event", status: "mechanic", facts: ["Named reward: Mantis Pheromones.", "Can gain a Mantis crewmember named Kazaaak."] },
  { title: "Loss of Cabin Pressure", status: "no-mechanic", facts: [] },
  { title: "Malfunctioning defense system", status: "mechanic", facts: ["Hull: 5 hull damage."] },
  { title: "Mantis Attacking Slug", status: "no-mechanic", facts: [] },
  { title: "Mantis Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Mantis Fugitive", status: "mechanic", facts: ["Hull: 5 hull damage.", "Can gain a Mantis crewmember."] },
  { title: "Mantis Ship-Collectors", status: "no-mechanic", facts: [] },
  { title: "Mantis Ships Battle for Rock Freighter", status: "no-mechanic", facts: [] },
  { title: "Mantis attacking Crystal", status: "no-mechanic", facts: [] },
  { title: "Mantis fight (Slug)", status: "no-mechanic", facts: [] },
  { title: "Mantis fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Mantis fight with boarders (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Mantis ship attacking Slug ship", status: "no-mechanic", facts: [] },
  { title: "Mantis ship with Rock body parts", status: "no-mechanic", facts: [] },
  { title: "Merchant's Request", status: "mechanic", facts: ["Scrap: 20-30 scrap, 40-55 scrap, 55-70 scrap.", "Can gain a crewmember."] },
  { title: "Merchant docked with Lanius Transport", status: "mechanic", facts: ["Scrap: 45 scrap, 50 scrap, 40 scrap."] },
  { title: "Mods and Tools", status: "no-mechanic", facts: [] },
  { title: "Nebula Seen Ships Exchange Fire", status: "mechanic", facts: ["Hull: 5 hull damage.", "Can gain a crewmember."] },
  { title: "Nebula lost ship", status: "mechanic", facts: ["Can gain a crewmember."] },
  { title: "No fuel: Auto-ship warning", status: "no-mechanic", facts: [] },
  { title: "No fuel: Rebel fight", status: "no-mechanic", facts: [] },
  { title: "No fuel: automated refueling ship", status: "mechanic", facts: ["Scrap: 20 scrap, 8 scrap."] },
  { title: "No fuel: fuel trader", status: "no-mechanic", facts: [] },
  { title: "No fuel: poorly armed Slug ship", status: "mechanic", facts: ["Scrap: 15 scrap, 20-35 scrap."] },
  { title: "No fuel: wait fail (distress)", status: "no-mechanic", facts: [] },
  { title: "Orbiting Small Platform", status: "mechanic", facts: ["Scrap: 5-10 scrap.", "Hull: 3 hull damage."] },
  { title: "Pirate Attacking Civilian in Lanius Sector", status: "no-mechanic", facts: [] },
  { title: "Pirate Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Pirate Fight in Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Pirate Smuggler", status: "no-mechanic", facts: [] },
  { title: "Pirate at Pulsar", status: "no-mechanic", facts: [] },
  { title: "Pirate attacking civilian (Lanius)", status: "no-mechanic", facts: [] },
  { title: "Pirate engine hacker", status: "no-mechanic", facts: [] },
  { title: "Pirate fight (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Pirate fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Pirate ship attacking Crystal", status: "no-mechanic", facts: [] },
  { title: "Pirate ship distress trap", status: "no-mechanic", facts: [] },
  { title: "Pirate ships in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Plasma Storm", status: "no-mechanic", facts: [] },
  { title: "Plasma Storms", status: "no-mechanic", facts: [] },
  { title: "Poorly Armed Slug Ship", status: "mechanic", facts: ["Scrap: 15 scrap, 20-35 scrap."] },
  { title: "Quest beacon", status: "no-mechanic", facts: [] },
  { title: "Races/Crystal", status: "no-mechanic", facts: [] },
  { title: "Races/Mantis", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Ancient Device", status: "mechanic", facts: ["Named reward: Crystal Vengeance.", "Hull: 10 hull repairs.", "A Distraction Buoy postpones the Rebel fleet by 1 jump."] },
  { title: "Races (legacy page with comments)/Human", status: "no-mechanic", facts: [] },
  { title: "Races (legacy page with comments)/Slug", status: "no-mechanic", facts: [] },
  { title: "Rarity", status: "no-mechanic", facts: [] },
  { title: "Rebel Attacking Engi", status: "mechanic", facts: ["Named reward: Healing Burst, Engi Med-bot Dispersal.", "Scrap: 25 scrap, 40 scrap."] },
  { title: "Rebel Auto-Ship in Nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel Auto-ship near small space-station", status: "no-mechanic", facts: [] },
  { title: "Rebel Automated Ship Near Small Space-Station", status: "no-mechanic", facts: [] },
  { title: "Rebel Controlled Sector", status: "no-mechanic", facts: [] },
  { title: "Rebel Flagship Construction", status: "mechanic", facts: ["Rebel fleet is delayed for 2 turns."] },
  { title: "Rebel Ship Laying Down Fire on Crystalline Vessel", status: "no-mechanic", facts: [] },
  { title: "Rebel Store", status: "no-mechanic", facts: [] },
  { title: "Rebel at Pulsar", status: "no-mechanic", facts: [] },
  { title: "Rebel attacking refueling outpost", status: "no-mechanic", facts: [] },
  { title: "Rebel fight (Engi)", status: "no-mechanic", facts: [] },
  { title: "Rebel fight among Rebel fleet", status: "no-mechanic", facts: [] },
  { title: "Rebel fight in nebula", status: "no-mechanic", facts: [] },
  { title: "Rebel fight with boarders", status: "no-mechanic", facts: [] },
  { title: "Rebel ship attacking Federation loyalists", status: "mechanic", facts: ["Can gain a crewmember."] },
  { title: "Rebel ship warning", status: "no-mechanic", facts: [] },
  { title: "Rebels Supplying Civilians", status: "mechanic", facts: ["Hull: 2 hull damage."] },
  { title: "Refuel Station", status: "mechanic", facts: ["Scrap: 12 scrap, 6 scrap, 2 scrap."] },
  { title: "Refugee", status: "no-mechanic", facts: [] },
  { title: "Refugee Ship Trading for Scrap", status: "mechanic", facts: ["Scrap: 10 scrap."] },
  { title: "Refugee distress (Pirate)", status: "no-mechanic", facts: [] },
  { title: "Remote Settlement", status: "no-mechanic", facts: [] },
  { title: "Research station with no response", status: "mechanic", facts: ["Can gain a crewmember. A crewmember can be lost."] },
  { title: "Rock Boarders Near Sun", status: "no-mechanic", facts: [] },
  { title: "Rock Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Rock Fight in Asteroid Field", status: "no-mechanic", facts: [] },
  { title: "Rock Pirate Near Sun", status: "no-mechanic", facts: [] },
  { title: "Rock Store", status: "no-mechanic", facts: [] },
  { title: "Rock bride", status: "mechanic", facts: ["Can gain a Rockman crewmember named Ariadne."] },
  { title: "Rock pirate fight near sun", status: "no-mechanic", facts: [] },
  { title: "Rock ship in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Science craft docked with Lanius", status: "no-mechanic", facts: [] },
  { title: "Sell missiles for scrap", status: "mechanic", facts: ["Scrap: 15 scrap, 30 scrap, 45 scrap."] },
  { title: "Shields Holding", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Avast, ye scurvy dogs!", status: "mechanic", facts: ["Kill 5 enemy crew with no hull damage and no crew loss."] },
  { title: "Ship Achievements/Defense Drones Don't Do D'anything!", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Givin' her all she's got, Captain!", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Loss of Cabin Pressure", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Phase Shift", status: "no-mechanic", facts: [] },
  { title: "Ship Achievements/Sweet Revenge", status: "mechanic", facts: ["Hull: Crystal Vengeance deals 1 damage when the hull is damaged."] },
  { title: "Ship Achievements/The guns... They've stopped", status: "no-mechanic", facts: [] },
  { title: "Ship Comparison", status: "no-mechanic", facts: [] },
  { title: "Ship Without Slug Markings", status: "no-mechanic", facts: [] },
  { title: "Slocknog", status: "mechanic", facts: ["Scrap: 55 scrap.", "Can gain a Slug crewmember named Slocknog."] },
  { title: "Slug Controlled Nebula", status: "no-mechanic", facts: [] },
  { title: "Slug Fight in Ion Storm", status: "no-mechanic", facts: [] },
  { title: "Slug Nebula Empty Beacon", status: "no-mechanic", facts: [] },
  { title: "Slug Rebel", status: "no-mechanic", facts: [] },
  { title: "Slug Ships", status: "no-mechanic", facts: [] },
  { title: "Slug and Rock Standoff", status: "mechanic", facts: ["Scrap: 10-15 scrap.", "Hull: 5 hull damage."] },
  { title: "Slug drink", status: "mechanic", facts: ["Scrap: 25-35 scrap.", "Hull: 10 hull repairs."] },
  { title: "Slug fight in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Slug hacker (oxygen)", status: "no-mechanic", facts: [] },
  { title: "Slug question", status: "mechanic", facts: ["Scrap: 35 scrap.", "Can gain a Slug crewmember."] },
  { title: "Slugman Fuel Depot", status: "mechanic", facts: ["Scrap: 50 scrap, 95 scrap."] },
  { title: "Small Research Station with No Response", status: "mechanic", facts: ["Can gain a crewmember. A crewmember can be lost."] },
  { title: "Special events crewmembers", status: "mechanic", facts: ["Scrap: 55 scrap, 40 scrap."] },
  { title: "Stationed Rebel Ship", status: "no-mechanic", facts: [] },
  { title: "Store (Mantis)", status: "no-mechanic", facts: [] },
  { title: "Store (Zoltan)", status: "no-mechanic", facts: [] },
  { title: "Store in nebula (Uncharted)", status: "no-mechanic", facts: [] },
  { title: "Tactical Approach", status: "no-mechanic", facts: [] },
  { title: "Terrified Rock Crew in Zoltan Nebula", status: "no-mechanic", facts: [] },
  { title: "The Final Boss", status: "mechanic", facts: ["Crew killed on the Flagship are not replaced later."] },
  { title: "The Rebellion", status: "no-mechanic", facts: [] },
  { title: "Tough Little Ship", status: "mechanic", facts: ["Scrap: 58 or 87 scrap.", "Hull: 1 hull damage; Must be repaired from 1 hull point to full."] },
  { title: "Trade: sell missiles for scrap", status: "mechanic", facts: ["Scrap: 15 scrap, 30 scrap, 45 scrap."] },
  { title: "Trade resources", status: "no-mechanic", facts: [] },
  { title: "Trader in nebula", status: "no-mechanic", facts: [] },
  { title: "Two pirate ships in plasma storm", status: "no-mechanic", facts: [] },
  { title: "Unknown Disease on Mining Colony", status: "mechanic", facts: ["A crewmember can be lost."] },
  { title: "Weapons/Tables", status: "no-mechanic", facts: [] },
  { title: "Zoltan \"Science Ship\"", status: "mechanic", facts: ["Can gain a Zoltan crewmember."] },
  { title: "Zoltan Controlled Sector", status: "no-mechanic", facts: [] },
  { title: "Zoltan Fight with Boarders", status: "no-mechanic", facts: [] },
  { title: "Zoltan Life Raft", status: "mechanic", facts: ["Scrap: 40 scrap.", "Can gain a Zoltan crewmember."] },
  { title: "Zoltan Research Facility", status: "mechanic", facts: ["Can gain a Crystal crewmember named Ruwen."] },
  { title: "Zoltan Ship Tour", status: "no-mechanic", facts: [] },
  { title: "Zoltan fight in asteroid field", status: "no-mechanic", facts: [] },
  { title: "Zoltan odd moon", status: "mechanic", facts: ["Can gain a Zoltan crewmember."] },
  { title: "Zoltan ship asks to dock", status: "mechanic", facts: ["Can gain a Zoltan crewmember."] },
];
