/**
 * Hostile encounters per sector type: which fight events a sector's hostile beacons draw, and the ship each one fields.
 * enemy-gen.ts turns this into the pool and the weights of a sector's random ("pool") fights.
 *
 * Two kinds of source, best first:
 *
 * 1. DOCUMENTED event lists. Wiki "Sectors", Civilian (Starting) Sector: "4-6 [[Template:EventList HOSTILE_CIVILIAN|
 *    hostile_civilian]] events" and "2 [[Template:EventList HOSTILE1|hostile1]] / [[Template:EventList OVERRIDE_HOSTILE1|
 *    override_hostile1]] events". Civilian Sector: "6-8 hostile encounters <!-- 4-6 from "HOSTILE_CIVILIAN" eventList and
 *    2-2 from "HOSTILE1" eventList, which comes after "QUESTS" -->". The two templates print every entry.
 *    Sectors: "'override_...' eventlists are used when Advanced Edition Content is enabled". This game has the Advanced
 *    Edition races (Lanius) and systems, so OVERRIDE_HOSTILE1 is the list used.
 *    Sectors: the order of entries "doesn't affect the likelihood of them being chosen over the other ones in the same
 *    eventList". So each entry weighs (draws from that list) / (entries in that list); 4-6 draws count as 5. INFERRED: the
 *    midpoint, and "unique" entries (once per sector) are not discounted.
 *
 * 2. DERIVED from event pages, for every other sector. The dump has no eventList template for any other sector, and the
 *    Sectors page names none ("@TO-DO: The beacons listing on this page should be updated to reflect the actual
 *    evenLists"); it prints only the count ("6-8 hostile encounters", "5-7 nebula hostile encounters", ...) and links each
 *    sector's event category. Category pages carry no member list; membership is each event page's {{Locations|...}}
 *    line. INFERRED membership rule: an event counts as a hostile encounter of a sector when its {{Locations}} names the
 *    sector, its long-range-scanner flag shows a ship ("LRSmap=ship...", or a plasma storm that hides it), and the page
 *    links a fight with a ship ("Fight a [[Rebel Ships|Rebel ship]]", "[[Enemy Ships|Pirate ship]]", ...).
 *    Left out by hand, with the reason:
 *    - "Slaver (friendly)": a trade ("Buy one slave ..."); the fight is only the "Attack the slaver scum" choice.
 *    - "Deactivated Auto-ship": "it appears to be de-activated"; the fight is one outcome of salvaging it.
 *    - "Legendary thief KazaaakplethKilik": Sectors, Mantis Homeworlds, places it by name ("1 Legendary thief ... event").
 *    - "Slug Home Nebula surrender": its page says the sector definition places it once
 *      ('<event name="NEBULA_SLUG_FIGHT_UNLOCK" min="1" max="1"/>').
 *    Each event counts once. INFERRED: the dump does not say how many lists an event sits in or how often.
 *
 * The ship of each event is the first fight its page links, read the way enemy-gen.ts requestFor reads a fight tier.
 */

export type HostileEntry = { event: string; ship: string; weight: number };

/** Template:EventList HOSTILE CIVILIAN, every row, with the ship each page fights. */
export const HOSTILE_CIVILIAN: [string, string][] = [
  ["Auto-ship attacking outpost", "Auto-ship"],
  ["Auto-ship fight near sun", "Auto-ship"],
  ["Pirate fight", "Pirate ship"],
  ["Pirate fight in asteroid field", "Pirate ship"],
  ["Pirate toll", "Pirate ship"],
  ["Pirate engine hacker", "Pirate ship"],
  ["Slaver (hostile)", "Pirate ship"],
  ["Pirate fight near sun", "Pirate ship"],
  ["Rebel fight", "Rebel ship"],
  ["Rebel ship attacking refueling outpost", "Rebel ship"],
  ["Rebel ship warning", "Rebel ship"],
];

/** Template:EventList OVERRIDE HOSTILE1, every row ("MANTIS_HOSTILE": "comprised only of [[Mantis fight]] event"). */
export const OVERRIDE_HOSTILE1: [string, string][] = [
  ["Auto-ship fight in asteroid field", "Auto-ship"],
  ["Auto-ship attacking civilian", "Auto-ship"],
  ["Auto-ship carrying shield virus", "Auto-ship"],
  ["Auto-ship attacking outpost", "Auto-ship"],
  ["Auto-ship warning", "Auto-ship"],
  ["Mantis fight", "Mantis ship"],
  ["Pirate toll", "Pirate ship"],
  ["Pirate fight near pulsar", "Pirate ship"],
  ["Rebel fight", "Rebel ship"],
  ["Auto-ship fight", "Auto-ship"],
  ["Rebel fight near pulsar", "Rebel ship"],
  ["Rebel ship warning", "Rebel ship"],
];

/** Sectors: "4-6 ... hostile_civilian events" (5 INFERRED), "2 ... hostile1 / override_hostile1 events". */
export const HOSTILE_CIVILIAN_DRAWS = 5;
export const HOSTILE1_DRAWS = 2;

/** Sectors whose hostile beacons the two templates fill (Sectors, both Civilian headings). */
export const CIVILIAN_LIST_SECTORS = new Set(["Civilian (Starting) Sector", "Civilian Sector"]);

/**
 * DERIVED (see the file comment): per sector, the hostile fight events whose {{Locations}} names it.
 * Sector names are the wiki "Sectors" headings, as in wiki/sectors.ts.
 */
export const SECTOR_HOSTILE_EVENTS: Record<string, string[]> = {
  "Engi Controlled Sector": [
    "Auto-ship near storage station",
    "Engi distress Rebel fight",
    "Mantis fight (Engi)",
    "Mantis fight choice",
    "Mantis ship attacking civilian",
    "Pirate briber",
    "Pirate engine hacker",
    "Pirate fight",
    "Pirate fight (Engi)",
    "Pirate fight in asteroid field",
    "Pirate fight near pulsar",
    "Pirate fight near sun",
    "Pirate ship distress trap",
    "Pirate toll",
    "Rebel fight",
    "Rebel fight (Engi)",
    "Rebel ship warning",
  ],
  "Engi Homeworlds": [
    "Auto-ship near storage station",
    "Engi distress Rebel fight",
    "Mantis fight (Engi)",
    "Mantis fight choice",
    "Mantis ship attacking civilian",
    "Pirate briber",
    "Pirate engine hacker",
    "Pirate fight",
    "Pirate fight (Engi)",
    "Pirate fight in asteroid field",
    "Pirate fight near pulsar",
    "Pirate fight near sun",
    "Pirate ship distress trap",
    "Pirate toll",
    "Rebel fight",
    "Rebel fight (Engi)",
    "Rebel ship warning",
  ],
  "Zoltan Controlled Sector": [
    "Auto-ship fight",
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning in nebula",
    "Engi fight",
    "Mantis fight (Zoltan)",
    "Mantis outcasts",
    "Pirate briber",
    "Pirate fight (Zoltan)",
    "Pirate ship distress trap",
    "Rebel fight",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Rebel fight near pulsar",
    "Rock fight in nebula",
    "Zoltan border police",
    "Zoltan fight",
    "Zoltan fight in asteroid field",
    "Zoltan retake the ship",
  ],
  "Zoltan Homeworlds": [
    "Auto-ship fight",
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning in nebula",
    "Engi fight",
    "Mantis fight (Zoltan)",
    "Mantis outcasts",
    "Pirate briber",
    "Pirate fight (Zoltan)",
    "Pirate ship distress trap",
    "Rebel fight",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Rebel fight near pulsar",
    "Rock fight in nebula",
    "Zoltan border police",
    "Zoltan fight",
    "Zoltan fight in asteroid field",
    "Zoltan retake the ship",
  ],
  "Abandoned Sector": [
    "Auto-ship fight",
    "Lanius fight",
    "Lanius fight distress",
    "Lanius fight in asteroid field",
    "Lanius fight near pulsar",
    "Lanius fight with friendly ASB support",
    "Lanius lone ship",
    "Lanius powered-down ship",
    "Lanius ship absorbing automated scout",
    "Lanius ship absorbing jump beacon",
    "Lanius ship attacking civilian",
    "Lanius ship attacking civilian distress",
    "Lanius ship salvager",
    "Pirate briber",
    "Pirate fight (Lanius)",
    "Pirate ship attacking civilian (Lanius)",
    "Pirate ship distress trap",
    "Rebel fight",
    "Rebel fight (Lanius)",
  ],
  "Mantis Controlled Sector": [
    "Auto-ship fight in asteroid field",
    "Auto-ship warning",
    "Mantis fight",
    "Mantis fight choice",
    "Mantis fight near sun",
    "Mantis ship attacking civilian",
    "Mantis ship-collectors",
    "Pirate ship distress trap",
    "Rebel fight",
    "Rebel fight near pulsar",
    "Rebel transport ship",
  ],
  "Mantis Homeworlds": [
    "Auto-ship fight in asteroid field",
    "Auto-ship warning",
    "Mantis fight",
    "Mantis fight choice",
    "Mantis fight near sun",
    "Mantis ship attacking civilian",
    "Mantis ship-collectors",
    "Pirate ship distress trap",
    "Rebel fight",
    "Rebel fight near pulsar",
    "Rebel transport ship",
  ],
  "Pirate Controlled Sector": [
    "Auto-ship fight",
    "Auto-ship fight in asteroid field",
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning in nebula",
    "Pirate briber",
    "Pirate engine hacker",
    "Pirate fight",
    "Pirate fight in asteroid field",
    "Pirate fight in nebula",
    "Pirate fight near pulsar",
    "Pirate fight near sun",
    "Pirate ship distress trap",
    "Pirate toll",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Slaver (hostile)",
    "The mercenary",
  ],
  "Rebel Controlled Sector": [
    "Auto-ship fight",
    "Auto-ship fight in asteroid field",
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near sensor station",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning",
    "Auto-ship warning in nebula",
    "Pirate ship distress trap",
    "Rebel defector",
    "Rebel fight",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Rebel fight near pulsar",
    "Rebel fight with boarders",
    "Rebel ship attacking refueling outpost",
    "Rebel ship warning",
    "Rebel transport ship",
  ],
  "Rebel Stronghold": [
    "Auto-ship fight",
    "Auto-ship fight in asteroid field",
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near sensor station",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning",
    "Auto-ship warning in nebula",
    "Pirate ship distress trap",
    "Rebel defector",
    "Rebel fight",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Rebel fight near pulsar",
    "Rebel fight with boarders",
    "Rebel ship attacking refueling outpost",
    "Rebel ship warning",
    "Rebel transport ship",
  ],
  "Rock Controlled Sector": [
    "Mantis ship with Rock body parts",
    "Pirate ship distress trap",
    "Rock atheists",
    "Rock fight",
    "Rock fight in asteroid field",
    "Rock fight with boarders",
    "Rock fight with boarders in asteroid field",
    "Rock pirates fight",
    "Rock pirates fight in asteroid field",
    "Rock pirates fight near sun",
    "The mercenary",
  ],
  "Rock Homeworlds": [
    "Mantis ship with Rock body parts",
    "Pirate ship distress trap",
    "Rock atheists",
    "Rock fight",
    "Rock fight in asteroid field",
    "Rock fight with boarders",
    "Rock fight with boarders in asteroid field",
    "Rock pirates fight",
    "Rock pirates fight in asteroid field",
    "Rock pirates fight near sun",
    "Rock war vessel encounter",
    "The mercenary",
  ],
  "Slug Controlled Nebula": [
    "Auto-ship attacking outpost",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Mantis fight (Slug)",
    "Mantis fight in nebula (Slug)",
    "Pirate briber",
    "Pirate fight (Slug)",
    "Pirate fight choice in nebula",
    "Pirate ship distress trap",
    "Pirate ship selling weapon",
    "Rebel fight (Slug)",
    "Rebel fight chance in nebula",
    "Rebel fight choice in nebula",
    "Rebel fight in plasma storm",
    "Rebel transport ship",
    "Slug drink",
    "Slug fight",
    "Slug fight in nebula",
    "Slug fight in plasma storm",
    "Slug hacker (medical)",
    "Slug hacker (oxygen)",
    "Slug oxygen malfunction",
    "Slug store ship",
    "The mercenary",
  ],
  "Slug Home Nebula": [
    "Auto-ship attacking outpost",
    "Auto-ship near storage station",
    "Auto-ship near storage station in nebula",
    "Mantis fight (Slug)",
    "Mantis fight in nebula (Slug)",
    "Pirate briber",
    "Pirate fight (Slug)",
    "Pirate fight choice in nebula",
    "Pirate ship distress trap",
    "Pirate ship selling weapon",
    "Rebel fight (Slug)",
    "Rebel fight chance in nebula",
    "Rebel fight choice in nebula",
    "Rebel fight in plasma storm",
    "Rebel transport ship",
    "Slug drink",
    "Slug fight",
    "Slug fight in nebula",
    "Slug fight in plasma storm",
    "Slug hacker (medical)",
    "Slug hacker (oxygen)",
    "Slug oxygen malfunction",
    "Slug store ship",
    "The mercenary",
  ],
  "Uncharted Nebula": [
    "Auto-ship fight in nebula",
    "Auto-ship fight in plasma storm",
    "Auto-ship near storage station in nebula",
    "Auto-ship warning in nebula",
    "Mantis fight choice in nebula",
    "Mantis fight in nebula",
    "Pirate briber",
    "Pirate fight in nebula",
    "Pirate ship distress trap",
    "Pirate ship selling weapon",
    "Rebel fight chance in nebula",
    "Rebel fight choice in nebula",
    "Rebel fight in nebula",
    "Rebel fight in plasma storm",
    "Rock ship in plasma storm",
  ],
  "Hidden Crystal Worlds": [
    "Auto-ship fight (Crystal)",
    "Crystal fight",
    "Crystal fight with surrender offer (Human crew)",
    "Crystal fight with surrender offer (hull repairs)",
    "Crystalline men buried",
    "Crystalline ship messaging about Rebels",
    "Federation deserters",
    "Rebel fight (Crystal)",
  ],
  "The Last Stand": [
    "Fight in Last Stand",
    "Rebel fight",
    "Rebel fight among Federation and Rebel fleets",
    "Rebel fight among Rebel fleet",
    "Rebel ship attacking refueling outpost",
  ],
};
export const HOSTILE_SHIP: Record<string, string> = {
  "Auto-ship attacking outpost": "Auto-ship",
  "Auto-ship fight": "Auto-ship",
  "Auto-ship fight (Crystal)": "Auto-ship",
  "Auto-ship fight in asteroid field": "Auto-ship",
  "Auto-ship fight in nebula": "Auto-ship",
  "Auto-ship fight in plasma storm": "Auto-ship",
  "Auto-ship near sensor station": "Auto-ship",
  "Auto-ship near storage station": "Auto-ship",
  "Auto-ship near storage station in nebula": "Auto-ship",
  "Auto-ship warning": "Auto-ship",
  "Auto-ship warning in nebula": "Auto-ship",
  "Crystal fight": "Crystal ship",
  "Crystal fight with surrender offer (Human crew)": "Crystal ship",
  "Crystal fight with surrender offer (hull repairs)": "Crystal ship",
  "Crystalline men buried": "Crystal ship",
  "Crystalline ship messaging about Rebels": "Crystal ship",
  "Engi distress Rebel fight": "Rebel Ship",
  "Engi fight": "Engi ship",
  "Federation deserters": "Federation ship",
  "Fight in Last Stand": "Rebel ship",
  "Lanius fight": "Lanius ship",
  "Lanius fight distress": "Lanius ship",
  "Lanius fight in asteroid field": "Lanius ship",
  "Lanius fight near pulsar": "Lanius ship",
  "Lanius fight with friendly ASB support": "Lanius ship",
  "Lanius lone ship": "Lanius ship",
  "Lanius powered-down ship": "Lanius ship",
  "Lanius ship absorbing automated scout": "Lanius ship",
  "Lanius ship absorbing jump beacon": "Lanius ship",
  "Lanius ship attacking civilian": "Lanius ship",
  "Lanius ship attacking civilian distress": "Lanius ship",
  "Lanius ship salvager": "Lanius ship",
  "Mantis fight": "Mantis Ship",
  "Mantis fight (Engi)": "Mantis ship",
  "Mantis fight (Slug)": "Mantis ship",
  "Mantis fight (Zoltan)": "Mantis ship",
  "Mantis fight choice": "Mantis ship",
  "Mantis fight choice in nebula": "Mantis ship",
  "Mantis fight in nebula": "Mantis ship",
  "Mantis fight in nebula (Slug)": "Mantis ship",
  "Mantis fight near sun": "Mantis ship",
  "Mantis outcasts": "Mantis Ship",
  "Mantis ship attacking civilian": "Mantis Ship",
  "Mantis ship with Rock body parts": "Mantis ship",
  "Mantis ship-collectors": "Mantis Fighter",
  "Pirate briber": "Pirate ship",
  "Pirate engine hacker": "Pirate ship",
  "Pirate fight": "Pirate ship",
  "Pirate fight (Engi)": "Pirate ship",
  "Pirate fight (Lanius)": "Pirate ship",
  "Pirate fight (Slug)": "Pirate ship",
  "Pirate fight (Zoltan)": "Pirate ship",
  "Pirate fight choice in nebula": "Pirate ship",
  "Pirate fight in asteroid field": "Pirate ship",
  "Pirate fight in nebula": "Pirate ship",
  "Pirate fight near pulsar": "Pirate ship",
  "Pirate fight near sun": "Pirate ship",
  "Pirate ship attacking civilian (Lanius)": "Pirate ship",
  "Pirate ship distress trap": "Pirate ship",
  "Pirate ship selling weapon": "Pirate ship",
  "Pirate toll": "Pirate ship",
  "Rebel defector": "Rebel ship",
  "Rebel fight": "Rebel ship",
  "Rebel fight (Crystal)": "Rebel ship",
  "Rebel fight (Engi)": "Rebel ship",
  "Rebel fight (Lanius)": "Rebel ship",
  "Rebel fight (Slug)": "Rebel ship",
  "Rebel fight among Federation and Rebel fleets": "Rebel ship",
  "Rebel fight among Rebel fleet": "Rebel ship",
  "Rebel fight chance in nebula": "Rebel ship",
  "Rebel fight choice in nebula": "Rebel ship",
  "Rebel fight in nebula": "Rebel ship",
  "Rebel fight in plasma storm": "Rebel ship",
  "Rebel fight near pulsar": "Rebel ship",
  "Rebel fight with boarders": "Rebel ship",
  "Rebel ship attacking refueling outpost": "Rebel ship",
  "Rebel ship warning": "Rebel ship",
  "Rebel transport ship": "Rebel ship",
  "Rock atheists": "Rock ship",
  "Rock fight": "Rock ship",
  "Rock fight in asteroid field": "Rock ship",
  "Rock fight in nebula": "Rock ship",
  "Rock fight with boarders": "Rock ship",
  "Rock fight with boarders in asteroid field": "Rock ship",
  "Rock pirates fight": "Rock pirate ship",
  "Rock pirates fight in asteroid field": "Rock pirate ship",
  "Rock pirates fight near sun": "Rock pirate ship",
  "Rock ship in plasma storm": "Rock ship",
  "Rock war vessel encounter": "Rock Assault (Elite) ship",
  "Slaver (hostile)": "Pirate ship",
  "Slug drink": "Slug ship",
  "Slug fight": "Slug ship",
  "Slug fight in nebula": "Slug ship",
  "Slug fight in plasma storm": "Slug ship",
  "Slug hacker (medical)": "Slug ship",
  "Slug hacker (oxygen)": "Slug ship",
  "Slug oxygen malfunction": "Slug ship",
  "Slug store ship": "Slug ship",
  "The mercenary": "Pirate ship",
  "Zoltan border police": "Zoltan ship",
  "Zoltan fight": "Zoltan ship",
  "Zoltan fight in asteroid field": "Zoltan ship",
  "Zoltan retake the ship": "Zoltan pirate ship",
};

/** The weighted hostile encounters of a sector, or null when the dump gives nothing for that name. */
export function sectorHostiles(sectorName: string): HostileEntry[] | null {
  if (CIVILIAN_LIST_SECTORS.has(sectorName)) {
    return [
      ...HOSTILE_CIVILIAN.map(([event, ship]) => ({
        event,
        ship,
        weight: HOSTILE_CIVILIAN_DRAWS / HOSTILE_CIVILIAN.length,
      })),
      ...OVERRIDE_HOSTILE1.map(([event, ship]) => ({
        event,
        ship,
        weight: HOSTILE1_DRAWS / OVERRIDE_HOSTILE1.length,
      })),
    ];
  }
  const events = SECTOR_HOSTILE_EVENTS[sectorName];
  if (!events?.length) return null;
  return events.map((event) => ({ event, ship: HOSTILE_SHIP[event], weight: 1 }));
}
